#!/bin/bash

if [ $1 == "upgrade" -o $1 == "install" ]; then

	if [ -f "/usr/local/include/xbian-config/scripts/localpackages" ]; then
		rm "/usr/local/include/xbian-config/scripts/localpackages";
	fi
	
	if [ -f "/usr/local/include/xbian-config/scripts/remotepackages" ]; then
		rm "/usr/local/include/xbian-config/scripts/remotepackages";
	fi

	if [ ! -d "/usr/local/include/xbian-config/scripts" ]; then
		mkdir -p "/usr/local/include/xbian-config/scripts";
	fi

fi