#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>
#

# update/insert Raspberry PI config variable
#  $1 [String] Key
#  $2 [Mixed] Value
updateConfigVarFn() {
	sed -i "/$1=/d" /boot/config.txt
	echo "$1=$2" >> /boot/config.txt
	sed -i '/^$/d' /boot/config.txt
}

# select Raspberry PI config variable
#  $1 [String] Key
selectConfigVarFn() {
	RETURN=$(cat /boot/config.txt | grep $1= | cut -f 2 -d= | sed -e 's/\r//g');
}

# remove Raspberry PI config variable
#  $1 [String] Key
deleteConfigVarFn() {
	sed -i "/$1=/d" /boot/config.txt
}