#!/bin/bash
#
#Copyright 2012 CurlyMo & Hexagon <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

DEFAULTWIDTH=55;
DEFAULTHEIGHT=7;
DEFAULTCOLSEP="!"
DEFAULTDELIMITER="%"

# Show a normal dialog (messagebox)
#  $1 Text
#  $2 (optional) Height
#  $3 (optional) Width
#  $4 (optional) OK Label
showMsgDlg() {
	OKLABEL="$_CLOSE"

	# Default width and height
	HEIGHT=$DEFAULTHEIGHT
	WIDTH=$DEFAULTWIDTH
	# Override width and height
	if [ $# -gt 1 ]; then
		HEIGHT=$2
	fi
	if [ $# -gt 2 ]; then
		WIDTH=$3
	fi
	if [ $# -gt 3 ]; then
		OKLABEL=$4
	fi
	
	# Show messagebox
	dialog \
		--backtitle "$BACKTITLE" \
		--title "$TITLE" \
		--ok-label "$OKLABEL" \
		--msgbox "$1" $HEIGHT $WIDTH
}

# Show a information box
#  $1 Text
#  $2 (optional) Height
#  $3 (optional) Width
showInfoDlg() {
	# Default width and height
	HEIGHT=$DEFAULTHEIGHT
	WIDTH=$DEFAULTWIDTH
	# Override width and height
	if [ $# -gt 1 ]; then
		HEIGHT=$2
	fi
	if [ $# -gt 2 ]; then
		WIDTH=$3
	fi
	
	# Show messagebox
	dialog \
		--backtitle "$BACKTITLE" \
		--title "$TITLE" \
		--infobox "\n$1" $HEIGHT $WIDTH
}

# Show a text dialog
#  $1 File
#  $2 (optional) Height
#  $3 (optional) Width
#  $4 (optional) OK Label
showTextDlg() {
	OKLABEL="$_CLOSE"

	# Default width and height
	HEIGHT=$DEFAULTHEIGHT
	WIDTH=$DEFAULTWIDTH
	# Override width and height
	if [ $# -gt 1 ]; then
		HEIGHT=$2
	fi
	if [ $# -gt 2 ]; then
		WIDTH=$3
	fi
	if [ $# -gt 3 ]; then
		OKLABEL=$4
	fi
	
	# Show messagebox
	dialog \
		--backtitle "$BACKTITLE" \
		--title "$TITLE" \
		--ok-label "$OKLABEL" \
		--textbox "$1" $HEIGHT $WIDTH
}

# Show a yes/no dialog
#  $1 Text
#  $2 (optional) Height
#  $3 (optional) Width
#  $4 (optional) Yes label
#  $5 (optional) No Label
showConfirmDlg() {
	YESLABEL="$_YES"
	NOLABEL="$_NO"

	# Default width and height
	HEIGHT=$DEFAULTHEIGHT
	WIDTH=$DEFAULTWIDTH
	
	# Override width and height
	if [ $# -gt 1 ]; then
		HEIGHT=$2
	fi
	if [ $# -gt 2 ]; then
		WIDTH=$3
	fi
	if [ $# -gt 3 ]; then
		YESLABEL=$4
	fi
	if [ $# -gt 4 ]; then
		NOLABEL=$5
	fi
	# Show yes/no dialog
	dialog \
		--backtitle "$BACKTITLE" \
		--title "$TITLE" \
		--yes-label $YESLABEL \
		--no-label $NOLABEL \
		--yesno "$1" $HEIGHT $WIDTH
}

#Show menu
#  $1 Descriptive text
#  $2 Menu items
#  $3 (optional) Rows
#  $4 (optional) Height
#  $5 (optional) Width
#  $6 (optional) Yes label
#  $7 (optional) No Label
function showMenuDlg() {
	YESLABEL="$_SELECT"
	NOLABEL="$_RETURN"	
	
	if [ $# -gt 2 ]; then
		ROWS=$3;
	else
		ROWS=5;
	fi
	HEIGHT=$(($ROWS+5))
	WIDTH=$(($DEFAULTWIDTH+15));

	if [ $# -gt 3 ]; then
		HEIGHT=$4
	fi
	if [ $# -gt 4 ]; then
		WIDTH=$5
	fi
	if [ $# -gt 5 ]; then
		YESLABEL=$6
	fi
	if [ $# -gt 6 ]; then
		NOLABEL=$7
	fi
	IFS=$DEFAULTDELIMITER;
	RETURN=$( \
		dialog \
			--no-kill \
			--backtitle "$BACKTITLE" \
			--title "$TITLE" \
			--ok-label $YESLABEL \
			--colors \
			--cancel-label $NOLABEL \
			--column-separator "$DEFAULTCOLSEP" \
			--menu "\n$1" $HEIGHT $WIDTH $ROWS \
			$2 3>&1 1>&2 2>&3)
}

# Show radio list
#  $1 Descriptive text
#  $2 Items
#  $3 Rows
#  $4 (optional) Height
#  $5 (optional) Width
#  $6 (optional) Yes label
#  $7 (optional) No Label
function showRadioDlg() {
	YESLABEL="$_SELECT"
	NOLABEL="$_RETURN"
	HEADER=$1;

	if [ $# -gt 2 ]; then
		ROWS=$3;
	else
		ROWS=5;
	fi
	WIDTH=$(($DEFAULTWIDTH+15))
	if [ $# -gt 4 ]; then
		WIDTH=$5
	fi
	
	centerTxtFn "$_SPACEOPTIONSELECT" $(($DEFAULTWIDTH+11))
	HEIGHT=$(($DEFAULTHEIGHT+5));
	if [ $# -gt 3 ]; then
		HEIGHT=$4
	fi
	if [ $# -gt 5 ]; then
		YESLABEL=$6
	fi
	if [ $# -gt 6 ]; then
		NOLABEL=$7
	fi

	IFS=$DEFAULTDELIMITER;
	RETURN=$( \
		dialog \
			--no-kill \
			--ok-label $YESLABEL \
			--colors \
			--cancel-label $NOLABEL \
			--title "$TITLE" \
			--backtitle "$BACKTITLE" \
			--column-separator "$DEFAULTCOLSEP" \
			--no-collapse \
			--radiolist "\n$CENTEREDTXT\n  $HEADER" $HEIGHT $WIDTH $ROWS \
			$2 3>&1 1>&2 2>&3);
}

# Show checklist
#  $1 Descriptive text
#  $2 Items
#  $3 Rows
#  $4 (optional) Height
#  $5 (optional) Width
#  $6 (optional) Yes label
#  $7 (optional) No Label
#  $8 (optional) Opt. label
function showChecklistDlg() {
	YESLABEL="$_SELECT"
	NOLABEL="$_RETURN"
	OPTLABEL=0;
	HEADER=$1;

	if [ $# -gt 2 ]; then
		ROWS=$3;
	else
		ROWS=5;
	fi
	WIDTH=$(($DEFAULTWIDTH+15))
	if [ $# -gt 4 ]; then
		WIDTH=$5
	fi
	
	centerTxtFn "$_SPACECHECKSELECT" $(($DEFAULTWIDTH+11));
	HEIGHT=$(($DEFAULTHEIGHT+5));
	if [ $# -gt 3 ]; then
		HEIGHT=$4
	fi
	if [ $# -gt 5 ]; then
		YESLABEL=$6
	fi
	if [ $# -gt 6 ]; then
		NOLABEL=$7
	fi
	if [ $# -gt 7 ]; then
		OPTLABEL="$8"
	fi
	
	IFS=$DEFAULTDELIMITER;
	RETURN=$( \
		dialog \
			--no-kill \
			--ok-label $YESLABEL \
			--colors \
			--cancel-label $NOLABEL \
			--title "$TITLE" \
			--backtitle "$BACKTITLE" \
			--column-separator "$DEFAULTCOLSEP" \
			--no-collapse \
			--checklist "\n$CENTEREDTXT\n  $HEADER" $HEIGHT $WIDTH $ROWS \
			$2 3>&1 1>&2 2>&3);
}

# Show input dialog
#  $1 Descriptive text
#  $2 Value
#  $3 (optional) Height
#  $4 (optional) Width
#  $5 (optional) Change Label
#  $6 (optional) Cancel Label
function showInputDlg() {
	CHANGELABEL="$_CHANGE"
	CANCELLABEL="$_CANCEL"
	VALUE=$2;
	WIDTH=$DEFAULTWIDTH;
	HEIGHT=$(($DEFAULTHEIGHT+1))
	
	if [ $# -gt 2 ]; then
		HEIGHT=$3
	fi
	if [ $# -gt 3 ]; then
		WIDTH=$4
	fi
	if [ $# -gt 4 ]; then
		CHANGELABEL=$5
	fi
	if [ $# -gt 5 ]; then
		CANCELLABEL=$6
	fi

	RETURN=$( \
		dialog \
			--backtitle "$BACKTITLE" \
			--title "$TITLE" \
			--ok-label $CHANGELABEL \
			--cancel-label $CANCELLABEL \
			--inputbox "$1" $HEIGHT $WIDTH $VALUE \
			3>&1 1>&2 2>&3);
}

# Show password dialog
#  $1 Descriptive text
#  $3 (optional) Height
#  $4 (optional) Width
#  $5 (optional) Change Label
#  $6 (optional) Cancel Label
function showPassDlg() {
	WIDTH=$DEFAULTWIDTH;
	HEIGHT=$(($DEFAULTHEIGHT+2))
	CHANGELABEL=$_CHANGE
	CANCELLABEL=$_CANCEL
	
	if [ $# -gt 2 ]; then
		HEIGHT=$3
	fi
	if [ $# -gt 3 ]; then
		WIDTH=$4
	fi
	if [ $# -gt 4 ]; then
		CHANGELABEL=$5
	fi
	if [ $# -gt 5 ]; then
		CANCELLABEL=$6
	fi

	VALUES=$(dialog \
			--ok-label "$CHANGELABEL" \
			--cancel-label "$CANCELLABEL" \
			--backtitle "$BACKTITLE" \
			--title "$TITLE" \
			--insecure \
			--passwordform "$1" \
			$HEIGHT $WIDTH 0 \
			"$_PASSWORD" 1 3 "" 1 15 15 0 \
			"$_CONFIRM"  2 3 "" 2 15 15 0 \
		3>&1 1>&2 2>&3);
}

# Standard error dialog
function showErrorDlg() {
	centerTxtFn "$_ERROR" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $DEFAULTHEIGHT;
}

function showLoadingDlg() {
	centerTxtFn "$_LOADING" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $DEFAULTHEIGHT;
}

# Show an input form with 2 text fields
# Arguments
#  $1 Descriptive text
#  $2 Label 1
#  $3 Value 1
#  $4 Label 2
#  $5 Value 2
function showInputForm2Dlg() {

	CHANGELABEL="$_CHANGE"
	CANCELLABEL="$_CANCEL"

        WIDTH=$DEFAULTWIDTH;
        HEIGHT=$(($DEFAULTHEIGHT+3))

        RETURN=$( \
                dialog \
                        --backtitle "$BACKTITLE" \
                        --title "$TITLE" \
                        --ok-label "$CHANGELABEL" \
                        --cancel-label "$CANCELLABEL" \
                        --form "$1" $HEIGHT $WIDTH 2 \
                                "$2" 1 3 "$3" 1 16 32 0 \
                                "$4" 2 3 "$5" 2 16 32 0 \
                        3>&1 1>&2 2>&3);
}


# Show an input form with 5 text fields
# Arguments
#  $1 Descriptive text
#  $2 Label 1
#  $3 Value 1
#  $4 Label 2
#  $5 Value 2
#  $6 Label 3
#  $7 Value 3
#  $8 Label 4
#  $9 Value 4
#  $10 Label 5
#  $11 Value 5
function showInputForm5Dlg() {

	LABELW=16;
	
	LABEL1=$2;
	LABEL2=$4;
	LABEL3=$6;
	LABEL4=$8;
	LABEL5=${10};
	if [ ${#LABEL1} -gt $LABELW ]; then
		LABELW=${#LABEL1};
	fi
	if [ ${#LABEL2} -gt $LABELW ]; then
		LABELW=${#LABEL2};
	fi
	if [ ${#LABEL3} -gt $LABELW ]; then
		LABELW=${#LABEL3};
	fi
	if [ ${#LABEL4} -gt $LABELW ]; then
		LABELW=${#LABEL4};
	fi
	if [ ${#LABEL5} -gt $LABELW ]; then
		LABELW=${#LABEL5};
	fi
	LABELW=$(($LABELW+5));

	CHANGELABEL="$_CHANGE"
	CANCELLABEL="$_CANCEL"

	WIDTH=$DEFAULTWIDTH;
	HEIGHT=$(($DEFAULTHEIGHT+6))

	RETURN=$( \
			dialog \
					--backtitle "$BACKTITLE" \
					--title "$TITLE" \
					--ok-label "$CHANGELABEL" \
					--cancel-label "$CANCELLABEL" \
					--form "$1" $HEIGHT $WIDTH 5 \
							"$2" 1 3 "$3" 1 $LABELW 16 15 \
							"$4" 2 3 "$5" 2 $LABELW 16 15 \
							"$6" 3 3 "$7" 3 $LABELW 16 15 \
							"$8" 4 3 "$9" 4 $LABELW 16 15 \
							"${10}" 5 3 "${11}" 5 $LABELW 16 15 \
					3>&1 1>&2 2>&3);
}