#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# Shows the dialog in which users can enter the vc1 license
#  $1 [string] Current License
# Returns
#  $? [Integer]
#  - 1: Change
#  - 0: Cancel
function showLicenseVC1InputDlg() {
	showInputDlg "$_VC1LICENSE:" $1
}

#Shows the license successfully inserted dialog
function showLicenseVC1InsertedDlg() {
	wrapTxtFn "$_VC1INSERTED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT"
	return $?;
}

#Shows the license successfully updated dialog
function showLicenseVC1UpdatedDlg() {
	wrapTxtFn "$_VC1UPDATED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT"
	return $?;
}

function showInvalidLicenseFormatDlg() {
	wrapTxtFn "$_VC1LICENSEINVALID" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT"
	return $?;
}