#!/bin/bash

if [ $1 == "configure" ]; then
	depmod -a
	echo "3) Regenerating SSH keys";
	
	rm /etc/ssh/ssh_host_* && dpkg-reconfigure openssh-server 1>/dev/null 2>/dev/null >/dev/null

	echo "4) Add user xbian to input group";

	if [ $(cat /etc/group | grep xbian | grep input | wc -l) -eq 0 ]; then
		usermod -a -G input xbian;
		if [ $(cat /etc/group | grep xbian | grep input | wc -l) -eq 1 ]; then
			echo "Success: added user xbian to input group" >> /home/xbian/update.log; 
		else 
			echo "Error: Failed to add user xbian to input group" >> /home/xbian/update.log;  
		fi; 
	else 
		echo "Notice: User xbian already member of input group" >> /home/xbian/update.log; 
	fi;

	echo "5) Set system tag to su command";

	chmod +s /bin/su;
	
	echo "6) Set owner of xbmc user folder to xbian";

	chown -R xbian:xbian /home/xbian/.xbmc;
	
	echo "7) Remove double inittab root autologin entries";

	sed -i '/RPICFG_TO_DISABLE/d' /etc/inittab;

	echo "8) Change autologin to xbian user";
	
	sed -i 's/root/xbian/g' /etc/inittab; 
	
	if [ $(cat /etc/inittab | grep xbian | wc -l) -eq 1 ]; then 
		echo "Success: change autologin to xbian" >> /home/xbian/update.log; 
	else 
		echo "Error: Failed to set autologin to xbian" >> /home/xbian/update.log; 
	fi;
	
	echo "*) Remove possibly applied keyboard fix";
	
	sed -i '/\/dev\/tty0/d' /etc/rc.local;

	echo "9) Apply patches";
cat <<\EOF > /tmp/001-bootlocal.patch
--- a/etc/init.d/bootlocal
+++ b/etc/init.d/bootlocal
@@ -43,7 +43,7 @@ case "$1" in
         esac
         ;;
   stop)
-        #No-op
+        sync
         ;;
   *)
         echo "Usage: $SCRIPTNAME {start|stop}" >&2
EOF

	patch --dry-run /etc/init.d/bootlocal < /tmp/001-bootlocal.patch 2>/dev/null >/dev/null; 
	if [ $? == 0 ]; then 
		patch /etc/init.d/bootlocal < /tmp/001-bootlocal.patch 2>/dev/null >/dev/null; 
		echo "Success: applied 001-bootlocal.patch" >> /home/xbian/update.log; 
	else 
		echo "Notice: 001-bootlocal.patch already applied" >> /home/xbian/update.log; 
	fi;

cat <<\EOF > /tmp/002-bashrc.patch
--- a/home/xbian/.bashrc
+++ b/home/xbian/.bashrc
@@ -101,3 +101,5 @@
 if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
	 . /etc/bash_completion
 fi
+
+source /etc/profile.d/hideoutput.sh
EOF

	patch --dry-run /home/xbian/.bashrc < /tmp/002-bashrc.patch 2>/dev/null >/dev/null; 
	if [ $? == 0 ]; then 
		patch /home/xbian/.bashrc < /tmp/002-bashrc.patch 2>/dev/null >/dev/null; 
		echo "Success: applied 002-bashrc.patch" >> /home/xbian/update.log; 
	else 
		echo "Notice: 002-bashrc.patch already applied" >> /home/xbian/update.log; 
	fi;

cat <<\EOF > /tmp/003-hideoutput.patch
--- a/etc/profile.d/hideoutput.sh
+++ b/etc/profile.d/hideoutput.sh
@@ -17,8 +17,8 @@
 #You should have received a copy of the GNU General Public License along 
 #with Xbian. If not, see <http://www.gnu.org/licenses/>
 #
-if [[ $(who am i | grep -wo "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | wc -l) -eq 0 &&  "$TERM" != "screen"  && ! -n "$TMUX"  ]]; then
-        echo -e '\e[40;30m'
-        dmesg -n 1
-        clear
+if [[ -z $SSH_CONNECTION && $(who am i | grep -wo "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | wc -l) -eq 0 && "$(who am i | awk '{print $1}')" == "$(id -urn)" && "$TERM" != "screen" && ! -n "$TMUX" ]]; then
+        clear
-fi
\ No newline at end of file
+        export PS1="\e[40;30m";
+        echo -e '\e[40;30m';
+fi
EOF

	patch --dry-run /etc/profile.d/hideoutput.sh < /tmp/003-hideoutput.patch 2>/dev/null >/dev/null; 
	if [ $? == 0 ]; then 
		patch /etc/profile.d/hideoutput.sh < /tmp/003-hideoutput.patch 2>/dev/null >/dev/null; 
		echo "Success: applied 003-hideoutput.patch" >> /home/xbian/update.log; 
	else 
		echo "Notice: 003-hideoutput.patch already applied" >> /home/xbian/update.log; 
	fi;

cat <<\EOF > /tmp/004-xbian_config.patch
--- a/etc/profile.d/xbian-config.sh
+++ b/etc/profile.d/xbian-config.sh
@@ -17,6 +17,8 @@
 #You should have received a copy of the GNU General Public License along
 #with XBian. If not, see <http://www.gnu.org/licenses/>
 #
-if [ $(id -u) -eq 1001 ]; then
-        sudo xbian-config
+if ! [[ -z $SSH_CONNECTION && $(who am i | grep -wo "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | wc -l) -eq 0 &&  "$TERM" != "screen"  && ! -n "$TMUX" ]]; then
+        if [ $(id -u) -eq 1001 ]; then
+                sudo xbian-config
+        fi
 fi
EOF

	patch --dry-run /etc/profile.d/xbian-config.sh < /tmp/004-xbian_config.patch 2>/dev/null >/dev/null; 
	if [ $? == 0 ]; then 
		patch /etc/profile.d/xbian-config.sh < /tmp/004-xbian_config.patch 2>/dev/null >/dev/null; 
		echo "Success: applied 004-xbian_config.patch" >> /home/xbian/update.log; 
	else 
		echo "Notice: 004-xbian_config.patch already applied" >> /home/xbian/update.log; 
	fi;

cat <<\EOF > /tmp/005-99-input_rules.patch
--- a/etc/udev/rules.d/99-input.rules
+++ b/etc/udev/rules.d/99-input.rules
@@ -1,1 +1,2 @@
 SUBSYSTEM=="input", GROUP="input", MODE="0660"
+KERNEL=="tty0", GROUP="xbian", OWNER="xbian"
EOF

	patch --dry-run /etc/udev/rules.d/99-input.rules < /tmp/005-99-input_rules.patch 2>/dev/null >/dev/null; 
	if [ $? == 0 ]; then 
		patch /etc/udev/rules.d/99-input.rules < /tmp/005-99-input_rules.patch 2>/dev/null >/dev/null; 
		echo "Success: applied 005-99-input_rules.patch" >> /home/xbian/update.log; 
	else 
		echo "Notice: 005-99-input_rules.patch already applied" >> /home/xbian/update.log; 
	fi;

cat <<\EOF > /tmp/006-xbian_version.patch
--- a/etc/xbian_version
+++ b/etc/xbian_version
@@ -1 +1 @@
-1.0
+1.0a2
EOF

	patch --dry-run /etc/xbian_version < /tmp/006-xbian_version.patch 2>/dev/null >/dev/null; 
	if [ $? == 0 ]; then 
		patch /etc/xbian_version < /tmp/006-xbian_version.patch 2>/dev/null >/dev/null; 
		echo "Success: applied 006-xbian_version.patch" >> /home/xbian/update.log; 
	else
		echo "Notice: 006-xbian_version.patch already applied" >> /home/xbian/update.log; 
	fi;

	echo "10) Adding XBOX remove configuration to LIRC";

	if [ $(cat /etc/lirc/lircd.conf | grep "Xbox_Remote" | wc -l) -eq 0 ]; then
cat <<\EOF >> /etc/lirc/lircd.conf
# brand: Microsoft Xbox DVD Receiever (also works with generic)
# remote control: Xbox remote or any remote using RCA DVD player codes
 
begin remote
 
  name  Xbox_Remote
  bits            8
  eps            30
  aeps          100
 
  one             0     0
  zero            0     0
  gap          163983
  toggle_bit_mask 0x0
 
      begin codes
          left                     0xA9
          up                       0xA6
          right                    0xA8
          down                     0xA7
          enter                    0x0B
          1                        0xCE
          2                        0xCD
          3                        0xCC
          4                        0xCB
          5                        0xCA
          6                        0xC9
          7                        0xC8
          8                        0xC7
          9                        0xC6
          0                        0xCF
          menu                     0xF7
          display                  0xD5
          rewind                   0xE2
          ffwd                     0xE3
          play                     0xEA
          pause                    0xE6
          stop                     0xE0
          skip-                    0xDD
          skip+                    0xDF
          title                    0xE5
          info                     0xC3
          back                     0xD8
      end codes
 
end remote
EOF
		echo "Success: XBOX remote config added to lirc" >> /home/xbian/update.log;  
	else 
		echo "Notice: XBOX remote config already present" >> /home/xbian/update.log;  
	fi

	echo "11) Change default CEC settings";

	sed -i 's/<setting id="device_name" value="XBMC" \/>/<setting id="device_name" value="XBian" \/>/g' /home/xbian/.xbmc/userdata/peripheral_data/rpi_2708_1001.xml
	sed -i 's/<setting id="send_inactive_source" value="1" \/>/<setting id="send_inactive_source" value="0" \/>/g' /home/xbian/.xbmc/userdata/peripheral_data/rpi_2708_1001.xml
	sed -i 's/<setting id="standby_devices" value="36037" \/>/<setting id="standby_devices" value="231" \/>/g' /home/xbian/.xbmc/userdata/peripheral_data/rpi_2708_1001.xml
	sed -i 's/<setting id="wake_devices" value="36037" \/>/<setting id="wake_devices" value="231" \/>/g' /home/xbian/.xbmc/userdata/peripheral_data/rpi_2708_1001.xml

	echo "11) Remove unused files"
	
	if [ -f "/etc/udev/rules.d/10-my-media-automount.rules" ]; then 
		rm /etc/udev/rules.d/10-my-media-automount.rules; 
		echo "Success: removed /etc/udev/rules.d/10-my-media-automount.rules" >> /home/xbian/update.log; 
	else 
		echo "Notice: /etc/udev/rules.d/10-my-media-automount.rules doesn't exists" >> /home/xbian/update.log; 
	fi;
	
	if [ -f "/usr/local/share/doc/LICENSE.GPL" ]; then 
		rm /usr/local/share/doc/LICENSE.GPL; 
		echo "Success: removed /usr/local/share/doc/LICENSE.GPL" >> /home/xbian/update.log; 
	else 
		echo "Notice: /usr/local/share/doc/LICENSE.GPL doesn't exists" >> /home/xbian/update.log; 
	fi;
	
	if [ -f "/usr/local/share/doc/README.linux" ]; then 
		rm /usr/local/share/doc/README.linux; 
		echo "Success: removed /usr/local/share/doc/README.linux" >> /home/xbian/update.log; 
	else 
		echo "Notice: /usr/local/share/doc/README.linux doesn't exists" >> /home/xbian/update.log; 
	fi;
	
	if [ -f "/usr/local/share/doc/copying.txt" ]; then 
		rm /usr/local/share/doc/copying.txt; 
		echo "Success: removed /usr/local/share/doc/copying.txt" >> /home/xbian/update.log; 
	else 
		echo "Notice: /usr/local/share/doc/copying.txt doesn't exists" >> /home/xbian/update.log; 
	fi;
	
	if [ -f "/usr/local/share/icons/hicolor/icon-theme.cache" ]; then 
		rm /usr/local/share/icons/hicolor/icon-theme.cache; 
		echo "Success: removed /usr/local/share/icons/hicolor/icon-theme.cache" >> /home/xbian/update.log; 
	else 
		echo "Notice: /usr/local/share/icons/hicolor/icon-theme.cache doesn't exists" >> /home/xbian/update.log; 
	fi;
	
	echo "12) Starting XBMC";
	/etc/init.d/xbmc start;

	echo "13) Make kernel 3.6.1 the default"
	cp /boot/kernel3_6_1.img /boot/kernel.img
		
	echo "---UPDATE LOG---"
	cat "/home/xbian/update.log"
fi
