#!/bin/bash

if [ $1 == "install" ]; then
	echo "1) Stopping XBMC";
	/etc/init.d/xbmc stop 1>/dev/null 2>/dev/null >/dev/null

	if [ -f /home/xbian/update.log ]; then
		rm /home/xbian/update.log;
	fi

	if [ ! -d /var/lib/polkit-1/localauthority/50-local.d ]; then
		mkdir -p /var/lib/polkit-1/localauthority/50-local.d;
	fi
	
	echo "2) Installing new files"
fi