#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|          Global variables          |
#|------------------------------------|

# The arguments this module accepts
ARGUMENTS=(guires webserver);
GUIRES=(480 540 720 1080);

#|------------------------------------|
#|          Include files             |
#|------------------------------------|

source $BASEPATH/modules/xbmc/functions
source $BASEPATH/modules/xbmc/dialogs

#|------------------------------------|
#|           Main program             |
#|------------------------------------|

# Executes the GUI version of this module
function showGUIFn() {
	showXBMCSettingsDlg;
	if [ $? -eq 0 ]; then
		if [ $RETURN -eq 1 ]; then
			showXBMCGUIResDlg;
			if [ $? -eq 0 ]; then
				setXBMCGUIResFn ${GUIRES[$(($RETURN-1))]};
				if [ $? -eq 1 ]; then
					showXBMCGUIResSuccessDlg;
				else
					showXBMCGUIResFailedDlg;
				fi
				showGUIFn;
			else
				showGUIFn;
			fi
		elif [ $RETURN -eq 2 ]; then
			showXBMCWebserverDlg;
			STATE=$?;
			setXBMCWebserverFn $STATE;
			if [ $? -eq 1 ]; then
				if [ $STATE -eq 0 ]; then
					showXBMCWebserverSuccessEnabledDlg;
				else
					showXBMCWebserverSuccessDisabledDlg;
				fi
			else
				if [ $STATE -eq 0 ]; then
					showXBMCWebserverFailedEnableDlg;
				else
					showXBMCWebserverFailedDisableDlg;
				fi
			fi
			showGUIFn;
		fi
	fi
}

# Executes the command line version of this module
#  $1 Argument [String]
#  $2 XBMC setting [String]
# guires
#  $3 [String] list|select|update
#  $4 [Integer] resolution
# webserver
#  $3 [String] select[enable|disable]
# Returns
#  *webserver
#  - 1: Enable|Success
#  - 0: Disabled|Failed
#  *guires
#  - @: Resolution options
#  - 1: Success
#  - 0: Failed
function showCMDFn() {
	case $1 in
		guires)
			if [ $# -eq 2 ]; then
				if [ "$2" == "list" ]; then
					for RES in ${GUIRES[@]}; do
						echo $RES;
					done
				elif [ "$2" == "select" ]; then
					getXBMCGUIResFn
					if [ $CURRES -eq 0 ]; then
						echo -2;
					else
						echo $CURRES;
					fi
				fi
			elif [ $# -eq 3 ]; then
				if [ "$2" == "update" ]; then
					if [ ${#3} -ge 3 ]; then
						MATCH=0;
						for RES in ${GUIRES[@]}; do
							if [ $RES -eq $3 ]; then
								MATCH=1;
							fi
						done
						if [ $MATCH -eq 1 ]; then
							setXBMCGUIResFn $3
							echo $?;
						else
							echo -3;
						fi
					else
						echo -3;
					fi
				else
					echo -1
				fi
			else
				echo -1;
			fi
		;;
		webserver)
			if [ $# -eq 2 ]; then
				if [ "$2" == "select" ]; then
					getXBMCWebserverFn;
					echo $?;
				elif [ "$2" == "enable" ]; then
					setXBMCWebserverFn 1
					echo $?
				elif [ "$2" == "disable" ]; then
					setXBMCWebserverFn 0
					echo $?
				else
					echo -1
				fi
			else
				echo -1;
			fi
		;;
	esac;
}