#!/bin/bash

DEBUG=0;

function showyesno() {
	return 0;
}
function showdialog() {
	return 0
}

if [ $1 == "configure" ]; then

	echo "3) Removing swap partition"

	source /usr/local/include/xbian-config/scripts/resizesd
	resizesd >/dev/null

	echo "4) Apply patches";

	if [ $(cat /etc/motd 2>/dev/null | grep xbianonpi | wc -l) -eq 0 ]; then

cat <<\EOF > /etc/motd
------------------------------------------------------------------
     Y88b d88P  888888b.   8888888        d8888 888b    888
      Y88o88P   888  .88P    888        d88P888 88888b  888
       Y888P    8888888K.    888       d88P 888 888Y88b 888
       d888b    888  "Y88b   888      d88P  888 888 Y88b888
     d88P Y88b  888   d88P   888    d8888888888 888   Y8888
    d88P   Y88b 8888888P"  8888888 d88P     888 888    Y888
------------------------------------------------------------------
XBian v1.0 - XBMC on the Raspbery Pi, Bleeding Edge, 2012
Find up as: http://www.xbian.org / https://github.com/xbianonpi/xbian

XBian and all it's packages are distributed as free software; the
exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright. XBian itself is
distributed under the GNU GENERAL PUBLIC LICENSE v3. A full copy
of this license can be found under /etc/xbian_copying

XBian v1.0 comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

!Importance notice!
rpi-update breaks core features of xbian, use it at your own risk

EOF

		if [ $(cat /etc/motd | grep xbianonpi | wc -l) -eq 1 ]; then
			echo "Success: applied 001-motd.patch" >> /home/xbian/update.log;
		fi
	else
		echo "Notice: 001-motd.patch already applied" >> /home/xbian/update.log;
	fi

cat <<\EOF > /tmp/002-confluence.patch
--- a/usr/local/share/xbmc/addons/skin.confluence/720p/SettingsSystemInfo.xml
+++ b/usr/local/share/xbmc/addons/skin.confluence/720p/SettingsSystemInfo.xml
@@ -276,7 +276,7 @@
 				<control type="label" id="52">
 					<description>XBMC BUILD Version</description>
 					<posx>750</posx>
-					<posy>400</posy>
+					<posy>450</posy>
 					<width>730</width>
 					<label>144</label>
 					<align>right</align>
@@ -284,7 +284,7 @@
 					<shadowcolor>black</shadowcolor>
 					<font>font13_title</font>
 				</control>
-				<control type="label">
+				<!--<control type="label">
 					<description>CPU Text</description>
 					<posx>420</posx>
 					<posy>450</posy>
@@ -304,7 +304,7 @@
 					<width>320</width>
 					<height>16</height>
 					<info>System.CPUUsage</info>
-				</control>
+				</control>-->
 				<control type="label">
 					<description>Memory Text</description>
 					<posx>420</posx>
EOF

	patch --dry-run /usr/local/share/xbmc/addons/skin.confluence/720p/SettingsSystemInfo.xml < /tmp/002-confluence.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then 
		patch /usr/local/share/xbmc/addons/skin.confluence/720p/SettingsSystemInfo.xml < /tmp/002-confluence.patch 2>/dev/null >/dev/null;
		echo "Success: applied 002-confluence.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 002-confluence.patch already applied" >> /home/xbian/update.log;
	fi;

cat <<\EOF > /tmp/003-umountfs.patch
--- a/etc/init.d/umountfs
+++ b/etc/init.d/umountfs
@@ -99,10 +99,18 @@
 	then
 		if [ "$VERBOSE" = no ]
 		then
+                        log_action_begin_msg "Sync local filesystems part 1"
+                        sync
+                        log_action_begin_msg "Sync local filesystems part 2"
+                        sync
 			log_action_begin_msg "Unmounting local filesystems"
 			fstab-decode umount -f -r -d $REG_MTPTS
 			log_action_end_msg $?
 		else
+                        log_action_begin_msg "Sync local filesystems part 1"
+                        sync
+                        log_action_begin_msg "Sync local filesystems part 2"
+                        sync
 			log_daemon_msg "Will now unmount local filesystems"
 			fstab-decode umount -f -v -r -d $REG_MTPTS
 			log_end_msg $?
EOF

	patch --dry-run /etc/init.d/umountfs < /tmp/003-umountfs.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then 
		patch /etc/init.d/umountfs < /tmp/003-umountfs.patch 2>/dev/null >/dev/null;
		echo "Success: applied 003-umountfs.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 003-umountfs.patch already applied" >> /home/xbian/update.log;
	fi;

cat <<\EOF > /tmp/004-umountroot.patch
--- a/etc/init.d/umountroot
+++ b/etc/init.d/umountroot
@@ -15,6 +15,11 @@
 . /lib/lsb/init-functions

 do_stop () {
+
+	[ "$VERBOSE" = no ] || log_action_begin_msg "Sync root filesystem part 1"
+	sync
+	[ "$VERBOSE" = no ] || log_action_begin_msg "Sync root filesystem part 2"
+	sync
 	[ "$VERBOSE" = no ] || log_action_begin_msg "Mounting root filesystem read-only"
 	MOUNT_FORCE_OPT=
 	[ "$(uname -s)" = "GNU/kFreeBSD" ] && MOUNT_FORCE_OPT=-f
EOF

	patch --dry-run /etc/init.d/umountroot < /tmp/004-umountroot.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then
		patch /etc/init.d/umountroot < /tmp/004-umountroot.patch 2>/dev/null >/dev/null;
		echo "Success: applied 004-umountroot.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 004-umountroot.patch already applied" >> /home/xbian/update.log;
	fi;

cat <<\EOF > /tmp/005-xbmc.patch
--- a/etc/init.d/xbmc
+++ b/etc/init.d/xbmc
@@ -45,7 +45,6 @@
 {
 	if [ $(($(ps -A | grep xbmc.bin | wc -l))) -eq 0 ]; then
 		start-stop-daemon -c xbian -u xbian --start --quiet --pidfile $PIDFILE --exec $DAEMON --test || return 1;
-		chmod a+rw /dev/vchiq
 		echo $(chvt 1; start-stop-daemon -c xbian -u xbian -m --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS; RETURN=$?; case $RETURN in 0 ) echo do normal exit.....; chvt 2; ;; 64 ) echo do power off.....; sudo halt ;; 66 ) echo do reboot.....; sudo reboot; ;; esac || return 2) &exit
 	fi
 }
@@ -53,7 +52,7 @@
 do_stop()
 {
        start-stop-daemon --stop --signal 9 --retry 5 --quiet --pidfile $PIDFILE
-	   chvt 2;
+       chvt 2;
 }

 case "$1" in
EOF

	patch --dry-run /etc/init.d/xbmc < /tmp/005-xbmc.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then
		patch /etc/init.d/xbmc < /tmp/005-xbmc.patch 2>/dev/null >/dev/null;
		echo "Success: applied 005-xbmc.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 005-xbmc.patch already applied" >> /home/xbian/update.log;
	fi;

cat <<\EOF > /tmp/006-hideoutput.patch
--- a/etc/profile.d/hideoutput.sh
+++ b/etc/profile.d/hideoutput.sh
@@ -18,10 +18,27 @@
 #with Xbian. If not, see <http://www.gnu.org/licenses/>
 #
 if [[ $(who am i | awk '{print $2}') == "tty1" ]]; then
-	clear
-	export PS1="\e[40;30m";
-	echo -e '\e[40;30m';
+
+	# Hide console output
+        clear
+        export PS1="\e[40;30m";
+        echo -e '\e[40;30m';
+
 else
-	export PS1="\[\e[40;0m\]\u@\h:\w# "
-	echo -e '\e[40;0m';
+
+        # Restore console output
+        export PS1="\[\e[40;0m\]\u@\h:\w# "
+        echo -e '\e[40;0m';
+
+        # Reset/Restore framebuffer
+        GEO=$(sudo fbset -s | grep geometry);GEO_ARR=($GEO);
+        if [ ${#GEO_ARR[@]} -eq 6 ]; then
+                XRES=$(echo $GEO | cut -f 2 -d" ")
+                YRES=$(echo $GEO | cut -f 3 -d" ")
+                VXRES=$(echo $GEO | cut -f 4 -d" ")
+                VYRES=$(echo $GEO | cut -f 5 -d" ")
+                DEPTH=$(echo $GEO | cut -f 6 -d" ")
+                sudo fbset -xres $XRES -yres $YRES -vxres $VXRES -vyres $VYRES -depth $DEPTH
+        fi
+
 fi
EOF

	patch --dry-run /etc/profile.d/hideoutput.sh < /tmp/006-hideoutput.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then 
		patch /etc/profile.d/hideoutput.sh < /tmp/006-hideoutput.patch 2>/dev/null >/dev/null;
		echo "Success: applied 006-hideoutput.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 006-hideoutput.patch already applied" >> /home/xbian/update.log;
	fi;

cat <<\EOF > /tmp/007-input.patch
--- a/etc/udev/rules.d/99-input.rules
+++ b/etc/udev/rules.d/99-input.rules
@@ -1,2 +1 @@
 SUBSYSTEM=="input", GROUP="input", MODE="0660"
-KERNEL=="tty0", GROUP="xbian", OWNER="xbian"
EOF

	patch --dry-run /etc/udev/rules.d/99-input.rules < /tmp/007-input.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then 
		patch /etc/udev/rules.d/99-input.rules < /tmp/007-input.patch 2>/dev/null >/dev/null;
		echo "Success: applied 007-input.patch ">> /home/xbian/update.log;
	else
		echo "Notice: 007-input.patch already applied" >> /home/xbian/update.log;
	fi;

cat <<\EOF > /tmp/008-usbmount.patch
--- a/etc/usbmount/usbmount.conf
+++ b/etc/usbmount/usbmount.conf
@@ -14,7 +14,7 @@

 # Filesystem types: removable storage devices are only mounted if they
 # contain a filesystem type which is in this list.
-FILESYSTEMS="ntfs vfat ext2 ext3 ext4 hfsplus"
+FILESYSTEMS="ntfs vfat ext2 ext3 ext4 hfsplus exfat"

 #############################################################################
 # WARNING!                                                                  #
@@ -46,7 +46,13 @@
 # For example, "-fstype=vfat,gid=floppy,dmask=0007,fmask=0117" would add
 # the options "gid=floppy,dmask=0007,fmask=0117" when a vfat filesystem
 # is mounted.
-FS_MOUNTOPTIONS="dmask=0777,fmask=0777"
+FS_MOUNTOPTIONS="-fstype=ntfs,gid=xbian,uid=xbian,umask=0 \
+		 -fstype=vfat,gid=xbian,uid=xbian,umask=0 \
+		 -fstype=ext2,gid=xbian,uid=xbian,umask=0 \
+		 -fstype=ext3,gid=xbian,uid=xbian,umask=0 \
+		 -fstype=ext4,gid=xbian,uid=xbian,umask=0 \
+		 -fstype=hfsplus,gid=xbian,uid=xbian,umask=0 \
+		 -fstype=exfat,gid=xbian,uid=xbian,umask=0"

 # If set to "yes", more information will be logged via the syslog
 # facility.
EOF

	patch --dry-run /etc/usbmount/usbmount.conf < /tmp/008-usbmount.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then
		patch /etc/usbmount/usbmount.conf < /tmp/008-usbmount.patch 2>/dev/null >/dev/null;
		echo "Success: applied 008-usbmount.patch.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 008-usbmount.patch.patch already applied" >> /home/xbian/update.log;
	fi;

cat <<\EOF > /tmp/009-xbian_version.patch
--- a/etc/xbian_version
+++ b/etc/xbian_version
@@ -1 +1 @@
-1.0a3
+1.0a4
EOF

	patch --dry-run /etc/xbian_version < /tmp/009-xbian_version.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then 
		patch /etc/xbian_version < /tmp/009-xbian_version.patch 2>/dev/null >/dev/null;
		echo "Success: applied 009-xbian_version.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 009-xbian_version.patch already applied" >> /home/xbian/update.log;
	fi;

	if [ $(cat /etc/sudoers | grep fbset | wc -l) -eq 0 ]; then
		sed -i 's/\/sbin\/reboot/\/sbin\/reboot, \/bin\/fbset/g' /etc/sudoers
		echo "Success: applied 010-sudoers.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 010-sudoers.patch already applied" >> /home/xbian/update.log;
	fi;

	if [ ! -f "/lib/udev/rules.d/99-local-xbian.rules" ]; then
		echo "KERNEL==\"tty0\", GROUP=\"xbian\", OWNER=\"xbian\"" > /lib/udev/rules.d/99-local-xbian.rules
		if [ -f "/lib/udev/rules.d/99-local-xbian.rules" ]; then
			echo "Success: applied 011-xbian.patch" >> /home/xbian/update.log;
		fi;
	else
		echo "Notice: 011-xbian.patch already applied" >> /home/xbian/update.log;
	fi;

cat <<\EOF > /tmp/012-remote.patch
--- a/usr/local/share/xbmc/system/keymaps/remote.xml
+++ b/usr/local/share/xbmc/system/keymaps/remote.xml
@@ -63,10 +63,11 @@
       <volumeminus>VolumeDown</volumeminus>
       <mute>Mute</mute>
       <power>XBMC.ShutDown()</power>
-      <myvideo>XBMC.ActivateWindow(MyVideos)</myvideo>
+      <myvideo>XBMC.ActivateWindow(Videos,MovieTitles)</myvideo>
       <mymusic>XBMC.ActivateWindow(MyMusic)</mymusic>
       <mypictures>XBMC.ActivateWindow(MyPictures)</mypictures>
-      <mytv>XBMC.ActivateWindow(MyPVR)</mytv>
+      <mytv>XBMC.ActivateWindow(Videos,TvShowTitles)</mytv>
+      <mypvr>XBMC.ActivateWindow(MyPVR)</mypvr>
       <guide>XBMC.ActivateWindowAndFocus(MyPVR, 31,0, 10,0)</guide>
       <livetv>XBMC.ActivateWindowAndFocus(MyPVR, 32,0, 11,0)</livetv>
       <liveradio>XBMC.ActivateWindowAndFocus(MyPVR, 33,0, 12,0)</liveradio>
EOF

	patch --dry-run /usr/local/share/xbmc/system/keymaps/remote.xml < /tmp/012-remote.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then
		patch /usr/local/share/xbmc/system/keymaps/remote.xml < /tmp/012-remote.patch 2>/dev/null >/dev/null;
		echo "Success: applied 012-remote.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 012-remote.patch already applied" >> /home/xbian/update.log;
	fi;

cat <<\EOF > /tmp/013-lircmap.patch
--- a/usr/local/share/xbmc/system/Lircmap.xml
+++ b/usr/local/share/xbmc/system/Lircmap.xml
@@ -10,6 +10,7 @@
 
 <lircmap>
 	<remote device="mceusb">
+	<altname>srm7500</altname>	
 		<play>Play</play>
 		<pause>Pause</pause>
 		<stop>Stop</stop>
@@ -510,4 +511,31 @@
 		<mypictures>yellow</mypictures>
 		<myvideo>blue</myvideo>
 	</remote>
+
+	<remote device="smt1000t">
+		<mute>KEY_MUTE</mute>
+		<mypvr>KEY_TV</mypvr>
+		<subtitle>KEY_TEXT</subtitle>
+		<language>KEY_AUDIO</language>
+		<menu>KEY_MENU</menu>
+		<title>KEY_INFO</title>
+		<select>KEY_OK</select>
+		<stop>KEY_EXIT</stop>
+		<info>KEY_EPG</info>
+		<pageplus>KEY_CHANNELUP</pageplus>
+		<pageminus>KEY_CHANNELDOWN</pageminus>
+		<myvideo>KEY_RED</myvideo>
+		<mymusic>KEY_GREEN</mymusic>
+		<mytv>KEY_YELLOW</mytv>
+		<mypictures>KEY_BLUE</mypictures>
+	</remote>
+
+	<remote device="srm7500">
+		<display>KEY_SETUP</display>
+		<title>KEY_CONTEXT_MENU</title>
+		<star>KEY_STAR</star>
+		<subtitle>KEY_TEXT</subtitle>
+		<hash>KEY_HASHTAG</hash>
+		<aspectratio>KEY_SWITCHVIDEOMODE</aspectratio>
+	</remote>
 </lircmap>
EOF

	patch --dry-run /usr/local/share/xbmc/system/Lircmap.xml < /tmp/013-lircmap.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then 
		patch /usr/local/share/xbmc/system/Lircmap.xml < /tmp/013-lircmap.patch 2>/dev/null >/dev/null;
		echo "Success: applied 013-lircmap.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 013-lircmap.patch already applied" >> /home/xbian/update.log;
	fi

cat <<\EOF > /tmp/014-rpi.patch
--- a/lib/udev/rules.d/10-local-rpi.rules
+++ b/lib/udev/rules.d/10-local-rpi.rules
@@ -1 +1 @@
-SUBSYSTEM=="vchiq", GROUP="video", MODE="0660"
+SUBSYSTEM=="vchiq", GROUP="video", MODE="0666"
EOF

	if [ -f "/lib/udev/rules.d/10-local-rpi.rules" ]; then
		patch --dry-run /lib/udev/rules.d/10-local-rpi.rules < /tmp/014-rpi.patch 2>/dev/null >/dev/null;
		if [ $? == 0 ]; then 
			patch /lib/udev/rules.d/10-local-rpi.rules < /tmp/014-rpi.patch 2>/dev/null >/dev/null;
			echo "Success: applied 014-rpi.patch" >> /home/xbian/update.log;
		else
			echo "Notice: 014-rpi.patch already applied" >> /home/xbian/update.log;
		fi;
	else
		echo "SUBSYSTEM==\"vchiq\", GROUP=\"video\", MODE=\"0666\"" > /lib/udev/rules.d/10-local-rpi.rules
		echo "Success: applied 014-rpi.patch" >> /home/xbian/update.log;
	fi
	
cat <<\EOF > /tmp/015-bootlocal.patch
--- a/etc/init.d/bootlocal
+++ b/etc/init.d/bootlocal
@@ -36,7 +36,8 @@
 case "$1" in
   start)
         [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" ""
-         /etc/rc.local
+        /etc/rc.local
+        echo 1 | sudo tee /proc/sys/vm/drop_caches >/dev/null
         case "$?" in
                 0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                 2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
EOF

	patch --dry-run /etc/init.d/bootlocal < /tmp/015-bootlocal.patch 2>/dev/null >/dev/null;
	if [ $? == 0 ]; then 
		patch /etc/init.d/bootlocal < /tmp/015-bootlocal.patch 2>/dev/null >/dev/null;
		echo "Success: applied 015-bootlocal.patch" >> /home/xbian/update.log;
	else
		echo "Notice: 015-bootlocal.patch already applied" >> /home/xbian/update.log;
	fi

	echo "/opt/vc/lib" > /etc/ld.so.conf.d/00-vmcs.conf

	echo "5) Updating XBMC configuration"
	if [ -f "/home/xbian/.xbmc/userdata/sources.xml" ]; then
		if [ $(cat /home/xbian/.xbmc/userdata/sources.xml | grep "http://fusion.xbmchub.com/" | wc -l) -eq 0 ];	then
			cp /home/xbian/.xbmc/userdata/sources.xml /home/xbian/.xbmc/userdata/sources.xml.xbian
			sed -i '/<\/files>/d' /home/xbian/.xbmc/userdata/sources.xml
			sed -i '/<\/sources>/d' /home/xbian/.xbmc/userdata/sources.xml
			echo -e "\t<source>\n\t\t<name>XBMC HUB Fusion</name>\n\t\t<path pathversion=\"1\">http://fusion.xbmchub.com/</path>\n\t</source>\n    </files>\n</sources>" >> /home/xbian/.xbmc/userdata/sources.xml
			if [ $(cat /home/xbian/.xbmc/userdata/sources.xml | grep "http://fusion.xbmchub.com/" | wc -l) -eq 1 ];	then
				echo "Success: added xbmc fuse" >> /home/xbian/update.log;
			else
				echo "Error: failed to add xbmc fuse" >> /home/xbian/update.log;
				mv /home/xbian/.xbmc/userdata/sources.xml.xbian /home/xbian/.xbmc/userdata/sources.xml
			fi
		else
			echo "Notice: already added xbmc fuse" >> /home/xbian/update.log;
		fi
	else
		echo -e "<sources>\n    <files>\n\t<source>\n\t\t<name>XBMC HUB Fusion</name>\n\t\t<path pathversion=\"1\">http://fusion.xbmchub.com/</path>\n\t</source>\n    </files>\n</sources>" >> /home/xbian/.xbmc/userdata/sources.xml
		chown xbian:xbian /home/xbian/.xbmc/userdata/sources.xml
		if [ $(cat /home/xbian/.xbmc/userdata/sources.xml | grep "http://fusion.xbmchub.com/" | wc -l) -eq 1 ];	then
			echo "Success: added xbmc fuse" >> /home/xbian/update.log;
		else
			echo "Error: failed to add xbmc fuse" >> /home/xbian/update.log;
			rm /home/xbian/.xbmc/userdata/sources.xml
		fi
	fi

	if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "guires" | wc -l) -eq 0 ];	then
		if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "lookandfeel" | wc -l) -eq 2 ]; then
			sed -i 's/<\/lookandfeel>/     <guires>720<\/guires>\n   <\/lookandfeel>/g' /home/xbian/.xbmc/userdata/advancedsettings.xml
		else
			sed -i 's/<\/advancedsettings>/   <lookandfeel>\n     <guires>720<\/guires>\n   <\/lookandfeel>\n<\/advancedsettings>/g' /home/xbian/.xbmc/userdata/advancedsettings.xml
		fi
		if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "guires" | wc -l) -eq 1 ]; then
			echo "Success: added gui resolution setting" >> /home/xbian/update.log;
		else
			echo "Error: failed to add gui resolution setting" >> /home/xbian/update.log;
		fi
	else
		echo "Notice: already added gui resolution setting" >> /home/xbian/update.log;
	fi

	if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "gputempcommand" | wc -l) -eq 0 ]; then
		if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "cputempcommand" | wc -l) -eq 1 ]; then
			sed -i 's/<\/cputempcommand>/<\/cputempcommand>\n   <gputempcommand>echo "$\(\/opt\/vc\/bin\/vcgencmd measure_temp | grep -o "[0-9]\\\{2\\\}") C"<\/gputempcommand>/g' /home/xbian/.xbmc/userdata/advancedsettings.xml
			sed -i '/<\/cputempcommand>/d' /home/xbian/.xbmc/userdata/advancedsettings.xml
			sed -i 's/<\/gputempcommand>/<\/gputempcommand>\n   <cputempcommand>echo "$\(\/opt\/vc\/bin\/vcgencmd measure_temp | grep -o "[0-9]\\\{2\\\}") C"<\/cputempcommand>/g' /home/xbian/.xbmc/userdata/advancedsettings.xml
		fi
		if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "gputempcommand" | wc -l) -eq 1 ]; then
			echo "Success: added gpu temperature monitor" >> /home/xbian/update.log;
		else
			echo "Error: failed to add gpu temperature monitor" >> /home/xbian/update.log;
		fi
	else
		echo "Notice: already added gpu temperature monitor" >> /home/xbian/update.log;
	fi

	if [ $(ls -Al /boot/*.xbian 2>/dev/null | wc -l) -gt 0 ]; then
		rm /boot/*.xbian
	fi

	if [ ! -L "/usr/bin/edidparser" ]; then
		ln -s /opt/vc/bin/edidparser /usr/bin/edidparser
	fi

	if [ ! -L "/usr/bin/tvservice" ]; then
		ln -s /opt/vc/bin/tvservice /usr/bin/tvservice
	fi

	if [ ! -L "/usr/bin/vcdbg" ]; then
		ln -s /opt/vc/bin/vcdbg /usr/bin/vcdbg
	fi

	if [ ! -L "/usr/bin/vcdbg" ]; then
		ln -s /opt/vc/bin/vcdbg /usr/bin/vcdbg
	fi

	if [ ! -L "/usr/bin/vcgencmd" ]; then
		ln -s /opt/vc/bin/vcgencmd /usr/bin/vcgencmd
	fi

	if [ ! -L "/usr/bin/vchiq_test" ]; then
		ln -s /opt/vc/bin/vchiq_test /usr/bin/vchiq_test
	fi

	ldconfig >/dev/null 2>/dev/null

	mv /home/xbian/Splash.png /usr/local/share/xbmc/media/Splash.png
	mv /home/xbian/SplashChristmass.png /usr/local/share/xbmc/media/SplashChristmass.png
	
	echo "6) Make kernel 3.6.11 the default"
	cp /boot/kernel3_6_11.img /boot/kernel.img

	echo 'man-db man-db/auto-update boolean false' | sudo debconf-set-selections
	
	echo "7) Starting XBMC";
	/etc/init.d/xbmc start;

	echo "!------------------------------------------------!"
	echo "!                                                !"
	echo "!  Please reboot for the changes to take effect  !"
	echo "!                                                !"
	echo "!------------------------------------------------!"

	echo "---UPDATE LOG---"
	cat "/home/xbian/update.log"

fi 
