#!/bin/bash

if [ $1 == "install" ]; then

	if [ $(dpkg-query -W -f='${Version}\n' "xbian-update") != "1.0-0.3" ]; then
		echo "!-------------------------------------------------!"
		echo "!                                                 !"
		echo "! Please install this update on XBian 1.0 Alpha 3 !"
		echo "!                                                 !"
		echo "!-------------------------------------------------!"
		exit 1;
	fi

fi

if [ $1 == "upgrade" ]; then

	if [ $(dpkg-query -W -f='${Version}\n' "xbian-update") != "1.0-0.4" -a $(dpkg-query -W -f='${Version}\n' "xbian-update") != "1.0-0.3" ]; then
		echo "!-------------------------------------------------!"
		echo "!                                                 !"
		echo "! Please install this update on XBian 1.0 Alpha 3 !"
		echo "!    or use it to reinstall XBian 1.0 Alpha 4     !"
		echo "!                                                 !"
		echo "!-------------------------------------------------!"
		exit 1;
	fi

fi

if [ $1 == "install" -o $1 == "upgrade" ]; then

	echo "1) Stopping XBMC";
	/etc/init.d/xbmc stop 1>/dev/null 2>/dev/null >/dev/null

	if [ ! -d "/boot" ]; then
		mkdir -p "/boot";
	fi

	if [ ! -d "/home/xbian/.xbmc/addons/script.linux.nm" ]; then
		mkdir -p "/home/xbian/.xbmc/addons/script.linux.nm";
	fi

	if [ ! -d "/home/xbian/.xbmc/addons/script.linux.nm/resources/language/English" ]; then
		mkdir -p "/home/xbian/.xbmc/addons/script.linux.nm/resources/language/English";
	fi

	if [ ! -d "/home/xbian/.xbmc/addons/script.linux.nm/resources/lib" ]; then
		mkdir -p "/home/xbian/.xbmc/addons/script.linux.nm/resources/lib";
	fi

	if [ ! -d "/home/xbian/.xbmc/addons/script.linux.nm/resources" ]; then
		mkdir -p "/home/xbian/.xbmc/addons/script.linux.nm/resources";
	fi

	if [ ! -d "/home/xbian/.xbmc/addons/script.linux.nm/resources/skins/default/720p" ]; then
		mkdir -p "/home/xbian/.xbmc/addons/script.linux.nm/resources/skins/default/720p";
	fi

	if [ ! -d "/home/xbian/.xbmc/addons/script.linux.nm/resources/skins/default/media" ]; then
		mkdir -p "/home/xbian/.xbmc/addons/script.linux.nm/resources/skins/default/media";
	fi

	if [ ! -d "/home/xbian/.xbmc/addons/script.linux.nm/resources/skins/default/media/colors" ]; then
		mkdir -p "/home/xbian/.xbmc/addons/script.linux.nm/resources/skins/default/media/colors";
	fi

	if [ ! -d "/opt/vc/bin" ]; then
		mkdir -p "/opt/vc/bin";
	fi

	if [ ! -d "/opt/vc/include/EGL" ]; then
		mkdir -p "/opt/vc/include/EGL";
	fi

	if [ ! -d "/opt/vc/include/GLES" ]; then
		mkdir -p "/opt/vc/include/GLES";
	fi

	if [ ! -d "/opt/vc/include/GLES2" ]; then
		mkdir -p "/opt/vc/include/GLES2";
	fi

	if [ ! -d "/opt/vc/include/IL" ]; then
		mkdir -p "/opt/vc/include/IL";
	fi

	if [ ! -d "/opt/vc/include/KHR" ]; then
		mkdir -p "/opt/vc/include/KHR";
	fi

	if [ ! -d "/opt/vc/include/VG" ]; then
		mkdir -p "/opt/vc/include/VG";
	fi

	if [ ! -d "/opt/vc/include/WF" ]; then
		mkdir -p "/opt/vc/include/WF";
	fi

	if [ ! -d "/opt/vc/include/interface/vchi/common" ]; then
		mkdir -p "/opt/vc/include/interface/vchi/common";
	fi

	if [ ! -d "/opt/vc/include/interface/vchi/connections" ]; then
		mkdir -p "/opt/vc/include/interface/vchi/connections";
	fi

	if [ ! -d "/opt/vc/include/interface/vchi/message_drivers" ]; then
		mkdir -p "/opt/vc/include/interface/vchi/message_drivers";
	fi

	if [ ! -d "/opt/vc/include/interface/vchi" ]; then
		mkdir -p "/opt/vc/include/interface/vchi";
	fi

	if [ ! -d "/opt/vc/include/interface/vchiq_arm" ]; then
		mkdir -p "/opt/vc/include/interface/vchiq_arm";
	fi

	if [ ! -d "/opt/vc/include/interface/vcos/generic" ]; then
		mkdir -p "/opt/vc/include/interface/vcos/generic";
	fi

	if [ ! -d "/opt/vc/include/interface/vcos/pthreads" ]; then
		mkdir -p "/opt/vc/include/interface/vcos/pthreads";
	fi

	if [ ! -d "/opt/vc/include/interface/vcos" ]; then
		mkdir -p "/opt/vc/include/interface/vcos";
	fi

	if [ ! -d "/opt/vc/include/interface/vctypes" ]; then
		mkdir -p "/opt/vc/include/interface/vctypes";
	fi

	if [ ! -d "/opt/vc/include/interface/vmcs_host/khronos/IL" ]; then
		mkdir -p "/opt/vc/include/interface/vmcs_host/khronos/IL";
	fi

	if [ ! -d "/opt/vc/include/interface/vmcs_host/vchi_local" ]; then
		mkdir -p "/opt/vc/include/interface/vmcs_host/vchi_local";
	fi

	if [ ! -d "/opt/vc/include/interface/vmcs_host/linux/vcfiled" ]; then
		mkdir -p "/opt/vc/include/interface/vmcs_host/linux/vcfiled";
	fi

	if [ ! -d "/opt/vc/include/interface/vmcs_host" ]; then
		mkdir -p "/opt/vc/include/interface/vmcs_host";
	fi

	if [ ! -d "/opt/vc/include" ]; then
		mkdir -p "/opt/vc/include";
	fi

	if [ ! -d "/opt/vc/include/vcinclude" ]; then
		mkdir -p "/opt/vc/include/vcinclude";
	fi

	if [ ! -d "/opt/vc/lib" ]; then
		mkdir -p "/opt/vc/lib";
	fi

	if [ ! -d "/opt/vc/sbin" ]; then
		mkdir -p "/opt/vc/sbin";
	fi

	if [ ! -d "/opt/vc/src/hello_pi" ]; then
		mkdir -p "/opt/vc/src/hello_pi";
	fi

	if [ ! -d "/opt/vc/src/hello_pi/hello_encode" ]; then
		mkdir -p "/opt/vc/src/hello_pi/hello_encode";
	fi

	if [ ! -d "/opt/vc/src/hello_pi/hello_jpeg" ]; then
		mkdir -p "/opt/vc/src/hello_pi/hello_jpeg";
	fi

	if [ ! -d "/opt/vc/src/hello_pi/hello_tiger" ]; then
		mkdir -p "/opt/vc/src/hello_pi/hello_tiger";
	fi

	if [ ! -d "/opt/vc/src/hello_pi/libs/vgfont" ]; then
		mkdir -p "/opt/vc/src/hello_pi/libs/vgfont";
	fi

	if [ ! -d "/usr/local/bin" ]; then
		mkdir -p "/usr/local/bin";
	fi

	if [ ! -d "/usr/local/include/libcec" ]; then
		mkdir -p "/usr/local/include/libcec";
	fi

	if [ ! -d "/usr/local/lib" ]; then
		mkdir -p "/usr/local/lib";
	fi
	
	if [ -f "/boot/.firmware_revision" ]; then
		rm /boot/.firmware_revision
	fi
	
	if [ -f "/boot/bootcode.bin" ]; then
		rm /boot/bootcode.bin
	fi
	
	if [ -f "/boot/fixup.dat" ]; then
		rm /boot/fixup.dat
	fi
	
	if [ -f "/boot/fixup_cd.dat" ]; then
		rm /boot/fixup_cd.dat
	fi
	
	if [ -f "/boot/start.elf" ]; then
		rm /boot/start.elf
	fi
	
	if [ -f "/boot/start_cd.elf" ]; then
		rm /boot/start_cd.elf
	fi
	echo "2) Installing new files" 
fi