#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Pretaktovanie"
_DESC="Nadstavenie pretaktovania"
_OCWARNING="Extrémne pretaktovanie môže znížiť životnosť tvojho Raspberry Pi.XBian testoval rôzne nadstavenia pretaktovania a boli vybrané najviac používané kombinácie. Turbo pretaktovanie môže spôsobiť znefunkčnenie systému. Pretaktovanie len na vlastné riziko!"
_OCNOTCHANGED="Tieto nadstavenia pretaktovania sú už momentálne použité"
_OCCHANGED="Pretaktovanie bolo úspešne zmenené"
_OCNAME="Meno"
_OCCUSTOM="~"
_OCEMPTYFIELDS="Neboli zadané všetky položky"