#!/bin/bash

if [ $1 == "configure" ]; then

	if [ -f /usr/local/lib/liblirc_client.so.0 ]; then
		rm /usr/local/lib/liblirc_client.so.0;
	fi
	
	if [ -f /usr/local/lib/liblirc_client.so ]; then
		rm /usr/local/lib/liblirc_client.so;
	fi	

	ln -s /usr/local/lib/liblirc_client.so.0.2.1 /usr/local/lib/liblirc_client.so.0
	ln -s /usr/local/lib/liblirc_client.so.0.2.1 /usr/local/lib/liblirc_client.so
	
fi