#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function checkNeedToResizeFn() {
	NEEDRESIZE=0;
	PART_START=$(fdisk -l | grep mmcblk0p2 | awk '{print $2}');
	CPART_END=$(fdisk -l | grep mmcblk0p2 | awk '{print $3}');
	SDEND=$(fdisk -l | sed -n '/mmcblk0/{n;p;}' | head -1 | awk '{print $8}');
	SDEND=$(($SDEND-1));
	SWAP=$(fdisk -l | grep 'mmcblk0p3' | awk '{print $5}');
		
	FDISKBLOCKSIZE=$(sfdisk -d /dev/mmcblk0 | grep Id=83 | awk '{printf "%d", $6}');
	FDISKBLOCKCOUNT=$(fdisk -l /dev/mmcblk0 | grep Units | sed -ne 's/\(.*= \)\([0-9]\{1,\}\)\( bytes\)/\2/p');
	TUNE2FS=$(tune2fs -l /dev/mmcblk0p2);
	TUNEBLOCKSIZE=$(echo -e "${TUNE2FS}" | grep "Block size" | awk '{printf "%d", $3}');
	TUNEBLOCKCOUNT=$(echo -e "${TUNE2FS}" | grep "Block count" | awk '{printf "%d", $3}');
	TUNETOTALBLOCKS=$(($(($TUNEBLOCKCOUNT*$TUNEBLOCKSIZE))/1024/1024));
	FDISKTOTALBLOCKS=$(($(($FDISKBLOCKSIZE*$FDISKBLOCKCOUNT))/1024/1024));

	# check if parition was actually resized, if not reboot
	if [ $TUNETOTALBLOCKS -lt $FDISKTOTALBLOCKS ]; then		
		NEEDRESIZE=1;
	elif [ $SDEND -gt $CPART_END ]; then
		NEEDRESIZE=1;
	fi
	return $NEEDRESIZE;
}

function resizeSDFn() {
	ERROR=0;
	
	checkNeedToResizeFn;
	if [ $? == 1 ]; then
		PART_START=$(fdisk -l | grep mmcblk0p2 | awk '{print $2}');
		CPART_START=$PART_START;
		CPART_END=$(fdisk -l | grep mmcblk0p2 | awk '{print $3}');
		SDEND=$(fdisk -l | sed -n '/mmcblk0/{n;p;}' | head -1 | awk '{print $8}');
		SDEND=$(($SDEND-1));
		SWAP=$(fdisk -l | grep 'mmcblk0p3' | awk '{print $5}');
		
		PART_END=$SDEND;
		
		if [ ! -z $SWAP ] && [ $SWAP -eq 82 ]; then
			swapoff -a
			ERROR=$?;
			if [ $ERROR -eq 0 ]; then
fdisk /dev/mmcblk0 2>/dev/null >/dev/null <<EOF
d
2
d
3
n
p
2
$PART_START
$PART_END
w
EOF
				ERROR=$?;
			else
				return 1;
			fi
			sed -i '/\/dev.*swap/d' /etc/fstab
		else
			if [ $ERROR -eq 0 ]; then
fdisk /dev/mmcblk0 2>/dev/null >/dev/null <<EOF
d
2
n
p
2
$PART_START
$PART_END
w
EOF
				ERROR=$?;
			else
				return 1;
			fi
		fi

		if [ $ERROR -eq 0 ]; then
		askForRebootFn;

cat <<\EOF > /etc/init.d/resize2fs_once
#!/bin/sh
### BEGIN INIT INFO
# Provides: resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5 S
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once"
    resize2fs /dev/mmcblk0p2 >/dev/null
    rm /etc/init.d/resize2fs_once >/dev/null
    update-rc.d resize2fs_once remove >/dev/null
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
EOF
			ERROR=$?;
		fi
		if [ $ERROR -eq 0 ]; then
			chmod +x /etc/init.d/resize2fs_once >/dev/null;
			if [ $? -eq 0 ]; then
				ERROR=0;
			else
				ERROR=1;
			fi
		else
			ERROR=1;
		fi
		if [ $ERROR -eq 0 ]; then
			update-rc.d resize2fs_once defaults >/dev/null 2>/dev/null;
			if [ $? -eq 0 ]; then
				ERROR=0;
			else
				ERROR=1;
			fi
		else
			ERROR=1;
		fi
	return $ERROR;
	else
		return 1;
	fi
}