#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|             Main Menu			  |
#|------------------------------------|
_TITLE="Konfiguration"
_REBOOTREQUIRED="Ein Neustart ist notwendig. Soll dieser jetzt durchgeführt werden?"

#|------------------------------------|
#|             Menu Items			  |
#|------------------------------------|
_ITEMSETTINGSNAME="Einstellungen"
_ITEMSETTINGSDESC="Konfiguration der Systemeinstellungen"
_ITEMSYSTEMNAME="System"
_ITEMSYSTEMDESC="u.a. Resize SD, Übertaktung, Hostname"
_ITEMACCOUNTSNAME="Konten"
_ITEMACCOUNTSDESC="Ändern von Kennwörtern, SSH root login"
_ITEMLICENSESNAME="Lizenzen"
_ITEMLICENSESDESC="Hinzufügen oder Entfernen von Lizenzen"
_ITEMCONNECTIVITYNAME="Ein- und Ausgabe"
_ITEMCONNECTIVITYDESC="z.B. Video Ausgabe"

#|------------------------------------|
#|              Dialogs	  	   		  |
#|------------------------------------|
_YES="Ja"
_NO="Nein"
_ON="An"
_OFF="Aus"
_INSERT="Einfügen"
_REMOVE="Entfernen"
_UPDATE="Aktualisieren"
_CANCEL="Abbruch"
_SELECT="Auswählen"
_RETURN="Zurück"
_ERROR="Ein Fehler ist aufgetreten"
_CLOSE="Schließen"
_CHANGE="Ändern"
_EXIT="Beenden"
_ENABLE="Aktivieren"
_DISABLE="Deaktivieren"
_PASSWORD="Kennwort:"
_CONFIRM="Bestätigen:"
_RETRY="Wiederholen"
_SPACEOPTIONSELECT="Drücke [Leertaste], um eine anderen Option auszuwählen"
_SPACECHECKSELECT="Drücke [Leertaste], um die Option zu de-/aktivieren"
_LOADING="Module werden geladen, bitte warten..."
_REQUIREDPACKAGES="Das Programm benötigt die folgenden Pakete:"