#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|             Main Menu			  |
#|------------------------------------|
_TITLE="Konfiguration"
_REBOOTREQUIRED="Genstart er påkrævet. Ønsker du at genstarte nu?"

#|------------------------------------|
#|             Menu Items			  |
#|------------------------------------|
_ITEMSETTINGSNAME="Indstillinger"
_ITEMSETTINGSDESC="Rediger systemindstillinger"
_ITEMSYSTEMNAME="System"
_ITEMSYSTEMDESC="f.eks. Tilpas SD, Overclocking, Værtsnavn"
_ITEMACCOUNTSNAME="Konti"
_ITEMACCOUNTSDESC="e.g. Skift adgangskode, SSH root login"
_ITEMLICENSESNAME="Licenser"
_ITEMLICENSESDESC="Tilføj/Fjern hardwarelicenser"
_ITEMCONNECTIVITYNAME="Opkobling"
_ITEMCONNECTIVITYDESC="f.eks. Video-output"

#|------------------------------------|
#|              Dialogs	  	   		  |
#|------------------------------------|
_YES="Ja"
_NO="Nej"
_ON="Til"
_OFF="Fra"
_INSERT="Indsæt"
_REMOVE="Fjern"
_UPDATE="Opdater"
_CANCEL="Afbryd"
_SELECT="Vælg"
_RETURN="Tilbage"
_ERROR="Der opstod en uventet fejl"
_CLOSE="Luk"
_CHANGE="Skift"
_EXIT="Afslut"
_ENABLE="Aktiver"
_DISABLE="Deaktiver"
_PASSWORD="Adgangskode:"
_CONFIRM="Bekræft:"
_RETRY="Forsøg igen"
_SPACEOPTIONSELECT="Tryk [space] for at ændre valgmulighed"
_SPACECHECKSELECT="Tryk [space] for at de-/aktivere valgmulighed"
_LOADING="Indlæser modul. Vent venligst..."
_REQUIREDPACKAGES="Dette program kræver følgende pakker:"