#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|             Main Menu			  |
#|------------------------------------|
_TITLE="Config"
_REBOOTREQUIRED="A reboot is required. Do you want to reboot now?"

#|------------------------------------|
#|             Menu Items			  |
#|------------------------------------|
_ITEMSETTINGSNAME="Settings"
_ITEMSETTINGSDESC="Change various system settings"
_ITEMSYSTEMNAME="System"
_ITEMSYSTEMDESC="e.g. Resize SD, Overclocking, Hostname"
_ITEMACCOUNTSNAME="Accounts"
_ITEMACCOUNTSDESC="e.g. Change passwords, SSH root login"
_ITEMLICENSESNAME="Licenses"
_ITEMLICENSESDESC="Add/Remove hardware licenses"
_ITEMCONNECTIVITYNAME="Connectivity"
_ITEMCONNECTIVITYDESC="e.g. Video output"

#|------------------------------------|
#|              Dialogs	  	   		  |
#|------------------------------------|
_YES="Yes"
_NO="No"
_ON="On"
_OFF="Off"
_INSERT="Insert"
_REMOVE="Remove"
_UPDATE="Update"
_CANCEL="Cancel"
_SELECT="Select"
_RETURN="Return"
_ERROR="An unexpected error occurred"
_CLOSE="Close"
_CHANGE="Change"
_EXIT="Exit"
_ENABLE="Enable"
_DISABLE="Disable"
_PASSWORD="Password:"
_CONFIRM="Confirm:"
_RETRY="Retry"
_SPACEOPTIONSELECT="Press [space] to select a different option"
_SPACECHECKSELECT="Press [space] to enable or disable an option"
_LOADING="Loading module. Please wait..."
_REQUIREDPACKAGES="This program requires the following packages:"