#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|             Main Menu			  |
#|------------------------------------|
_TITLE="Config"
_REBOOTREQUIRED="Un redémarrage est nécessaire, voulez vous redémarrer maintenant?"

#|------------------------------------|
#|             Menu Items			  |
#|------------------------------------|
_ITEMSETTINGSNAME="Paramètres"
_ITEMSETTINGSDESC="Modifier les paramètres systèmes"
_ITEMSYSTEMNAME="Système"
_ITEMSYSTEMDESC="ex. Redimensionner carte SD, overclocking"
_ITEMACCOUNTSNAME="Comptes"
_ITEMACCOUNTSDESC="ex. Modifier les mots de passe, SSH root"
_ITEMLICENSESNAME="Licenses"
_ITEMLICENSESDESC="Ajouter/Supprimer les licenses matérielles"
_ITEMCONNECTIVITYNAME="Connectivitée"
_ITEMCONNECTIVITYDESC="e.g. Sortie vidéo"

#|------------------------------------|
#|              Dialogs	  	   		  |
#|------------------------------------|
_YES="Oui"
_NO="Non"
_ON="On"
_OFF="Off"
_INSERT="Insérer"
_REMOVE="Supprimer"
_UPDATE="Mettre à jour"
_CANCEL="Annuler"
_SELECT="Selectionner"
_RETURN="Retour"
_ERROR="Une erreur inattendue est survenue"
_CLOSE="Fermer"
_CHANGE="Modifier"
_EXIT="Quitter"
_ENABLE="Activer"
_DISABLE="Désactiver"
_PASSWORD="Mot de passe:"
_CONFIRM="Confirmation:"
_RETRY="Réessayer"
_SPACEOPTIONSELECT="Appuyer [espace] pour sélectionner les différentes options"
_SPACECHECKSELECT="Appuyer [espace] pour activer ou désactiver une option"
_LOADING="Chargement des modules, veuillez patienter..."
_REQUIREDPACKAGES="Ce programme requiert les paquets suivants:"
