#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|             Main Menu			  |
#|------------------------------------|
_TITLE="Config"
_REBOOTREQUIRED="Een herstart is vereist. Wilt u nu herstarten?"

#|------------------------------------|
#|             Menu Items			  |
#|------------------------------------|
_ITEMSETTINGSNAME="Instellingen"
_ITEMSETTINGSDESC="Verander systeem instellingen"
_ITEMSYSTEMNAME="Systeem"
_ITEMSYSTEMDESC="e.g. Vul SD, Overclocking, Systeemnaam"
_ITEMACCOUNTSNAME="Accounts"
_ITEMACCOUNTSDESC="e.g. Verander wachtwoorden, SSH root"
_ITEMLICENSESNAME="Licenties"
_ITEMLICENSESDESC="Voeg toe/verwijder hardware licenties"
_ITEMCONNECTIVITYNAME="Connectiviteit"
_ITEMCONNECTIVITYDESC="e.g. Video uitvoer"

#|------------------------------------|
#|              Dialogs	  	   		  |
#|------------------------------------|
_YES="Ja"
_NO="Nee"
_ON="Aan"
_OFF="Uit"
_INSERT="Invoegen"
_REMOVE="Verwijderen"
_UPDATE="Bijwerken"
_CANCEL="Annuleren"
_SELECT="Selecteren"
_RETURN="Terugkeren"
_ERROR="Er is een onverwachte fout opgetreden"
_CLOSE="Sluiten"
_CHANGE="Veranderen"
_EXIT="Afsluiten"
_ENABLE="Aanzetten"
_DISABLE="Uitzetten"
_PASSWORD="Wachtwoord:"
_CONFIRM="Herhaal:"
_RETRY="Opnieuw"
_SPACEOPTIONSELECT="Druk op [spatie] om een andere optie te selecteren"
_SPACECHECKSELECT="Druk op [spatie] om een optie aan of uit te zetten"
_LOADING="De module is aan het laden. Een ogenblik geduld..."
_REQUIREDPACKAGES="Dit programma vereist de volgende paketten:"