#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|             Main Menu			  |
#|------------------------------------|
_TITLE="Параметры"
_REBOOTREQUIRED="Требуется перезагрузка. Перезагрузить сейчас?"

#|------------------------------------|
#|             Menu Items			  |
#|------------------------------------|
_ITEMSETTINGSNAME="Настройки"
_ITEMSETTINGSDESC="Изменение различных настроек системы"
_ITEMSYSTEMNAME="Система"
_ITEMSYSTEMDESC="напр. заполнение SD, разгон, Hostname"
_ITEMACCOUNTSNAME="Аккаунты"
_ITEMACCOUNTSDESC="напр. смена паролей, вход root по SSH"
_ITEMLICENSESNAME="Лицензии"
_ITEMLICENSESDESC="Управление лицензиями"
_ITEMCONNECTIVITYNAME="Connectivity"
_ITEMCONNECTIVITYDESC="напр. видеовыход"

#|------------------------------------|
#|              Dialogs	  	   		  |
#|------------------------------------|
_YES="Да"
_NO="Нет"
_ON="Вкл"
_OFF="Выкл"
_INSERT="Insert"
_REMOVE="Remove"
_UPDATE="Update"
_CANCEL="Отмена"
_SELECT="Выбор"
_RETURN="Назад"
_ERROR="Непредвиденная ошибка"
_CLOSE="Закрыть"
_CHANGE="Change"
_EXIT="Выход"
_ENABLE="Enable"
_DISABLE="Disable"
_PASSWORD="Пароль:"
_CONFIRM="Подтвержд.:"
_RETRY="Retry"
_SPACEOPTIONSELECT="Нажмите [space] чтобы выбрать другой пункт"
_SPACECHECKSELECT="Нажмите [space] выбрать или снять выбор"
_LOADING="Загрузка модулей, ждите..."
_REQUIREDPACKAGES="Этой программе необходимы следующие пакеты:"