#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|             Main Menu			  |
#|------------------------------------|
_TITLE="Config"
_REBOOTREQUIRED="Je potrebný reštart. Chceš reštartovať teraz?"

#|------------------------------------|
#|             Menu Items			  |
#|------------------------------------|
_ITEMSETTINGSNAME="Nadstavenia"
_ITEMSETTINGSDESC="Zmena rôznych systémových nadstavení"
_ITEMSYSTEMNAME="Systém"
_ITEMSYSTEMDESC="napr. Pretaktovanie, Hostname"
_ITEMACCOUNTSNAME="Účty"
_ITEMACCOUNTSDESC="napr. zmena hesla, SSH root prihlásenie"
_ITEMLICENSESNAME="Licencie"
_ITEMLICENSESDESC="Pridaj/Odsráň licencie"
_ITEMCONNECTIVITYNAME="Pripojenia"
_ITEMCONNECTIVITYDESC="napr. Video výstup"

#|------------------------------------|
#|              Dialogs	  	   		  |
#|------------------------------------|
_YES="Áno"
_NO="Nie"
_ON="Zapnúť"
_OFF="Vypnúť"
_INSERT="Vložiť"
_REMOVE="Odstrániť"
_UPDATE="Aktualizovať"
_CANCEL="Zrušiť"
_SELECT="Vybrať"
_RETURN="Návrat"
_ERROR="Veskytla sa neočakávaná chyba"
_CLOSE="Zatvoriť"
_CHANGE="Zmeniť"
_EXIT="Exit"
_ENABLE="Aktivovať"
_DISABLE="Deaktivovať"
_PASSWORD="Heslo:"
_CONFIRM="Potvrdiť:"
_RETRY="Zopakuj"
_SPACEOPTIONSELECT="Stlač [medzerník] pre výber inej možnosti"
_SPACECHECKSELECT="Stlač [medzerník] pre aktiváciu-deaktiváciu možnosti"
_LOADING="Nahrávam modul. Prosím čakať..."
_REQUIREDPACKAGES="Tento program potrebuje nasledovné balíky:"