#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Tilpas SD"
_DESC="Forøg root paritionen og udfyld SD-kortet"
_SDCONFIRM="Vil du udfylde SD-kortet?"
_SDRESIZENOTNEEDED="SD-kortet er allerede udfyldt. Afbryder."
_SDREBOOT="Root-partitionen er blevet forøget. Filsystemet forøges efter næste genstart."
_SDERROR="En fejl opstod. Det er muligt at systemet ikke kan genstarte. Foretag en sikkerhedskopiering af dine filer inden genstart."