#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Resize SD"
_DESC="Expand root parition to fill SD card"
_SDCONFIRM="Are you sure you want to resize you SD card?"
_SDRESIZENOTNEEDED="This SD card is already resized. Aborting."
_SDREBOOT="Root partition has been resized. The filesystem will be enlarged upon the next reboot."
_SDERROR="An error occurred. It is possible that the system will become unbootable. Please make a backup of your files before rebooting."