#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|             Main Menu			  |
#|------------------------------------|
_TITLE="Configuración"
_REBOOTREQUIRED="Se necesita reinicar, ¿quieres reinicar ahora?"

#|------------------------------------|
#|             Menu Items			  |
#|------------------------------------|
_ITEMSETTINGSNAME="Ajustes"
_ITEMSETTINGSDESC="Cambiar ajustes del sistema"
_ITEMSYSTEMNAME="Sistema"
_ITEMSYSTEMDESC="Ej. Cambiar tamaño SD, Overclocking"
_ITEMACCOUNTSNAME="Cuentas"
_ITEMACCOUNTSDESC="Ej. Cambiar contraseña, conexión SSH"
_ITEMLICENSESNAME="Licencias"
_ITEMLICENSESDESC="Añadir/Quitar licencias de hardware"
_ITEMCONNECTIVITYNAME="Conectividad"
_ITEMCONNECTIVITYDESC="Ej. salidas de video"

#|------------------------------------|
#|              Dialogs	  	   		  |
#|------------------------------------|
_YES="Si"
_NO="No"
_ON="Encender"
_OFF="Apagar"
_INSERT="Insertar"
_REMOVE="Eliminar"
_UPDATE="Actualizar"
_CANCEL="Cancelar"
_SELECT="Seleccionar"
_RETURN="Volver"
_ERROR="Un error inesperado ha ocurrido"
_CLOSE="Cerrar"
_CHANGE="Cambiar"
_EXIT="Salir"
_ENABLE="Activar"
_DISABLE="Desactivar"
_PASSWORD="Contraseña:"
_CONFIRM="Confirmar:"
_RETRY="Reintentar"
_SPACEOPTIONSELECT="Presiona [espacio] para seleccionar otra opción"
_SPACECHECKSELECT="Presiona [espacio] para activar o desactivar una opción"
_LOADING="Cargándo módulos. Por favor espere..."