#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function showUpdateAptDBDlg() {
	wrapTxtFn "$_UPDATINGAPTDB" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showUpdateAptDBFailedDlg() {
	wrapTxtFn "$_UPDATEAPTDBFAILED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showDownloadPackageListDlg() {
	wrapTxtFn "$_DOWNLOADINGPACKAGELIST" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showUpdateDowngradeDlg() {
	wrapTxtFn "$_UPDATEDOWNGRADE" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showFailedToRetrieveAptMirrosDlg() {
	wrapTxtFn "$_FAILEDTORETRIEVEAPTMIRRORS" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showRetrievingUpdateListDlg() {
	wrapTxtFn "$_UPDATEDOWNLOADLIST" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showUpdateAlreadyInstalledDlg() {
	wrapTxtFn "$_UPDATEALREADYINSTALLED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showUpdateVersionNotExistDlg() {
	wrapTxtFn "$_UPDATEVERSIONNOTEXISTS" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showUpdateNotExistsDlg() {
	wrapTxtFn "$_UPDATENOTEXISTS" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showAskForLogDlg() {
	wrapTxtFn "$_UPDATEASKFORLOG" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showConfirmDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showUpdateAdvErrorDlg() {
	wrapTxtFn "$_UPDATEADVERROR" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showInstallUpdatesDlg() {
	wrapTxtFn "$_UPDATEINSTALLS" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showUpToDateDlg() {
	wrapTxtFn "$_UPDATETODATE" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showSystemUpdateConfirmDlg() {
	wrapTxtFn "$_ASKFORSYSTEMUPDATE" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showConfirmDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showUpgradeSystemDlg() {
	wrapTxtFn "$_UPGRADESYSTEM" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showSystemUpdateRebootDlg() {
	wrapTxtFn "$_UPDATESYSTEMREBOOT" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showUpdateLogDlg() {
	sed -i 's/\r/\n/g' /tmp/aptstatus
	showTextDlg "/tmp/aptstatus" 15 $(($DEFAULTWIDTH+11));
}

function showSystemUpdateLogDlg() {
	showTextDlg "/home/xbian/update" 15 $(($DEFAULTWIDTH+11));
}

function showAvailableUpdatesDlg() {
	IFS=$'\n';
	ARRAY=($1);
	MENU=();
	I=0;
	for VALUE in ${ARRAY[@]}; do
		IFS=";";
		VALUE=($VALUE);
		I=$(($I+1));
		NAME=$(echo ${VALUE[0]} | rev | cut -f1 -d"-" | rev);
		if ! [[ "${VALUE[0]}" =~ "xbian-update" ]]; then
			if [ $(echo "${VALUE[1]} == ${VALUE[2]}" | bc) -eq 0 ]; then
				MENU+=($I,"\Zb"$NAME",\Zb"${VALUE[1]}" ("${VALUE[2]}"),Off");
			fi
		fi
	done;
	IFS=$ORIGINALIFS;
	TBLCOLUMNCENTER=0;
	createTableFn "check" \
	" #,\Zb"$_UPDATES",\Zb"$_UPDATEVERSION \
	"${MENU[@]}";
	TBLCOLUMNCENTER=1;
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+5));
	showChecklistDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} $((${#MENU[@]}+9)) 
}