#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# Shows the dialog in which users can enter the new password
function showLoadingServiceDlg() {
	wrapTxtFn "$_LOADINGSERVICES" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showServiceConfirmationDlg() {
	wrapTxtFn "$_SERVICEDELETECONFIRM" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showConfirmDlg "$ALIGNEDTXT" $HEIGHT;
}

function showServiceDeletedDlg() {
	wrapTxtFn "$_SERVICEDELETED" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}

function showServiceInsertedDlg() {
	wrapTxtFn "$_SERVICEINSERTED" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}

function showServiceUpdatedDlg() {
	wrapTxtFn "$_SERVICEUPDATED" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}

function showRestartServiceDlg() {
	wrapTxtFn "$_RESTARTINGSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showServiceNotExistsDlg() {
	wrapTxtFn "$_UNEXISTINGSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showFailedToRestartDlg() {
	wrapTxtFn "$_FAILEDTORESTARTSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showStartServiceDlg() {
	wrapTxtFn "$_STARTINGSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showFailedToStartDlg() {
	wrapTxtFn "$_FAILEDTOSTARTSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showStopServiceDlg() {
	wrapTxtFn "$_STOPPINGSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showFailedToStopDlg() {
	wrapTxtFn "$_FAILEDTOSTOPSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showDisableAutoStartServiceDlg() {
	wrapTxtFn "$_DISABLEAUTOSTARTSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showFailedToDisableAutoStartDlg() {
	wrapTxtFn "$_FAILEDTODISABLEAUTOSTARTSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showEnableAutoStartServiceDlg() {
	wrapTxtFn "$_ENABLEAUTOSTARTSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showFailedToDisableAutoStartDlg() {
	wrapTxtFn "$_FAILEDTOENABLEAUTOSTARTSERVICE" $(($DEFAULTWIDTH-4))
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4))
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

function showServicesListDlg() {
	MENU=()
	I=1
	AT=$_OFF;
	RUNNING=$_NO
	X=3;
	for SERVICE in ${INSTSERV[@]}; do
		if [ $(getServiceAutoStartStatusFn $SERVICE; echo $?) -eq 0 ]; then
			AT="\Z1"$_OFF;
		else
			AT="\Z2"$_ON;
		fi
		if [ $(getServiceRunningStatusFn $SERVICE; echo $?) -eq 0 ]; then
			RUNNING="\Z1"$_NO;
		else
			RUNNING="\Z2"$_YES;
		fi
		if [ ${#SERVICE} -gt $X ]; then
			X=${#SERVICE};
		fi
		MENU+=($I",\Zn"$SERVICE","$AT","$RUNNING);
		I=$(($I+1))
	done
	MENU+=($I",\Zn...,\Zn...,\Zn...");
	createTableFn "menu"\
	"#,\Zb"$_SERVICE",\Zb"$_SERVICEAUTOSTART",\Zb"$_SERVICERUNNING\
	"${MENU[@]}";
	
	
	HEIGHT=$((${#MENU[@]}+8));
	if [ $HEIGHT -gt 15 ]; then
		HEIGHT=15;
	fi
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+11));
	showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} $HEIGHT
}

function showServiceManageDlg() {
	MENU=()

	IFS=$'\n';
	SERVCONF=($(echo -e "$SERVICES"));
	SERV=$(echo ${SERVCONF[$1]} | cut -f 1 -d:);
	IFS=$ORIGINALIFS;	

	TBLCOLUMNCENTER=0;
	if [ $(getServiceAutoStartStatusFn $SERV; echo $?) -eq 0 ]; then
		MENU+=("1,\Z1"$_SERVICEAUTOSTART);
	else
		MENU+=("1,\Z2"$_SERVICEAUTOSTART);
	fi
	MENU+=("2,\Zn"$_SERVICESTARTRESTART);
	MENU+=("3,\Zn"$_SERVICESTOP);
	MENU+=("4,\Zn"$_SERVICEEDIT);
	MENU+=("5,\Zn"$_SERVICEDELETE);
	createTableFn "menu"\
	"#,\Zb"$_SERVICEACTION\
	"${MENU[@]}";
	
	TBLCOLUMNCENTER=1;
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+11));
	showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} 11
}

function showServiceEditDlg() {
	IFS=" ";
	DATA=($1)
	IFS=$ORIGINALIFS;

	VALUES=$(dialog \
			--ok-label "$_CHANGE" \
			--cancel-label "$_RETURN" \
			--backtitle "$BACKTITLE" \
			--title "$TITLE" \
			--mixedform "" \
			8 $DEFAULTWIDTH 2 \
			"$_SERVICENAME:" 1 3 "${DATA[0]}" 1 16 20 19 0\
			"$_SERVICEDAEMONS:" 2 3 "${DATA[1]}" 2 16 20 19 0\
			3>&1 1>&2 2>&3);
}

function showServiceInsertDlg() {
	IFS=" ";
	DATA=($1)
	IFS=$ORIGINALIFS;

	VALUES=$(dialog \
			--ok-label "$_INSERT" \
			--cancel-label "$_RETURN" \
			--backtitle "$BACKTITLE" \
			--title "$TITLE" \
			--mixedform "" \
			8 $DEFAULTWIDTH 2 \
			"$_SERVICENAME:" 1 3 "${DATA[0]}" 1 16 20 19 0\
			"$_SERVICEDAEMONS:" 2 3 "${DATA[1]}" 2 16 20 19 0\
			3>&1 1>&2 2>&3);
} 