#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# Shows a radio with available kernel versions
# Returns
#  $? [Integer]
#  - 1: Change
#  - 0: Cancel
function showKernelVersionsDlg() {
	TBLCOLUMNCENTER=0;
	createTableFn "radio" \
	"#,\Zb$_KERNELVERSION"\
	"${KERNELMENU[@]}"
	TBLCOLUMNCENTER=1;
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+8))
	showRadioDlg "$CENTEREDTXT" "$ROWS" ${#KERNELMENU[@]} $((${#KERNELMENU[@]}+9))
}

# Show the kernel has successfully switched message
function showKernelSwitchedSuccesfullDlg() {
	wrapTxtFn "$_KERNELSWITCHSUCCESS"  $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT"
}

# Show the kernel version is already running message
function showKernelAlreadyRunningDlg() {
	wrapTxtFn "$_KERNELALREADYRUNNING" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT"
}

# Show the only one kernel installed message
function showKernelSingleInstalledDlg() {
	wrapTxtFn "$_SINGLEKERNELINSTALLED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT"
}