#!/bin/bash
#
#Copyright 2012 Hexagon & CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Netzwerk"
_DESC="Konfiguriere die Netzwerkschnittstellen"
_LOADINGINTERFACES="Netzwerkschnittstellen werden geladen..."
_NOINTERFACES="Keine Netzwerkschnittstellen verfügbar oder verbunden"
_SELECTINTERFACE="Bitte wähle eine Schnittstelle aus"
_IPDHCP="DHCP"
_IPSTATIC="Statische IP"
_SELECTHOW="Bitte wähle aus";
_OBTAINIP="wie die IP Adresse zugewiesen werden soll"
_SSID="SSID"
_KEY="Schlüssel (Key)"
_ENTERCREDENTIALS="Bitte trage die Zugangsdaten für die ausgewählte Schnittstelle ein"
_INVALIDCREDENTIALS="Ungültige Zugangsdaten eingetragen"
_WLANWEP="WEP"
_WLANWPA="WPA"
_WLANOPEN="Offen"
_WLANSIGNAL="Signal"
_CREDENTIALSUPDATED="WLAN Zugangsdaten erfolgreich gespeichert"
_ENTERSTATICCONFIG="Bitte gib eine statische IP-Adresse an"
_NETWORKINTERFACES="Schnittstellen"
_NETWORKADDRESS="IP-Adresse"
_NETWORKMASK="Netmask"
_NETWORKGATEWAY="Gateway"
_NAMESERVER="Nameserver"
_INVALIDSTATICCONFIG="Ungültige statische IP-Adresse, bitte versuche es erneut"
_STATICCONFIGUPDATED="Statische IP-Adresse wurde aktualisiert"
_DHCPCONFIGUPDATED="DHCP ist nun aktiv"
_NETWORKTYPE="Typ"
_NETWORKPROTECTION="Sicherheit"
_WLANSCAN="Scannen"
_NETWORKNAME="Name"
_NETWORKSCANAVAILABLE="Scannen"
_NETWORKCUSTOM="benutzerdefiniert"
_NETWORKWLAN="WLAN"
_SCANNINGFORWLAN="Suche verfügbare Netzwerke..."
_RESTARTINGADAPTER="Neustart"
_TRYINGCONNECTINGTO="Verbindungsaufbau wird geprüft, bitte warten..."
_FAILEDTOCONNECTTO="Verbindungsaufbau fehlgeschlagen"
_SUCCESSFULLYCONNECTEDTO="Verbindungsaufbau erfolgreich"