#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="XBMC"
_DESC="Change XBMC settings"
_XBMCWEBSERVERSUCCESSENABLED="XBMC webserver successfully enabled"
_XBMCWEBSERVERSUCCESSDISABLED="XBMC webserver successfully disabled"
_XBMCWEBSERVERFAILEDENABLE="Failed to enable XBMC webserver"
_XBMCWEBSERVERFAILEDDISABLE="Failed to disable XBMC webserver"
_XBMCGUIRESSUCCESS="XBMC GUI resolution successfully changed"
_XBMCGUIRESFAILED="Failed to change XBMC GUI resolution"
_XBMCGUIRES="GUI Resolution"
_XBMCWEBSERVER="Webserver"
_XBMCACTIONS="Actions"
_XBMCWEBSERVERENABLEDISABLE="Do you want to enable or disable the XBMC webserver?"