#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="XBMC"
_DESC="Modifier les paramètres XBMC"
_XBMCWEBSERVERSUCCESSDISABLED="Serveur web XBMC désactivé"
_XBMCWEBSERVERSUCCESSENABLED="Serveur web de XBMC activé correctement"
_XBMCWEBSERVERFAILEDENABLE="Echec lors de l'activation du serveur Web de XBMC"
_XBMCWEBSERVERFAILEDDISABLE="Une erreur s'est produite lors de la désactivation du serveur web XBMC" 
_XBMCGUIRESSUCCESS="Résolution de l'interface de XBMC correctement modifiée"
_XBMCGUIRESFAILED="Echec lors de la modification de la résolution de l'interface de XBMC"
_XBMCGUIRES="Résolution de l'interface"
_XBMCWEBSERVER="Server web"
_XBMCACTIONS="Actions"
_XBMCWEBSERVERENABLEDISABLE="Voulez vous activer ou désactiver l'interface web de XBMC?"