#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Aktualisierungen"
_DESC="Neue Systemaktualisierungen suchen"
_UPDATINGAPTDB="Lokale Paketdatenbank wird aktualisiert..."
_UPDATEDOWNLOADLIST="Liste der upgradefähigen Pakete wird geladen..."
_UPDATEAPTDBFAILED="Bei der Aktualisierung der Paketdatenbank trat ein Fehler auf"
_DOWNLOADINGPACKAGELIST="Remote Paketdatenbank wird aktualisiert..."
_FAILEDTORETRIEVEAPTMIRRORS="Laden der Download Mirrors fehlgeschlagen, daher wird eine (womöglich veraltete) lokale Liste genutzt"
_CONFIRMUPDAGESINSTALL="Sollen die Pakete wirklich aktualisiert werden?"
_UPDATEALREADYINSTALLED="Die aktuellste Version der Pakete ist bereits installiert"
_UPDATEVERSIONNOTEXISTS="Die ausgewählten Versionen konnten nicht gefunden werden"
_UPDATENOTEXISTS="Die ausgewählten Pakete konnten nicht gefunden werden"
_UPDATEINSTALLSUCCESS="Die Pakete wurden erfolgreich installiert"
_UPDATEASKFORLOG="Soll das Installationslog angezeigt werden?"
_UPDATEADVERROR="Bei der Bearbeitung trat ein Fehler auf"
_UPDATEINSTALLS="Pakete werden aktualisiert, bitte warten..."
_UPDATES="Aktualisierungen"
_UPDATEVERSION="Version"
_UPDATETODATE="Die vorhandene Installation umfasst bereits die aktuellsten Xbian Pakete"
_ASKFORSYSTEMUPDATE="Eine neue XBian Version ist verfügbar. Soll diese nun installiert werden? Das System wird anschließend automatisch neustarten"
_UPGRADESYSTEM="XBian wird aktualisiert. Dies kann abhängig von der Internetverbindung einige Minuten dauern. Bitte führe in dieser Zeit keinen Neustart aus und entfernen nicht das Stromkabel."
_UPDATESYSTEMREBOOT="XBian wird automatisch neustarten, wenn du dieses Fenster schließt"
_UPDATEDOWNGRADE="Es sind bereits aktuellere Versionen installiert"