#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Opdateringer"
_DESC="Søg efter systemopdateringer"
_UPDATINGAPTDB="Opdater lokal pakke-database..."
_UPDATEDOWNLOADLIST="Henter liste over pakker til opgradering..."
_UPDATEAPTDBFAILED="En fejl opstod under opdatering af pakke-databasen"
_DOWNLOADINGPACKAGELIST="Henter fjernpakke-database..."
_FAILEDTORETRIEVEAPTMIRRORS="Hentning af spejlede downloadsider mislykkedes, derfor anvendes en lokal (muligvis uddateret) liste"
_CONFIRMUPDAGESINSTALL="Er du sikker på du vil opdatere disse pakker?"
_UPDATEALREADYINSTALLED="De seneste versioner af disse pakker er allerede installeret"
_UPDATEVERSIONNOTEXISTS="De pakkeversioner du forsøger at installere kunne ikke findes"
_UPDATENOTEXISTS="Pakkerne du førsøger at installere kunne ikke findes"
_UPDATEINSTALLSUCCESS="Opdatering af pakkerne lykkedes"
_UPDATEASKFORLOG="Ønsker du at se installationsloggen?"
_UPDATEADVERROR="En alvorlig fejl opstod under håndteringen af disse pakker"
_UPDATEINSTALLS="Opdaterer pakkerne, dette kan tage adskillige minutter..."
_UPDATES="Opdateringer"
_UPDATEVERSION="Version"
_UPDATETODATE="Din installation indeholder allerede de seneste XBian-pakker"
_ASKFORSYSTEMUPDATE="En ny version af XBian er tilgængelig, øsnker du at installere den nu? Systemet vil genstarte automatisk når opdateringen er fuldført"
_UPGRADESYSTEM="XBian opgraderes til en ny version, undlad at genstarte eller afbryde stømmen da dette kan medføre fejl i systemet, varigheden for denne handling afhænger af hastigheden på din internetforbindelse..."
_UPDATESYSTEMREBOOT="XBian genstartes automatisk når dette vindue lukkes"
_UPDATEDOWNGRADE="Du har allerede nyere versioner af disse pakker installeret"