#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Updates"
_DESC="Check for system updates"
_UPDATINGAPTDB="Update local package database..."
_UPDATEDOWNLOADLIST="Retrieving list of upgradeable packages..."
_UPDATEAPTDBFAILED="An error occured while updating the package database"
_DOWNLOADINGPACKAGELIST="Downloading remote package database..."
_FAILEDTORETRIEVEAPTMIRRORS="Failed to retrieve download mirrors, therefore a local (possibly outdated) list will be used"
_CONFIRMUPDAGESINSTALL="Are you sure you want to update these packages?"
_UPDATEALREADYINSTALLED="The latest versions of these packages are already installed"
_UPDATEVERSIONNOTEXISTS="The packages versions you are trying to install could not be found"
_UPDATENOTEXISTS="The packages you are trying to install could not be found"
_UPDATEINSTALLSUCCESS="The packages are successfully updated"
_UPDATEASKFORLOG="Would you like to see the installation log?"
_UPDATEADVERROR="A serious error occured while processing these packages"
_UPDATEINSTALLS="Updating the packages, this could take several minutes so please wait..."
_UPDATES="Updates"
_UPDATEVERSION="Version"
_UPDATETODATE="Your install already contains the latest versions of XBian packages"
_ASKFORSYSTEMUPDATE="A new XBian version is available, would you like to install it now? The system will reboot automatically when the update is finished"
_UPGRADESYSTEM="XBian is being upgraded to a new version, please do not reboot or pull the power plug because this could result in a malfunctioning system, depending on your internet connection, this procedure can take quit some time..."
_UPDATESYSTEMREBOOT="XBian will reboot automatically when you close this window"
_UPDATEDOWNGRADE="You already got newer versions of this package installed"