#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Actualizaciones"
_DESC="Buscar actualizaciones"
_UPDATINGAPTDB="Actualizando la base de datos..."
_UPDATEDOWNLOADLIST="Recibiendo la lista de actualizaciones..."
_UPDATEAPTDBFAILED="Ha ocurrido un error mientras se actualizaba la base de datos"
_DOWNLOADINGPACKAGELIST="Descargando la lista de actualizaciones..."
_FAILEDTORETRIEVEAPTMIRRORS="La descarga ha fallado, se utilizara la base de datos local"
_CONFIRMUPDAGESINSTALL="¿Estas seguro de que quieres actualizar estos modulos?"
_UPDATEALREADYINSTALLED="Ya tiene instalado la ultima version de estos modulos"
_UPDATEVERSIONNOTEXISTS="La version de los modulos que intenta instalar podrian no encontrarse"
_UPDATENOTEXISTS="Los modulos que intenta instalar podrian no encontrarse"
_UPDATEINSTALLSUCCESS="Los modulos han sido actualizados con exito"
_UPDATEASKFORLOG="¿Quieres ver el registro de instalacion?"
_UPDATEADVERROR="Un error ha ocurrido mientras procesabamos estos modulos"
_UPDATEINSTALLS="Actualizando los modulos, puede tardar algunos minutos, por favor espere..."
_UPDATES="Actualizaciones"
_UPDATEVERSION="Version"
_UPDATETODATE="Ya tienes instalados la ultima version de los modulos de XBian"
_ASKFORSYSTEMUPDATE="Una nueva version de XBian esta disponible, ¿quieres instalarla?. El sistema se reiniciara cuando la actualizacion acabe"
_UPGRADESYSTEM="XBian está siendo actualizado con una nueva versión, por favor no reinicie ni desconecte la alimentación, porque podría generar un problemas con el sistema, dependiendo de tu conexión a internet, este procedimiento puede llevar algún tiempo...."
_UPDATESYSTEMREBOOT="XBian será reiniciado automáticamente cuando cierres esta ventana"
_UPDATEDOWNGRADE="Ya estás utilizando la última versión de este módulo"
