#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Mises à jour"
_DESC="Vérification des mises à jour"
_UPDATINGAPTDB="Mise a jour du paquet de dépot..."
_UPDATEDOWNLOADLIST="Récupération des paquets pouvant être mis à jour..."
_UPDATEAPTDBFAILED="Une erreur est survenue lors de la maj de la base de donnée"
_DOWNLOADINGPACKAGELIST="Téléchargement de la base de donnée distante..."
_FAILEDTORETRIEVEAPTMIRRORS="Téléchargement des mirroirs echoués, La base locale (peut être pas a jour) va être utilisée"
_CONFIRMUPDAGESINSTALL="Etes vous sur de vouloir mettre à jours ces packages?"
_UPDATEALREADYINSTALLED="Ces paquets sont déja à jour"
_UPDATEVERSIONNOTEXISTS="Les versions des paquets à installer n'ont pas été trouvées"
_UPDATENOTEXISTS="Les paquets à installer n'ont pas été trouvé "
_UPDATEINSTALLSUCCESS="Les paquets ont été mis a jour"
_UPDATEASKFORLOG="Would you like to see the installation log?"
_UPDATEADVERROR="Une erreur importante est survenue"
_UPDATEINSTALLS="Mises à jour des paquets, cela peut prendre quelques minutes. Veuillez pastienter "
_UPDATES="Mises à jour"
_UPDATEVERSION="Version"
_UPDATETODATE="Votre installation contient déja les dernières versions des paquets XBian"
_ASKFORSYSTEMUPDATE="Une nouvelle version de XBian est disponible, voulez-vous l'installer maintenant? Le systeme redémarrera automatiquement après la mise a jour"
_UPGRADESYSTEM="Une nouvelle version de XBian est en cours d'installation, Ne redémarrer pas et ne debranché pas le RPI, cela pourrait rendre votre système no fonctionnel, en fonction de votre connection internet, la procédure peut durer assez longtemps"
_UPDATESYSTEMREBOOT="XBian redémarrera automatiquement lorsque vous fermerez cette fenêtre"
_UPDATEDOWNGRADE="Vous avez déja la dernière version du paquet installée"