#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Updates"
_DESC="Controleer op systeem updates"
_UPDATINGAPTDB="Lokale pakketten database aan het bijwerken..."
_UPDATEDOWNLOADLIST="Lijst van bij te werken pakketten aan het ophalen..."
_UPDATEAPTDBFAILED="Er is een fout opgetreden bij het bijwerken van de pakketten database"
_DOWNLOADINGPACKAGELIST="Externe pakketten database aan het ophalen..."
_FAILEDTORETRIEVEAPTMIRRORS="Het ophalen van de download mirrors is niet gelukt, er zal daarom een lokale (mogelijk verouderde) lijst worden gebruikt"
_CONFIRMUPDAGESINSTALL="Weet u zeker dat u deze pakketten bijwerken?"
_UPDATEALREADYINSTALLED="De laatste versie van deze pakketten is al geinstalleerd"
_UPDATEVERSIONNOTEXISTS="De versie van de pakketten die u probeert te installeren, kunnen niet gevonden worden"
_UPDATENOTEXISTS="De pakketten die u probeert bij te werken, kunnen niet gevonden worden"
_UPDATEINSTALLSUCCESS="De pakketten zijn succesvol bijgewerkt"
_UPDATEASKFORLOG="Wilt u het installatie log bestand inkijken?"
_UPDATEADVERROR="Er is een serieuze fout opgetreden tijdens het verwerken van deze pakketten"
_UPDATEINSTALLS="Bezig met het bijwerken van deze pakketten, dit kan een paar minuten duren dus een ogenblik geduld aub..."
_UPDATES="Update"
_UPDATEVERSION="Versie"
_UPDATETODATE="Uw installatie bevat al de laatste versies XBian pakketten"
_ASKFORSYSTEMUPDATE="Een nieuwe versie van XBian is beschikbaar, wilt u deze nu installeren? Het systeem zal automatisch herstarten nadat deze update klaar is"
_UPGRADESYSTEM="XBian wordt op dit moment bijgewerkt naar een nieuwe versie, laat de stroom op je Raspberry Pi zitten en doe geen herstart, dit kan resulteren in een onbruikbaar systeem, afhankelijk van uw internetverbinding kan deze procedure enige tijd duren..."
_UPDATESYSTEMREBOOT="XBian zal automatisch herstarten zodra u dit scherm sluit"
_UPDATEDOWNGRADE="U heeft al nieuwere versies van deze paketten geinstalleerd"