#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Aktualizácie"
_DESC="Skontroluj systémové aktualizácie"
_UPDATINGAPTDB="Aktualizuj lokálnu databázu balíkov..."
_UPDATEDOWNLOADLIST="Získavanie zoznamu aktualizovateľných balíkov..."
_UPDATEAPTDBFAILED="Vyskytla sa chyba pri aktualizácii databázy balíkov"
_DOWNLOADINGPACKAGELIST="Preberanie databázy balíkov..."
_FAILEDTORETRIEVEAPTMIRRORS="Nepodarilo sa načítať zoznam sererov, takže bude použitý starý lokálny zoznam"
_CONFIRMUPDAGESINSTALL="Si si istý že chceš aktualizovať tieto balíky?"
_UPDATEALREADYINSTALLED="Najnovšie verzie týchto balíkov sú už nainštalované"
_UPDATEVERSIONNOTEXISTS="Verzie balíkov ktoré sa snažíš nainštalovať niesú dostupné"
_UPDATENOTEXISTS="Balíky ktoré sa snažíš nainštalovať niesú dostupné"
_UPDATEINSTALLSUCCESS="Balíky boli úspešne aktualizované"
_UPDATEASKFORLOG="Chceš si prezrieť log nainštalácie?"
_UPDATEADVERROR="Nastala vážna chyba pri spracovávaní týchto balíkov"
_UPDATEINSTALLS="Aktualizácia balíkov, tento proces môže trvať zopár minút, prosím čakať..."
_UPDATES="Aktualizácie"
_UPDATEVERSION="Verzia"
_UPDATETODATE="V systéme sa nachádza najnovšia verzia balíkov XBian"
_ASKFORSYSTEMUPDATE="Nová verzia XBian je dostupná, chceš ju nainštalovať? Systém bude automaticky zreštartovaný po skončení aktualizácie"
_UPGRADESYSTEM="Prebieha aktualizácia XBian na novšiu verziu, prosím nereštartovať alebo neodpájať z elektrickej siete pretože by to mohlo mať za následok znefunkčnenie systému. Táto operácia môže trvať niekoľko minút, v závislosti od internetového pripojenia..."
_UPDATESYSTEMREBOOT="XBian bude zreštartovaný po zatvorení tohto okna"
_UPDATEDOWNGRADE="Najnovšia verzia tohto balíka je už nainštalovaná"