#!/bin/bash

if [ $1 == "remove" ]; then
	
	if [ -d /usr/local/include/xbian-config ]; then
		rm -r /usr/local/include/xbian-config;
	fi
	
	if [ -f /usr/local/sbin/xbian-config ]; then
		rm /usr/local/sbin/xbian-config
	fi
	
fi