#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="SSH root login"
_DESC="Enable/Disable SSH root login"
_SSHROOTENABLE="Do you want to enable or disable root ssh login?"
_NOSSHROOTPASS="User root has an empty password, without a password user root cannot login through SSH so please set this first."
_SSHROOTENABLED="SSH root login successfully enabled"
_SSHROOTDISABLED="SSH root login successfully disabled"