#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Superusuario SSH"
_DESC="(Des)activar acceso superusuario SSH"
_SSHROOTENABLE="Quieres activar o desactivar el acceso al superusuario mediante SSH"
_NOSSHROOTPASS="La contraseña de superusuario esta vacia, sin contraseña no se puede acceder como superusuario mediante SSH, por favor corrigalo."
_SSHROOTENABLED="Acceso como superusuario mediante SSH activado con exito"
_SSHROOTDISABLED="Acceso como superusuario mediante SSH desactivado"