#!/bin/bash

function rootpass() {
	VALUES=$(dialog --ok-label "Change" \
		  --backtitle "$BACKTITLE" \
		  --title " $1 " \
		  --insecure \
		  --passwordform "\n   Change root password " \
		10 55 0 \
		"Password:" 1 3		"" 1 15 15 0 \
		"Confirm:"  2 3		"" 2 15 15 0 \
		3>&1 1>&2 2>&3)
	if [ ${#VALUES} -ne 0 ]; then
		VALUES=( $VALUES )
		if [ ${#VALUES[@]} -eq 2 ]; then
			if [ ! -z ${VALUES[0]} ] && [ ! -z ${VALUES[1]} ] && [ "${VALUES[0]}" == "${VALUES[1]}" ]; then
				echo "root:${VALUES[0]}" | chpasswd
				showdialog "$1" "Close" "\n        root password succesfully changed" 
			else
				showdialog "$1" "Retry" "\n      Passwords did not match"
				xbian-rootpass;
			fi
		else
			showdialog "$1" "Retry" "\n  You have to enter both a new password and a confirmation." 7 65
			xbian-rootpass;
		fi
	fi
}
