#!/bin/bash
function xbian-timezone() {
	showinfo	"$1" \
			"\n\n  Please wait while 'tzdata' is loading..." 7 47
	dpkg-reconfigure tzdata
	showdialog 	"$1" \
			"Close" \
			"\n      Timezone succesfully changed" 9 42
}
