#!/bin/bash
function xbian-timezone() {
	showinfo	"$1" \
			"\n   Please wait while 'tzdata' is loading..."
	dpkg-reconfigure tzdata
	showdialog 	"$1" \
			"Close" \
			"\n          Timezone succesfully changed"
}
