#!/bin/bash

function xbian-sshroot() {
	if [ -z $(cat /etc/shadow | grep root | cut -f 2 -d:) ]; then
		showdialog "$1" "Close" "\n  User root has an empty password, without a\n  password user root cannot login through ssh\n  so please set this first."
		return 0;
	fi
	dialog 		--backtitle "$BACKTITLE" \
			--title "$1" \
			--yes-label "Enable" \
			--no-label "Disable" \
			--yesno "\n Do you want to enable or disable root ssh login?" 7 55
	if [ $? -eq 0 ]; then
		sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config
		/etc/init.d/ssh restart >/dev/null
		showdialog "$1" "Close" "\n        SSH root login succesfully enabled"
	else
		sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
		/etc/init.d/ssh restart >/dev/null
		showdialog "$1" "Close" "\n        SSH root login succesfully disabled"
	fi
}
