#!/bin/bash

function xbian-overclocking() {
	showdialog "$1" "Close" "\nBe aware that overclocking may reduce the lifetime of your Raspberry Pi. If overclocking at a certain level causes system instability, try a more modest overclock. See http://elinux.org/RPi_Overclocking for more information." 10 65
	showmenu	"$1" \
			1 "None     700MHz ARM, 250MHz core, 400MHz SDRAM, 0 overvolt" \
			2 "Modest   800MHz ARM, 300MHz core, 400MHz SDRAM, 0 overvolt" \
			3 "XBian    840MHz ARM, 375MHz core, 400MHz SDRAM, 0 overvolt" \
			4 "Medium   900MHz ARM, 333MHz core, 450MHz SDRAM, 2 overvolt" \
			5 "High     950MHz ARM, 450MHz core, 450MHz SDRAM, 6 overvolt" \
			6 "Turbo    1000MHz ARM, 500MHz core, 500MHz SDRAM, 6 overvolt"
	case "$RETURN" in
		1)
			set_overclock None 700 250 400 0
		;;
		2)
			set_overclock Modest 800 300 400 0
		;;
		3)
			set_overclock XBian 840 375 400 0
		;;
		4)
			set_overclock Medium 900 333 450 2
		;;
		5)
			set_overclock High 950 450 450 6
		;;
		6)
			set_overclock Turbo 1000 500 500 6
		;;
	esac
}
