#!/bin/bash

function xbian-notimplemented() {
        showdialog      "Config > Not implemented" \
                        "Close" \
                        "\n       This function is not yet implemented"
}
