#!/bin/bash

function xbian-forcehdmi() {
	showyesno 	"$1" \
			"\n  Enabling this option forces the pi to enable HDMI\n  at boot, even if no TV is connected. \n\n  Is this what you want?" 12 60
	case "$?" in
		0) 
			set_config_var force_hdmi_hotplug 1 /boot/config.txt >/dev/null
			showdialog 	"$1" \
					"Close" \
					"\n      Force HDMI hotplug successfully enabled"
		;;
		1)
			remove_config_var "force_hdmi_hotplug" /boot/config.txt >/dev/null
			showdialog 	"$1" \
					"Close" \
					"\n      Force HDMI hotplug successfully disabled"
		;;
	esac
}

