#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

	if [ ! -d "/boot" ]; then
		mkdir -p "/boot";
	fi

	if [ ! -d "/lib/modules/3.6.7" ]; then
		mkdir -p "/lib/modules/3.6.7";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/squashfs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/squashfs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/hfsplus" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/hfsplus";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/nfsd" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/nfsd";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/isofs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/isofs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/quota" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/quota";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/btrfs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/btrfs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/ocfs2/dlm" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/ocfs2/dlm";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/ocfs2" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/ocfs2";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/ocfs2/dlmfs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/ocfs2/dlmfs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/ocfs2/cluster" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/ocfs2/cluster";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/nls" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/nls";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/hfs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/hfs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/nilfs2" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/nilfs2";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/cifs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/cifs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/jfs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/jfs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/9p" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/9p";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/udf" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/udf";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/ecryptfs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/ecryptfs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/reiserfs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/reiserfs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/ntfs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/ntfs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/fuse" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/fuse";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/xfs" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/xfs";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/fs/gfs2" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/fs/gfs2";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/lib/zlib_deflate" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/lib/zlib_deflate";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/lib" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/lib";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/arch/arm/oprofile" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/arch/arm/oprofile";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/crypto" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/crypto";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/irda/irnet" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/irda/irnet";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/irda" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/irda";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/irda/irlan" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/irda/irlan";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/irda/ircomm" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/irda/ircomm";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/wimax" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/wimax";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/bluetooth/hidp" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/bluetooth/hidp";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/bluetooth" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/bluetooth";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/bluetooth/rfcomm" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/bluetooth/rfcomm";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/bluetooth/bnep" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/bluetooth/bnep";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/802" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/802";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/netfilter" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/netfilter";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/netfilter/ipset" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/netfilter/ipset";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/bridge/netfilter" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/bridge/netfilter";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/bridge" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/bridge";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/nfc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/nfc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/8021q" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/8021q";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/wireless" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/wireless";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/mac80211" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/mac80211";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/rose" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/rose";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/llc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/llc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/l2tp" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/l2tp";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/9p" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/9p";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/sched" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/sched";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/ipv4" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/ipv4";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/ipv4/netfilter" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/ipv4/netfilter";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/ax25" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/ax25";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/openvswitch" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/openvswitch";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/key" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/key";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/xfrm" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/xfrm";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/netrom" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/netrom";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/ipv6" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/ipv6";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/ipv6/netfilter" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/ipv6/netfilter";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/net/core" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/net/core";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/connector" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/connector";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/base/regmap" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/base/regmap";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/bluetooth" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/bluetooth";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/cpufreq" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/cpufreq";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/spi" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/spi";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/uio" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/uio";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/staging/csr" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/staging/csr";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/staging/zram" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/staging/zram";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/staging/media/lirc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/staging/media/lirc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/staging/gdm72xx" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/staging/gdm72xx";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/staging/winbond" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/staging/winbond";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/staging/ozwpan" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/staging/ozwpan";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/staging/rtl8712" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/staging/rtl8712";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/staging/wlan-ng" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/staging/wlan-ng";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/hsi/clients" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/hsi/clients";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/hsi" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/hsi";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/input" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/input";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/input/serio" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/input/serio";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/input/misc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/input/misc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/input/gameport" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/input/gameport";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/i2c/busses" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/i2c/busses";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/i2c/algos" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/i2c/algos";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/i2c" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/i2c";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/rtc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/rtc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/radio" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/radio";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/radio/si470x" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/radio/si470x";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/dvb/dvb-core" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/dvb/dvb-core";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/dvb/b2c2" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/dvb/b2c2";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/dvb/frontends" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/dvb/frontends";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/dvb/siano" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/dvb/siano";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/dvb/dvb-usb" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/dvb/dvb-usb";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/rc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/rc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/rc/keymaps" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/rc/keymaps";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/uvc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/uvc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/em28xx" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/em28xx";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/hdpvr" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/hdpvr";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/pwc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/pwc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/pvrusb2" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/pvrusb2";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/gspca" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/gspca";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/gspca/gl860" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/gspca/gl860";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/gspca/stv06xx" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/gspca/stv06xx";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/gspca/m5602" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/gspca/m5602";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/usbvision" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/usbvision";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/sn9c102" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/sn9c102";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/cx231xx" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/cx231xx";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/video/cx25840" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/video/cx25840";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/media/common/tuners" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/media/common/tuners";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/leds" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/leds";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/nfc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/nfc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/misc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/misc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/misc/eeprom" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/misc/eeprom";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/w1" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/w1";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/w1/slaves" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/w1/slaves";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/w1/masters" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/w1/masters";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/scsi" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/scsi";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/usb/storage" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/usb/storage";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/usb/image" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/usb/image";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/usb/serial" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/usb/serial";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/usb/host" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/usb/host";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/usb/class" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/usb/class";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/usb/misc" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/usb/misc";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/usb/chipidea" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/usb/chipidea";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/usb/phy" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/usb/phy";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/usb/mon" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/usb/mon";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/ssb" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/ssb";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/irda" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/irda";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wimax/i2400m" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wimax/i2400m";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/hamradio" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/hamradio";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/libertas" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/libertas";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/ath/carl9170" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/ath/carl9170";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/ath" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/ath";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/ath/ath9k" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/ath/ath9k";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/rtl8192cu" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/rtl8192cu";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/b43" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/b43";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/p54" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/p54";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/rtl818x/rtl8187" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/rtl818x/rtl8187";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/hostap" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/hostap";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/libertas_tf" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/libertas_tf";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/b43legacy" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/b43legacy";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/rt2x00" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/rt2x00";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/zd1211rw" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/zd1211rw";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/wireless/mwifiex" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/wireless/mwifiex";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/ppp" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/ppp";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/usb" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/usb";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/bonding" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/bonding";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/slip" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/slip";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/net/phy" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/net/phy";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/hid" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/hid";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/watchdog" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/watchdog";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/video/backlight" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/video/backlight";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/video" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/video";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/cdrom" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/cdrom";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/block" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/block";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/block/drbd" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/block/drbd";
	fi

	if [ ! -d "/lib/modules/3.6.7/kernel/drivers/extcon" ]; then
		mkdir -p "/lib/modules/3.6.7/kernel/drivers/extcon";
	fi

	if [ ! -d "/lib/modules/3.6.7/extra" ]; then
		mkdir -p "/lib/modules/3.6.7/extra";
	fi
	
fi