#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Zona horaria"
_DESC="Cambiar la zona horaria de tu RPi"
_TZLOADINGCURRENT="Cargando tu zona horaria actual..."
_TIMEZONE="Zona horaria"
_TZLOCATION="Pais"
_TZOLDANDNEW="La vieja y nueva fecha/hora:"
_TZNOCATEGORYSELECTED="No has seleccionado una zona horaria"
_TZNOLOCATIONSELECTED="No has seleccionado un pais"
_TZLOADINGLOCATIONS="Cargando paises..."