#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="SSH root login"
_DESC="Разр/Запр польз. root входить через SSH"
_SSHROOTENABLE="Вы хотите разрешить или запретить пользователю root входить через ssh?"
_NOSSHROOTPASS="Пользователь root имеет пустой пароль, без пароля пользователь root не может заходить через SSH, поэтому, пожалуйста, установите пароль."
_SSHROOTENABLED="Пользователю root разрешено входить через SSH"
_SSHROOTDISABLED="Пользователю root запрещено входить через SSH"