#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function setXBConfigLanguageFn() {
	if [ -f $BASEPATH"/config/xbconfig" ]; then
		CURLANG=$(cat $BASEPATH'/config/xbconfig' | grep language | cut -f2 -d':')
		sed -i "s/language:$CURLANG/language:$1/g" $BASEPATH"/config/xbconfig";
	else
		if [ -z "$1" ]; then
			echo "language:" >> $BASEPATH"/config/xbconfig";
		else
			echo "language:"$1 >> $BASEPATH"/config/xbconfig";
		fi
	fi
	if [ "$(cat $BASEPATH'/config/xbconfig' | grep language | cut -f2 -d':')" == "$1" ]; then
		getLanguageFn;
		if [ -f "$BASEPATH/lang/$LANGUAGE" ]; then
			source $BASEPATH/lang/$LANGUAGE
		else
			source $BASEPATH/lang/en
		fi
		if [ -f "$BASEPATH/modules/xbconfig/lang/$LANGUAGE" ]; then
			source $BASEPATH/modules/xbconfig/lang/$LANGUAGE
		else
			source $BASEPATH/modules/xbconfig/lang/en
		fi
		return 1;
	else
		return 0;
	fi
}

function setXBConfigAutoStartFn() {
	if [ $1 -eq 0 ]; then
		sed -i 's/sudo xbian-config/#sudo xbian-config/g' /home/xbian/.bashrc;
	else
		if [ $(grep xbian-config /home/xbian/.bashrc | wc -l) -eq 1 ]; then
			sed -i 's/#sudo xbian-config/sudo xbian-config/g' /home/xbian/.bashrc;
		else
			echo "sudo xbian-config" >> /home/xbian/.bashrc;
		fi
	fi
	if [ $1 -eq 1 ]; then
		if [ $(grep "^sudo xbian-config" /home/xbian/.bashrc | wc -l) -eq 1 ]; then
			return 1;
		else
			return 0;
		fi
	elif [ $1 -eq 0 ]; then
		if [ $(grep "^#sudo xbian-config" /home/xbian/.bashrc | wc -l) -eq 1 ] || [ $(grep "xbian-config" /home/xbian/.bashrc | wc -l) -eq 0 ]; then
			return 1;
		else
			return 0;
		fi
	else
		return 0;
	fi
}