#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Обновления"
_DESC="Проверка наличия обновлений"
_UPDATINGAPTDB="Обновление локальной базы пакетов..."
_UPDATEDOWNLOADLIST="Получение списка доступных обновлений..."
_UPDATEAPTDBFAILED="Во время обновления базы пакетов произошла ошибка"
_DOWNLOADINGPACKAGELIST="Загружается база пакетов..."
_FAILEDTORETRIEVEAPTMIRRORS="Не удалось получить список зеркал, поэтому будет использован имеющийся (возможно, устаревший) список пакетов"
_CONFIRMUPDAGESINSTALL="Вы действительно хотите обновить эти пакеты?"
_UPDATEALREADYINSTALLED="Последняя версия этого пакета уже установлена"
_UPDATEVERSIONNOTEXISTS="Не удалось найти версии пакетов, которые вы хотите установить"
_UPDATENOTEXISTS="Пакеты, которые вы хотите установить, не найдены"
_UPDATEINSTALLSUCCESS="Пакеты успешно обновлены"
_UPDATEASKFORLOG="Вы хотите посмотреть лог обновления?"
_UPDATEADVERROR="При обработке пакетов произошла серьезная ошибка"
_UPDATEINSTALLS="Пакеты обновляются, это может занять некоторое время..."
_UPDATES="Updates"
_UPDATEVERSION="Version"
_UPDATETODATE="Нет доступных обновлений"
_ASKFORSYSTEMUPDATE="Доступна новая версия XBian, вы хотите установить ее сейчас? Когда обновление закончится, система автоматически перезагрузится"
_UPGRADESYSTEM="XBian обновляется, пожалуйста не перезагружайте и не отключайте устройство, так как это может привести к неработоспособности системы. В зависимости от скорости вашего интернет-соединения, это может занять некоторое время..."
_UPDATESYSTEMREBOOT="XBian перезагрузится автоматически когда вы закроете это окно"
_UPDATEDOWNGRADE="Уже установлена более новая версия пакета"