#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#Resize SD function is based on the corresponding function in raspi-config
#The overclocking function is copied from raspi-config
#raspi-config is created by Alex Bradbury <asb@asbradbury.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function licensevc1() {
	SETTING=$(cat /boot/config.txt | grep 'decode_WVC1');
	CLICENSE=$(cat /boot/config.txt | grep 'decode_WVC1' | cut -f 2 -d=);
	if [ ! -z $SETTING ]; then
		BUTTON="Change";
		MESSAGE="changed";
	else
		BUTTON="Insert";
		MESSAGE="inserted";
	fi
	LICENSE=$(dialog --backtitle "$BACKTITLE" --title "$1" --ok-label $BUTTON --inputbox "License VC-1:" 7 55 $CLICENSE 3>&1 1>&2 2>&3)
	if [ $? -eq 0 ]; then
		if [ ! -z $LICENSE ]; then
			if [ ! -z $SETTING ]; then
				sed -i "s/$SETTING/decode_WVC1=$LICENSE/g" /boot/config.txt;
			else
				echo "decode_WVC1=$LICENSE" >> /boot/config.txt
			fi
			showdialog "$1" "Close" "\n        VC-1 license succesfully $MESSAGE"
		else
			if [ ! -z $SETTING ]; then
				sed -i "s/$SETTING//g" /boot/config.txt
				showdialog "$1" "Close" "\n        VC-1 license succesfully deleted"
			fi
		fi
	fi
	sed -i '/^$/d' /boot/config.txt
}
