#!/bin/bash

function licensevc1() {
	SETTING=$(cat /boot/config.txt | grep 'decode_WVC1');
	CLICENSE=$(cat /boot/config.txt | grep 'decode_WVC1' | cut -f 2 -d=);
	if [ ! -z $SETTING ]; then
		BUTTON="Change";
		MESSAGE="changed";
	else
		BUTTON="Insert";
		MESSAGE="inserted";
	fi
	LICENSE=$(dialog --backtitle "$BACKTITLE" --title "$1" --ok-label $BUTTON --inputbox "License VC-1:" 7 55 $CLICENSE 3>&1 1>&2 2>&3)
	if [ $? -eq 0 ]; then
		if [ ! -z $LICENSE ]; then
			if [ ! -z $SETTING ]; then
				sed -i "s/$SETTING/decode_WVC1=$LICENSE/g" /boot/config.txt;
			else
				echo "decode_WVC1=$LICENSE" >> /boot/config.txt
			fi
			showdialog "$1" "Close" "\n        VC-1 license succesfully $MESSAGE"
		else
			if [ ! -z $SETTING ]; then
				sed -i "s/$SETTING//g" /boot/config.txt
				showdialog "$1" "Close" "\n        VC-1 license succesfully deleted"
			fi
		fi
	fi
	sed -i '/^$/d' /boot/config.txt
}
