#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#Resize SD function is based on the corresponding function in raspi-config
#The overclocking function is copied from raspi-config
#raspi-config is created by Alex Bradbury <asb@asbradbury.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function overclocking() {
	showdialog "$1" "Close" "\n Be aware that overclocking may reduce the lifetime of your\n  Raspberry Pi. If overclocking at a certain level causes\n      system instability, try a more modest overclock.\nSee http://elinux.org/RPi_Overclocking for more information." 10 65
	showmenu	"$1" \
			1 "None     700MHz ARM, 250MHz core, 400MHz SDRAM, 0 overvolt" \
			2 "Modest   800MHz ARM, 300MHz core, 400MHz SDRAM, 0 overvolt" \
			3 "XBian    840MHz ARM, 375MHz core, 400MHz SDRAM, 0 overvolt" \
			4 "Medium   900MHz ARM, 333MHz core, 450MHz SDRAM, 2 overvolt" \
			5 "High     950MHz ARM, 450MHz core, 450MHz SDRAM, 6 overvolt" \
			6 "Turbo    1000MHz ARM, 500MHz core, 500MHz SDRAM, 6 overvolt"
	case "$RETURN" in
		1)
			set_overclock None 700 250 400 0
		;;
		2)
			set_overclock Modest 800 300 400 0
		;;
		3)
			set_overclock XBian 840 375 400 0
		;;
		4)
			set_overclock Medium 900 333 450 2
		;;
		5)
			set_overclock High 950 450 450 6
		;;
		6)
			set_overclock Turbo 1000 500 500 6
		;;
	esac
}
