#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#Resize SD function is based on the corresponding function in raspi-config
#The overclocking function is copied from raspi-config
#raspi-config is created by Alex Bradbury <asb@asbradbury.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function resizesd() {
	showyesno	"$1 " \
			"\n      Are you sure you want to resize you SD card?" 7 60;
	case "$?" in
		1)
			return 0;
		;;
	esac

	PART_START=$(fdisk -l | grep mmcblk0p2 | awk '{print $2}');
	CPART_START=$PART_START;
	CPART_END=$(fdisk -l | grep mmcblk0p2 | awk '{print $3}');
	SDEND=$(fdisk -l | sed -n '/mmcblk0/{n;p;}' | head -1 | awk '{print $8}');
	SDEND=$(($SDEND-1));
	SWAP=$(fdisk -l | grep 'mmcblk0p3' | awk '{print $5}');

	PART_END=$SDEND;
	
	if [[ $PART_START -eq $CPART_START && $PART_END -eq $CPART_END ]]; then
		showdialog "$1 " "Ok" "\n      This SD card is already resized. Aborting." 7 60
		return 0;
	fi
	
	if [ $DEBUG -eq 0 ]; then
		if [ ! -z $SWAP ] && [ $SWAP -eq 82 ]; then
			swapoff -a
		
fdisk /dev/mmcblk0 2>/dev/null >/dev/null <<EOF
d
2
d
3
n
p
2
$PART_START
$PART_END
w
EOF

			sed -i '/swap/d' /etc/fstab
		else
		
fdisk /dev/mmcblk0 2>/dev/null >/dev/null <<EOF
d
2
n
p
2
$PART_START
$PART_END
w
EOF

		fi
	fi

	ASKFORREBOOT=1;

# now set up an init.d script
	if [ $DEBUG -eq 0 ]; then
cat <<\EOF > /etc/init.d/resize2fs_once
#!/bin/sh
### BEGIN INIT INFO
# Provides: resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5 S
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once"
    resize2fs /dev/mmcblk0p2 >/dev/null
    rm /etc/init.d/resize2fs_once >/dev/null
    update-rc.d resize2fs_once remove >/dev/null
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
EOF
	chmod +x /etc/init.d/resize2fs_once >/dev/null;
	update-rc.d resize2fs_once defaults >/dev/null 2>/dev/null;
	fi

	showdialog "$1 " "Ok" "\n\n  Root partition has been resized. The\n  filesystem will be enlarged upon the\n  next reboot." 11 44
}
