#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#Resize SD function is based on the corresponding function in raspi-config
#The overclocking function is copied from raspi-config
#raspi-config is created by Alex Bradbury <asb@asbradbury.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function rootpass() {
	VALUES=$(dialog --ok-label "Change" \
		  --backtitle "$BACKTITLE" \
		  --title " $1 " \
		  --insecure \
		  --passwordform "\n   Change root password " \
		10 60 0 \
		"Password:" 1 3		"" 1 15 15 0 \
		"Confirm:"  2 3		"" 2 15 15 0 \
		3>&1 1>&2 2>&3)
	if [ $? -eq 0 ]; then
		if [ ${#VALUES} -ne 0 ]; then
			VALUES=( $VALUES )
			if [ ${#VALUES[@]} -eq 2 ]; then
				if [ ! -z ${VALUES[0]} ] && [ ! -z ${VALUES[1]} ] && [ "${VALUES[0]}" == "${VALUES[1]}" ]; then
					echo "root:${VALUES[0]}" | chpasswd
					showdialog "$1" "Close" "\n          root password succesfully changed" 7 60
				else
					showdialog "$1" "Retry" "\n                Passwords didn't match" 7 60
					rootpass $1;
				fi
			else
				showdialog "$1" "Retry" "\n  You have to enter both a new password and a confirmation." 7 65
				rootpass $1;
			fi
		else
			showdialog "$1" "Retry" "\n            You didn't enter any values." 7 60
			rootpass $1;
		fi
	fi
}
