#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#Resize SD function is based on the corresponding function in raspi-config
#The overclocking function is copied from raspi-config
#raspi-config is created by Alex Bradbury <asb@asbradbury.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function sshroot() {
	if [ -z $(cat /etc/shadow | grep root | cut -f 2 -d:) ]; then
		showdialog "$1" "Close" "\n  User root has an empty password, without a\n  password user root cannot login through ssh\n  so please set this first."
		return 0;
	fi
	showyesno " $1 " "\n Do you want to enable or disable root ssh login?" 7 55 "Enable" "Disable"
	if [ $? -eq 0 ]; then
		sed -i 's/PermitRootLogin no/PermitRootLogin yes/g' /etc/ssh/sshd_config
		/etc/init.d/ssh restart >/dev/null
		showdialog "$1" "Close" "\n        SSH root login succesfully enabled"
	else
		sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
		/etc/init.d/ssh restart >/dev/null
		showdialog "$1" "Close" "\n        SSH root login succesfully disabled"
	fi
}
