#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#Resize SD function is based on the corresponding function in raspi-config
#The overclocking function is copied from raspi-config
#raspi-config is created by Alex Bradbury <asb@asbradbury.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function switchkernel() {
	KERNELS=($(ls -Al /boot/*.img | awk '{print $9}' | grep -iv kernel.img));
	if [ ${#KERNELS[@]} -eq 1 ]; then
		showdialog "$1" "Close" "\n       You can't switch kernel because there\n           is only one version installed.\n" 8
		return 0;
	else
		LIST=();
		I=0;
		for KERNEL in ${KERNELS[@]}; do
			I=$(($I+1));

			CKERNEL=$(ls -Al /boot/kernel.img | awk '{print $5}');
			NKERNEL=$(ls -Al $KERNEL | awk '{print $5}');

			KERNEL=${KERNEL##*/};
			KERNEL=${KERNEL%.*};

			KERNEL=$(echo $KERNEL | sed -e 's/kernel//g' | sed -e 's/\_/./g');
			if [[ $NKERNEL -eq $CKERNEL ]]; then
				LIST+=("$I $KERNEL on ");
			else
				LIST+=("$I $KERNEL off ");
			fi
		done;
		IFS=" ";
		showradiolist "$1" " Press [space] to select a different kernel version:" "${LIST[*]}" $I 10 60
		case $? in
			0 )
				KERNEL=${KERNELS[$(($RETURN-1))]};
				NKERNEL=$(ls -Al $KERNEL | awk '{print $5}');
				CKERNEL=$(ls -Al /boot/kernel.img | awk '{print $5}');
				if [[ $NKERNEL -eq $CKERNEL ]]; then
					showdialog "$1" "Close" "\n       You're already running kernel v3.2.27\n"
					return 0;
				else
					cp $KERNEL /boot/kernel.img
					KERNEL=${KERNEL##*/};
					KERNEL=${KERNEL%.*};
					KERNEL=$(echo $KERNEL | sed -e 's/kernel//g' | sed -e 's/\_/./g');
					showdialog "$1" "Close" "\n      Succesfully switched to kernel v$KERNEL\n A reboot is needed to make this change permanent.\n" 8
					ASKFORREBOOT=1
					return 0;
				fi
			;;
			* )
				return 0;
			;;
		esac
		return 0;
	fi
	return 0;
}
