#!/bin/bash
#
#Copyright 2012 CurlyMo & Hexagon <development@xbian.org>
#
#Resize SD function is based on the corresponding function in raspi-config
#The overclocking function is copied from raspi-config
#raspi-config is created by Alex Bradbury <asb@asbradbury.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

changewlanunprotected() {
	SSID=$(dialog --backtitle "$BACKTITLE" --title " $1 " --ok-label Change --inputbox "SSID:" 7 55 $3 3>&1 1>&2 2>&3)
	if [ $? -eq 0 ]; then
		if [ ! -z $SSID ]; then
			eval "$2=\"$SSID\""
			return 1;
		else
			showdialog "$1" "Close" "\n    Please enter your network name"
			changewlanunprotected $1 $2 $3;
		fi
	else
		return 0;
	fi
}

changewlanprotected() {
	VALUES=$(dialog --ok-label "Change" --backtitle "$BACKTITLE" --title " $1 " --form "\n  Press up/down to move between fields" 11 55 0 \
		"SSID:" 1 1 "$4" 1 15 21 64 \
		"Password:" 3 1 "$5" 3 15 21 128 \
		3>&1 1>&2 2>&3);

	if [ $? -ge 1 ]; then
		return 0
	fi

	echo -e "$VALUES" > /tmp/xbian-config-args

	if [ $(cat /tmp/xbian-config-args | wc -l) -lt 2 ]; then
		showdialog "$1" "Close" "\n    Please enter your  network name and password"
		changewlanprotected "$1" "$2" "$3" "$4" "$5" "$6" "$7"
		return 0
	fi

	I=0;
	while read LINE; do
	if [ $I -eq 0 ]; then
		SSID=$LINE;
	elif [ $I -eq 1 ]; then
		PASSWD=$LINE;
	fi
	I=$(($I+1));
	done < /tmp/xbian-config-args;
	rm /tmp/xbian-config-args;

	eval "$2=\"$SSID\"";
	eval "$3=\"$PASSWD\"";
	
	return 1;
}

changewlandhcp() {

	# Read settings from /etc/network/interfaces
	if [ $(cat /etc/wpa_supplicant/wpa_supplicant.conf | grep ssid | wc -l) -gt 0 ]; then
		CWSSID=$(cat /etc/network/interfaces | grep ssid);
		CWPASSWD=$(cat /etc/network/interfaces | grep wpa-psk);
		if [ -z $CWPASSWD ];then
			CWPASSWD=$(cat /etc/network/interfaces | grep wireless-key);
		fi
		CSSID=$(echo -e "$CWSSID" | cut -f 2 -d ' ' | sed -e 's/"//g');
		CPASSWD=$(echo -e "$CWPASSWD" | cut -f 2 -d ' ' | sed -e 's/"//g');
		if [ -z $CPASSWD ]; then
			CMODE=1;
		else
			CMODE=2;
		fi
	fi

	showmenu	"$1" \
			1 "Unprotected" \
			2 "WPA or WPA2" \
			3 "WEP"

	MODE=$RETURN
	case "$MODE" in
		1)
			changewlanunprotected $1 $2 SSID $CSSID;
			if [ $? -eq 0 ]; then
				return 0;
			fi
		;;
		2)
			changewlanprotected "$1" "SSID" "PASSWD" "$CSSID" "$CPASSWD" "PMODE" "$MODE";
			if [ $? -eq 0 ]; then
				return 0;
			fi
		;;
		3)
			changewlanprotected "$1" SSID PASSWD "$CSSID" "$CPASSWD" PMODE "$MODE";
			if [ $? -eq 0 ]; then
				return 0;
			fi
		;;
		*)
			wlan $1
			return 0
		;;
	esac

	if [ $MODE -eq 1 ]; then
		CONFIG+="\nwireless-mode managed\nwireless-essid $SSID"
	elif [ $MODE -eq 2 ];then
		CONFIG+="\nwpa-ssid \"$SSID\"\nwpa-psk \"$PASSWD\""
	else
		CONFIG+="\nwireless-essid $SSID\nwireless-key $PASSWD"
	fi

	sed -i '/iface wlan0/,+10d' /etc/network/interfaces
	sed -i "s/allow-hotplug wlan0/allow-hotplug wlan0\niface wlan0 inet dhcp\n$CONFIG/g" /etc/network/interfaces
	showdialog " $1 " "Close" "\n      WLAN settings updated."
	ASKFORREBOOT=1;

}

changewlanstatic() {

	OLDIFS=$IFS; IFS=$' \t\n';

	# Read IP, netmask and gateway from /etc/network/interfaces
	if [ ! -z "$2" ]; then
		CIP=();
		CSM=();
		CGW=();
		I=0;

		echo -e "$2" > /tmp/xbian-config-args

		while read LINE; do
			if [ $I -gt 15 ]; then
				NS2[$(($I-16))]=$LINE;
			elif [ $I -gt 11 ]; then
				NS1[$(($I-12))]=$LINE;
			elif [ $I -gt 7 ]; then
				CGW[$(($I-8))]=$LINE;
			elif [ $I -gt 3 ]; then
				CSM[$(($I-4))]=$LINE;
			else
				CIP[$I]=$LINE;
			fi
			I=$(($I+1));
		done < /tmp/xbian-config-args;
		rm /tmp/xbian-config-args;
	else
		CONTENT=$(cat /etc/network/interfaces | grep -A6 "^iface wlan0 inet manual");
		CIP=($(echo -e "$CONTENT" | grep address | cut -f 2 -d " " | sed 's/\./\ /g'));
		CSM=($(echo -e "$CONTENT" | grep netmask | cut -f 2 -d " " | sed 's/\./\ /g'));
		CGW=($(echo -e "$CONTENT" | grep gateway | cut -f 2 -d " " | sed 's/\./\ /g'));

		# Read nameservers from /etc/resolv.conf
		NS1=();
		NS2=();
		if [ $(cat /etc/resolv.conf | grep nameserver | wc -l) -gt 0 ]; then
			RNS=($(cat /etc/resolv.conf | grep nameserver | sed 's/nameserver //g' ))
			if [ ${#RNS[@]} -gt 0 ]; then
				NS1=($(echo -e "${RNS[0]}" | sed 's/\./\ /g'));
			fi
			if [ ${#RNS[@]} -gt 1 ]; then
				NS2=($(echo -e "${RNS[1]}" | sed 's/\./\ /g'));
			fi
		fi
	fi

	IP=();
	SM=();
	GW=();
	ONS1=();
	ONS2=();

	# Read settings from /etc/network/interfaces
	if [ $(cat /etc/wpa_supplicant/wpa_supplicant.conf | grep ssid | wc -l) -gt 0 ]; then
		CWSSID=$(cat /etc/network/interfaces | grep ssid);
		CWPASSWD=$(cat /etc/network/interfaces | grep wpa-psk);
		if [ -z $CWPASSWD ];then
			CWPASSWD=$(cat /etc/network/interfaces | grep wireless-key);
		fi
		CSSID=$(echo -e "$CWSSID" | cut -f 2 -d ' ' | sed -e 's/"//g');
		CPASSWD=$(echo -e "$CWPASSWD" | cut -f 2 -d ' ' | sed -e 's/"//g');
		if [ -z $CPASSWD ]; then
			CMODE=1;
		else
			CMODE=2;
		fi
	fi

	showmenu 	"$1" \
			1 "Unprotected" \
			2 "WPA or WPA2" \
			3 "WEP"

	MODE=$RETURN
	case "$MODE" in
		1)
			changewlanunprotected "$1" SSID "$CSSID";
			if [ $? -eq 0 ]; then
				return 0;
			fi
		;;
		2)
			changewlanprotected "$1" SSID PASSWD "$CSSID" "$CPASSWD" "PMODE" "$MODE";
			if [ $? -eq 0 ]; then
				return 0;
			fi
		;;
		3)
			changewlanprotected "$1" SSID PASSWD "$CSSID" "$CPASSWD" "PMODE" "$MODE";
			if [ $? -eq 0 ]; then
				return 0;
			fi
		;;
		*)
			IFS=$OLDIFS;
			wlan "$TITLE"
			return 0;
		;;
	esac

	VALUES=$(dialog --ok-label "Change" --backtitle "$BACKTITLE" --title "$TITLE" --form "\n  Press up/down to move between fields" 19 55 0 \
		"Address:" 1 1 "${CIP[0]}" 1 15 4 3 \
			"." 1 19 "${CIP[1]}" 1 20 4 3 \
			"." 1 24 "${CIP[2]}" 1 25 4 3 \
			"." 1 29 "${CIP[3]}" 1 30 4 3 \
		"Subnet:" 3 1 "${CSM[0]}" 3 15 4 3 \
			"." 3 19 "${CSM[1]}" 3 20 4 3 \
			"." 3 24 "${CSM[2]}" 3 25 4 3 \
			"." 3 29 "${CSM[3]}" 3 30 4 3 \
		"Gateway:" 5 1 "${CGW[0]}" 5 15 4 3 \
			"." 5 19 "${CGW[1]}" 5 20 4 3 \
			"." 5 24 "${CGW[2]}" 5 25 4 3 \
			"." 5 29 "${CGW[3]}" 5 30 4 3 \
		"Nameserver:" 7 1 "${NS1[0]}" 7 15 4 3 \
			"." 7 19 "${NS1[1]}" 7 20 4 3 \
			"." 7 24 "${NS1[2]}" 7 25 4 3 \
			"." 7 29 "${NS1[3]}" 7 30 4 3 \
		"Nameserver:" 9 1 "${NS2[0]}" 9 15 4 3 \
			"." 9 19 "${NS2[1]}" 9 20 4 3 \
			"." 9 24 "${NS2[2]}" 9 25 4 3 \
			"." 9 29 "${NS2[3]}" 9 30 4 3 \
	3>&1 1>&2 2>&3);

	if [ $? -ge 1 ]; then
		wlan "$TITLE"
		return 0;
	fi

	I=0;

	echo -e "$VALUES" > /tmp/xbian-config-args

	while read LINE; do
		if [ $I -gt 15 ]; then
			ONS2[$(($I-16))]=$LINE;
		elif [ $I -gt 11 ]; then
			ONS1[$(($I-12))]=$LINE;
		elif [ $I -gt 7 ]; then
			GW[$(($I-8))]=$LINE;
		elif [ $I -gt 3 ]; then
			SM[$(($I-4))]=$LINE;
		else
			IP[$I]=$LINE;
		fi
		I=$(($I+1));
	done < /tmp/xbian-config-args;
	rm /tmp/xbian-config-args;

	# Check that ip is valid
	if ! case "$(echo ${IP[@]} | sed 's/\ /\./g')" in
		*[!.0-9]* | *.*.*.*.* | *..* | [!0-9]* | *[!0-9] ) false ;;
		*25[6-9]* | *2[6-9][0-9]* | *[3-9][0-9][0-9]* | *[0-9][0-9][0-9][0-9]* ) false ;;
		[!1-9].*.*.* | *.*.*.[!1-9] ) false ;;
		*.*.*.* ) true ;;
		*) false ;;
	esac; then
		showdialog "$TITLE" "Close" "\n        You didn't enter a valid ip address"
		changewlanstatic "$TITLE" "$VALUES";
		exit 0;
	fi

	# Check that netmask is valid
	if ! case "$(echo ${SM[@]} | sed 's/\ /\./g')" in
		255.0.0.0 | 255.255.0.0 | 255.255.255.0 | 255.255.255.255 ) true ;;
		*) false ;;
	esac; then
		showdialog "$1" "Close" "\n       You didn't enter a valid subnet"
		changewlanstatic "$1" "$VALUES";
		exit 0;
	fi

	# Check that gateway is a valid ip
	if ! case "$(echo ${GW[@]} | sed 's/\ /\./g')" in
		*[!.0-9]* | *.*.*.*.* | *..* | [!0-9]* | *[!0-9] ) false ;;
		*25[6-9]* | *2[6-9][0-9]* | *[3-9][0-9][0-9]* | *[0-9][0-9][0-9][0-9]* ) false ;;
		[!1-9].*.*.* | *.*.*.[!1-9] ) false ;;
		*.*.*.* ) true ;;
		*) false ;;
	esac; then
		showdialog "$1" "Close" "\n         You didn't enter a valid gateway"
		changewlanstatic "$1" "$VALUES";
		exit 0;
	fi

	# Check that ns1 is valid, if existing
	if [ ${#ONS1[@]} -gt 0 ]; then
		if ! case "$(echo ${ONS1[@]} | sed 's/\ /\./g')" in
			*[!.0-9]* | *.*.*.*.* | *..* | [!0-9]* | *[!0-9] ) false ;;
			*25[6-9]* | *2[6-9][0-9]* | *[3-9][0-9][0-9]* | *[0-9][0-9][0-9][0-9]* ) false ;;
			[!1-9].*.*.* | *.*.*.[!1-9] ) false ;;
			*.*.*.* ) true ;;
			*) false ;;
		esac; then
			showdialog "$1" "Close" "\n         Invalid address for nameserver 1"
			changewlanstatic "$1" "$VALUES";
			exit 0;
		fi
	fi

	# Check that ns2 is valid, if existing
	if [ ${#ONS2[@]} -gt 0 ]; then
		if ! case "$(echo ${ONS2[@]} | sed 's/\ /\./g')" in
			*[!.0-9]* | *.*.*.*.* | *..* | [!0-9]* | *[!0-9] ) false ;;
			*25[6-9]* | *2[6-9][0-9]* | *[3-9][0-9][0-9]* | *[0-9][0-9][0-9][0-9]* ) false ;;
			[!1-9].*.*.* | *.*.*.[!1-9] ) false ;;
			*.*.*.* ) true ;;
			*) false ;;
		esac; then
			showdialog "$1" "Close" "\n         Invalid address for nameserver 2"
			changewlanstatic "$1" "$VALUES";
			exit 0;
		fi
	fi

	CONFIG="";
	I=0;
	for VALUE in ${IP[@]}; do
		CONFIG+="$VALUE";
		if [ $I -lt 3 ]; then
			CONFIG+=".";
		else
			CONFIG+="\nnetwork ";
		fi
		I=$(($I+1));
	done;
	I=0;
	for VALUE in ${IP[@]}; do
		if [ $I -eq 3 ]; then
			CONFIG+=0;
		else
			CONFIG+=$VALUE;
		fi
		if [ $I -lt 3 ]; then
			CONFIG+=".";
		else
			CONFIG+="\nnetmask ";
		fi
		I=$(($I+1));
	done;
	I=0;
	for VALUE in ${SM[@]}; do
		CONFIG+=$VALUE;
		if [ $I -lt 3 ]; then
			CONFIG+=".";
		else
			CONFIG+="\nbroadcast ";
		fi
		I=$(($I+1));
	done;
	I=0;
	for VALUE in ${IP[@]}; do
		if [ $I -eq 3 ]; then
			CONFIG+=255;
		else
			CONFIG+=$VALUE;
		fi
		if [ $I -lt 3 ]; then
			CONFIG+=".";
		else
			CONFIG+="\ngateway ";
		fi
		I=$(($I+1));
	done;
	I=0;
	for VALUE in ${GW[@]}; do
		CONFIG+=$VALUE;
		if [ $I -lt 3 ]; then
			CONFIG+=".";
		fi
		I=$(($I+1));
	done;

	if [ $MODE -eq 1 ]; then
		CONFIG+="\nwireless-mode managed\nwireless-essid $SSID"
	elif [ $MODE -eq 2 ];then
		CONFIG+="\nwpa-ssid \"$SSID\"\nwpa-psk \"$PASSWD\""
	else
		CONFIG+="\nwireless-essid $SSID\nwireless-key $PASSWD"
	fi

	# Modify /etc/resolv.conf
	eval "sed -i '/nameserver/d' /etc/resolv.conf"
	NNS=0;
	if [ ${#ONS1[@]} -eq 4 ]; then
		I=0;
		NSLINE="";
		for VALUE in ${ONS1[@]}; do
			NSLINE+=$VALUE;
			if [ $I -lt 3 ]; then
				NSLINE+=".";
			fi
			I=$(($I+1));
		done;
		echo -e "nameserver $NSLINE" >> /etc/resolv.conf
		NNS=$(($NNS+1))
	fi
	if [ ${#ONS2[@]} -eq 4 ]; then
		I=0;
		NSLINE="";
		for VALUE in ${ONS2[@]}; do
			NSLINE+=$VALUE;
			if [ $I -lt 3 ]; then
				NSLINE+=".";
			fi
			I=$(($I+1));
		done;
		echo -e "nameserver $NSLINE" >> /etc/resolv.conf
		NNS=$(($NNS+1))
	fi

	sed -i '/wpa-roam/d' /etc/network/interfaces
	sed -i '/iface wlan0/,+10d' /etc/network/interfaces
	sed -i "s/allow-hotplug wlan0/allow-hotplug wlan0\niface wlan0 inet manual\naddress $CONFIG/g" /etc/network/interfaces
	showdialog "$1" "Close" "\n          WLAN static settings changed."

	IFS=$OLDIFS;

	ASKFORREBOOT=1;
}

function wlan() {
	MODE=$(dialog --backtitle "$BACKTITLE" --title "$1" --ok-label Select --cancel-label Return --menu '' 8 55 2 1 "DHCP" 2 "Static" 3>&1 1>&2 2>&3)
	case "$MODE" in
		1)
			changewlandhcp "$1";
		;;
		2)
			changewlanstatic "$1";
		;;
	esac
}

