#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Cambiar tamaño SD"
_DESC="Expandir particion de superusuario SD"
_SDCONFIRM="¿Estas seguro de que quieres cambiar el tamaño en la tarjeta SD?"
_SDRESIZENOTNEEDED="En esta tarjeta ya ha sido cambiado el tamaño de la particion. Abortando."
_SDREBOOT="La particion de superusuario ha cambiado de tamaño. El sistema de archivos se extenderá en el siguiente reinicio"
_SDERROR="Ha ocurrido un error. Es posible que el sistema no pueda arrancar. Por favor haga una copia de seguridad de sus archivos antes de reiniciar."