#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Redimensionner SD"
_DESC="Etendre la partion root a la taille SD"
_SDCONFIRM="Etes vous sur de vouloir redimensionner votre carte SD?"
_SDRESIZENOTNEEDED="Cette carte a déja été redimensionné, annulé."
_SDREBOOT="La partition a été redimensionnée. Le systeme de fichier sera ajusté au prochain reboot."
_SDERROR="Une erreur est survenue. Il est possible que le système ne redémarre pas. Faites une sauvegarde de vos fichiers avant de redémarrer."