#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Vergroot SD"
_DESC="Gebruik de volledige SD kaart"
_SDCONFIRM="Weet u zeker dat u uw SD kaart wilt vergroten?"
_SDRESIZENOTNEEDED="De SD kaart is al volledig in gebruik. Afbreken."
_SDREBOOT="De root partitie is vergroot. Het bestandssysteem zal worden vergroot tijdens de volgende herstart."
_SDERROR="Er is een fout opgetreden. Het is mogelijk dat het systeem onbruikbaar zal worden na een herstart. Maak eerst een backup voordat het systeem zal worden herstart."