#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Expanzia SD karty"
_DESC="Expanduj root na celú SD kartu"
_SDCONFIRM="Si si istý, že chceš expandovať systém na celú SD kartu?"
_SDRESIZENOTNEEDED="Táto karta už bola expandovaná. Operácia ukončená."
_SDREBOOT="Partícia root bola expandovaná. Systém bude aktualizovaný a rozšírený pri ďalšom reštarte."
_SDERROR="Vyskytla sa chyba. Môže sa stať že systém bude poškodený a nenaštartuje. Prosím zálohuj všetky dáta pred reštartom."