#!/bin/bash

if [ $1 == "remove" ]; then
	
	/etc/init.d/xbmc stop 1>/dev/null 2>/dev/null >/dev/null
	
	if [ -f /etc/init.d/xbmc ]; then
		rm /etc/init.d/xbmc;
	fi
	
	if [ -f /usr/local/bin/xbmc ]; then
		rm /usr/local/bin/xbmc;
	fi
	
	if [ -f /usr/local/bin/xbmc-standalone ]; then
		rm /usr/local/bin/xbmc-standalone;
	fi
	
	if [ -d /usr/local/lib/xbmc ]; then
		rm -r /usr/local/lib/xbmc;
	fi
	
	if [ -d /usr/local/share/xbmc ]; then
		rm -r /usr/local/share/xbmc;
	fi
	
	if [ -f /usr/local/share/xsessions/XBMC.desktop ]; then 
		rm /usr/local/share/xsessions/XBMC.desktop; 
	fi;
	
	if [ -f /usr/local/share/icons/hicolor/256x256/apps/xbmc.png ]; then 
		rm /usr/local/share/icons/hicolor/256x256/apps/xbmc.png; 
	fi;
	
	if [ -f /usr/local/share/icons/hicolor/48x48/apps/xbmc.png ]; then 
		rm /usr/local/share/icons/hicolor/48x48/apps/xbmc.png; 
	fi;		
	
fi