#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# Shows the dialog in which users can enter the new password
# Returns
#  $? [Integer]
#  - 1: Change
#  - 0: Cancel
function showXbianPassInputDlg() {
	showPassDlg "$_XBIANPASS"
}

# Shows xbianpass successfully changed dialog
function showXbianPassSuccessDlg() {
	wrapTxtFn "$_XBIANPASSCHANGED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
	return $?;
}

# Shows xbianpass passwords didn't match dialog
function showXbianPassNoMatchDlg() {
	wrapTxtFn "$_XBIANPASSNOMATCH" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT $DEFAULTWIDTH $_RETRY
	return $?;
}

# Shows xbianpass there where empty fields dialog
function showXbianPassEmptyFieldsDlg() {
	wrapTxtFn "$_XBIANPASSEMPTYFIELDS" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT $DEFAULTWIDTH $_RETRY
	return $?;
}