#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|          Global variables          |
#|------------------------------------|

# The arguments this module accepts
ARGUMENTS=(update);

#|------------------------------------|
#|          Include files             |
#|------------------------------------|

source $BASEPATH/modules/xbianpass/functions
source $BASEPATH/modules/xbianpass/dialogs

#|------------------------------------|
#|           Main program             |
#|------------------------------------|

# Executes the GUI version of this module
function showGUIFn() {
	showXbianPassInputDlg;
	CODE=$?
	if [ $CODE -eq 0 ]; then
		VALUES=($VALUES);
		if [ ${#VALUES[@]} -eq 2 ]; then 
			if [ ! -z ${VALUES[0]} ] && [ ! -z ${VALUES[1]} ] && [ "${VALUES[0]}" == "${VALUES[1]}" ]; then 
				setXbianPassFn ${VALUES[0]}
				if [ $? -eq 1 ]; then
					showXbianPassSuccessDlg;
				else
					showErrorDlg;
				fi
			else
				showXbianPassNoMatchDlg
				showGUIFn;
			fi
		else
			showXbianPassEmptyFieldsDlg;
			showGUIFn;
		fi
	fi 
}

# Executes the command line version of this module
#  $1 Argument [String]
#  $2 Password [String]
# Returns
#  *Update [Integer]
#  - 1: Success
#  - 0: Failed
function showCMDFn() {
	case $1 in
		"update")
			shift;
			if [ $# -eq 1 ]; then
				setXbianPassFn $1;
				echo $?;
			else
				echo 0;
			fi
		;;
	esac
}