#!/bin/bash

if [ $1 == "configure" ]; then
	echo "3) Fixing firmware permission"
	
	chmod +x /opt/vc/bin/*
	chmod +x /opt/vc/sbin/*
	
	echo "4) Changing memory split"
	
	if [ $(cat /boot/config.txt | grep "gpu_mem_256=128" | wc -l) -eq 1 ];	then
		sed -i 's/gpu_mem_256=128/gpu_mem_256=100/g' /boot/config.txt
		if [ $(cat /boot/config.txt | grep "gpu_mem_256=100" | wc -l) -eq 1 ];	then
			echo "Success: changed RPi 256 memsplit" >> /home/xbian/update.log; 
		else
			echo "Error: failed to set RPi 256 memsplit" >> /home/xbian/update.log; 
		fi
	else
		echo "Notice: RPi 256 memsplit already set" >> /home/xbian/update.log; 
	fi
	
	if [ $(cat /boot/config.txt | grep "gpu_mem_512=384" | wc -l) -eq 1 ];	then
		sed -i 's/gpu_mem_512=384/gpu_mem_512=100/g' /boot/config.txt
		if [ $(cat /boot/config.txt | grep "gpu_mem_512=100" | wc -l) -eq 1 ];	then
			echo "Success: changed RPi 512 memsplit" >> /home/xbian/update.log; 
		else
			echo "Error: failed to set RPi 512 memsplit" >> /home/xbian/update.log;
		fi
	else
		echo "Notice: RPi 512 memsplit already set" >> /home/xbian/update.log; 
	fi
	
	echo "5) Apply patches";
	
	if [ $(cat /etc/motd 2>/dev/null | grep rpi-update | wc -l) -eq 0 ]; then
	
cat <<\EOF > /etc/motd
------------------------------------------------------------------
     Y88b d88P  888888b.   8888888        d8888 888b    888
      Y88o88P   888  .88P    888        d88P888 88888b  888
       Y888P    8888888K.    888       d88P 888 888Y88b 888
       d888b    888  "Y88b   888      d88P  888 888 Y88b888
     d88P Y88b  888   d88P   888    d8888888888 888   Y8888
    d88P   Y88b 8888888P"  8888888 d88P     888 888    Y888 
------------------------------------------------------------------
XBian v1.0 - XBMC on the Raspbery Pi, Bleeding Edge, 2012
Find up as: http://www.xbian.org / https://github.com/Koenkk/xbian

XBian and all it's packages are distributed as free software; the 
exact distribution terms for each program are described in the 
individual files in /usr/share/doc/*/copyright. XBian itself is 
distributed under the GNU GENERAL PUBLIC LICENSE v3. A full copy 
of this license can be found under /etc/xbian_copying

XBian v1.0 comes with ABSOLUTELY NO WARRANTY, to the extent 
permitted by applicable law.

!Importance notice!
rpi-update breaks core features of xbian, use it at you're own risk 

EOF
	
		if [ $(cat /etc/motd | grep rpi-update | wc -l) -eq 1 ]; then
			echo "Success: applied 001-motd.patch" >> /home/xbian/update.log; 
		fi
	else
		echo "Notice: 001-motd.patch already applied" >> /home/xbian/update.log; 
	fi
	
cat <<\EOF > /tmp/002-hideoutput.patch
--- a/etc/profile.d/hideoutput.sh
+++ b/etc/profile.d/hideoutput.sh
@@ -17,8 +17,11 @@
 #You should have received a copy of the GNU General Public License along 
 #with Xbian. If not, see <http://www.gnu.org/licenses/>
 #
-if [[ -z $SSH_CONNECTION && $(who am i | grep -wo "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | wc -l) -eq 0 && "$(who am i | awk '{print $1}')" == "$(id -urn)" && "$TERM" != "screen" && ! -n "$TMUX" ]]; then
-        clear
+if [[ $(who am i | awk '{print $2}') == "tty1" ]]; then
+	clear
 	export PS1="\e[40;30m";
 	echo -e '\e[40;30m';
+else
+	export PS1="\[\e[40;0m\]\u@\h:\w# "
+	echo -e '\e[40;0m';
 fi
EOF

	patch --dry-run /etc/profile.d/hideoutput.sh < /tmp/002-hideoutput.patch 2>/dev/null >/dev/null; 
	if [ $? == 0 ]; then 
		patch /etc/profile.d/hideoutput.sh < /tmp/002-hideoutput.patch 2>/dev/null >/dev/null; 
		echo "Success: applied 002-hideoutput.patch" >> /home/xbian/update.log; 
	else 
		echo "Notice: 002-hideoutput.patch already applied" >> /home/xbian/update.log; 
	fi;
	
cat <<\EOF > /tmp/003-xbian-config.patch
--- a/etc/profile.d/xbian-config.sh
+++ b/etc/profile.d/xbian-config.sh
@@ -17,7 +17,7 @@
 #You should have received a copy of the GNU General Public License along
 #with XBian. If not, see <http://www.gnu.org/licenses/>
 #
-if ! [[ -z $SSH_CONNECTION && $(who am i | grep -wo "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | wc -l) -eq 0 &&  "$TERM" != "screen"  && ! -n "$TMUX" ]]; then
+if ! [[ -z $SSH_CONNECTION && $(who am i | awk '{print $2}') == "tty1" && $(who am i | grep -wo "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | wc -l) -eq 0 &&  "$TERM" != "screen"  && ! -n "$TMUX" ]]; then
         if [ $(id -u) -eq 1001 ]; then
                 sudo xbian-config
         fi
EOF

	patch --dry-run /etc/profile.d/xbian-config.sh < /tmp/003-xbian-config.patch 2>/dev/null >/dev/null; 
	if [ $? == 0 ]; then 
		patch /etc/profile.d/xbian-config.sh < /tmp/003-xbian-config.patch 2>/dev/null >/dev/null; 
		echo "Success: applied 003-xbian-config.patch" >> /home/xbian/update.log; 
	else 
		echo "Notice: 003-xbian-config.patch already applied" >> /home/xbian/update.log; 
	fi;

cat <<\EOF > /tmp/004-usbmount.patch
--- a/etc/usbmount/usbmount.conf
+++ b/etc/usbmount/usbmount.conf
@@ -46,7 +46,7 @@
 # For example, "-fstype=vfat,gid=floppy,dmask=0007,fmask=0117" would add
 # the options "gid=floppy,dmask=0007,fmask=0117" when a vfat filesystem
 # is mounted.
-FS_MOUNTOPTIONS=""
+FS_MOUNTOPTIONS="dmask=0777,fmask=0777"
 
 # If set to "yes", more information will be logged via the syslog
 # facility.
EOF

	patch --dry-run /etc/usbmount/usbmount.conf < /tmp/004-usbmount.patch 2>/dev/null >/dev/null; 
	if [ $? == 0 ]; then 
		patch /etc/usbmount/usbmount.conf < /tmp/004-usbmount.patch 2>/dev/null >/dev/null; 
		echo "Success: applied 004-usbmount.patch" >> /home/xbian/update.log; 
	else 
		echo "Notice: 004-usbmount.patch already applied" >> /home/xbian/update.log; 
	fi;
	
cat <<\EOF > /tmp/005-xbian_version.patch
--- a/etc/xbian_version
+++ b/etc/xbian_version
@@ -1 +1 @@
-1.0a2
+1.0a3
EOF

	patch --dry-run /etc/xbian_version < /tmp/005-xbian_version.patch 2>/dev/null >/dev/null; 
	if [ $? == 0 ]; then 
		patch /etc/xbian_version < /tmp/005-xbian_version.patch 2>/dev/null >/dev/null; 
		echo "Success: applied 005-xbian_version.patch" >> /home/xbian/update.log; 
	else
		echo "Notice: 005-xbian_version.patch already applied" >> /home/xbian/update.log; 
	fi;
	
	echo "6) Updating XBMC advanced settings"
	
	if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "fanartheight" | wc -l) -eq 1 ];	then
		sed -i 's/fanartheight/fanartres/g' /home/xbian/.xbmc/userdata/advancedsettings.xml
		if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "fanartres" | wc -l) -eq 1 ];	then
			echo "Success: changed fanartheight to fanartres" >> /home/xbian/update.log; 
		else
			echo "Error: failed to change fanartheight to fanartres" >> /home/xbian/update.log; 
		fi
	else
		echo "Notice: already changed fanartheight to fanartres" >> /home/xbian/update.log; 
	fi
	
	if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "thumbsize" | wc -l) -eq 1 ];	then
		sed -i 's/thumbsize/thumbres/g' /home/xbian/.xbmc/userdata/advancedsettings.xml
		if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "thumbres" | wc -l) -eq 1 ];	then
			echo "Success: changed thumbsize to thumbres" >> /home/xbian/update.log; 
		else
			echo "Error: failed to change thumbsize to thumbres" >> /home/xbian/update.log; 
		fi
	else
		echo "Notice: already changed thumbsize to thumbres" >> /home/xbian/update.log; 
	fi
	
	if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "algorithmdirtyregions" | wc -l) -eq 1 ];	then
		sed -i '/<algorithmdirtyregions>3<\/algorithmdirtyregions>/d' /home/xbian/.xbmc/userdata/advancedsettings.xml
		if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "algorithmdirtyregions" | wc -l) -eq 0 ];	then
			echo "Success: removed algorithmdirtyregions" >> /home/xbian/update.log; 
		else
			echo "Error: failed to remove algorithmdirtyregions" >> /home/xbian/update.log;
		fi 
	else
		echo "Notice: already removed algorithmdirtyregions" >> /home/xbian/update.log; 
	fi
	
	if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "nofliptimeout" | wc -l) -eq 1 ];	then
		sed -i '/<nofliptimeout>0<\/nofliptimeout>/d' /home/xbian/.xbmc/userdata/advancedsettings.xml
		if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep "nofliptimeout" | wc -l) -eq 0 ];	then
			echo "Success: removed nofliptimeout" >> /home/xbian/update.log; 
		else
			echo "Error: failed to remove nofliptimeout" >> /home/xbian/update.log; 
		fi
	else
		echo "Notice: already removed nofliptimeout" >> /home/xbian/update.log; 
	fi
	
	if [ ! -z $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep -A 1 '<gui>' | sed -e ':a;N;$!ba;s/\n//g' -e 's/\ *//g') ]; then
		if [ $(cat /home/xbian/.xbmc/userdata/advancedsettings.xml | grep -A 1 '<gui>' | sed -e ':a;N;$!ba;s/\n//g' -e 's/\ *//g') == "<gui></gui>" ]; then
			sed -i '/<gui>/d' /home/xbian/.xbmc/userdata/advancedsettings.xml
			sed -i '/<\/gui>/d' /home/xbian/.xbmc/userdata/advancedsettings.xml
		fi
	fi

	if [ ! -f /etc/apt/apt.conf.d/10AptTimeout ]; then
cat <<\EOF > /etc/apt/apt.conf.d/10AptTimeout
Acquire::http::Timeout "10";
EOF
	fi
	
	echo "7) Make kernel 3.6.7 the default"
	cp /boot/kernel3_6_7.img /boot/kernel.img

	echo "8) Starting XBMC";
	/etc/init.d/xbmc start;
	
	echo "---UPDATE LOG---"
	cat "/home/xbian/update.log"
	
fi
