#!/bin/bash

if [ $1 == "install" ]; then

	if [ $(dpkg-query -W -f='${Version}\n' "xbian-update") != "1.0-0.2" ]; then
		echo "!-------------------------------------------------!"
		echo "!                                                 !"
		echo "! Please install this update on XBian 1.0 Alpha 2 !"
		echo "!                                                 !"
		echo "!-------------------------------------------------!"
		exit 1;
	fi

fi

if [ $1 == "upgrade" ]; then

	if [ $(dpkg-query -W -f='${Version}\n' "xbian-update") != "1.0-0.3" -a $(dpkg-query -W -f='${Version}\n' "xbian-update") != "1.0-0.2" ]; then
		echo "!-------------------------------------------------!"
		echo "!                                                 !"
		echo "! Please install this update on XBian 1.0 Alpha 2 !"
		echo "!    or use it to reinstall XBian 1.0 Alpha 3     !"
		echo "!                                                 !"
		echo "!-------------------------------------------------!"
		exit 1;
	fi

fi

if [ $1 == "install" -o $1 == "upgrade" ]; then

	echo "1) Stopping XBMC";
	/etc/init.d/xbmc stop 1>/dev/null 2>/dev/null >/dev/null

	if [ -f /home/xbian/update.log ]; then
		rm /home/xbian/update.log;
	fi 	
	
	if [ ! -d "/usr/local/include/libcec" ]; then
		mkdir -p "/usr/local/include/libcec";
	fi

	if [ ! -d "/usr/local/lib" ]; then
		mkdir -p "/usr/local/lib";
	fi
	
	echo "2) Installing new files" 
fi