#!/bin/bash

if [[ $1 == "configure" ]]; then
	
	if [ -f "/usr/local/share/xsessions/XBMC.desktop" ]; then 
		rm /usr/local/share/xsessions/XBMC.desktop; 
	fi;
	
	if [ -f "/usr/local/share/icons/hicolor/256x256/apps/xbmc.png" ]; then 
		rm /usr/local/share/icons/hicolor/256x256/apps/xbmc.png; 
	fi;
	
	if [ -f "/usr/local/share/icons/hicolor/48x48/apps/xbmc.png" ]; then 
		rm /usr/local/share/icons/hicolor/48x48/apps/xbmc.png; 
	fi;	

	if [ -f "/usr/local/bin/xbmc" ]; then 
		rm /usr/local/bin/xbmc;
	fi;
	
	if [ -f "/usr/local/bin/xbmc-standalone" ]; then 
		rm /usr/local/bin/xbmc-standalone;
	fi;	
	
	/etc/init.d/xbmc start 1>/dev/null 2>/dev/null >/dev/null

fi