#!/bin/bash

if [ $1 == "remove" ]; then
	
	/etc/init.d/xbmc stop 1>/dev/null 2>/dev/null >/dev/null
	
	if [ -f /etc/init.d/xbmc ]; then
		rm /etc/init.d/xbmc;
	fi
	
	if [ -d /usr/local/lib/xbmc ]; then
		rm -r /usr/local/lib/xbmc;
	fi
	
	if [ -d /usr/local/share/xbmc ]; then
		rm -r /usr/local/share/xbmc;
	fi	
	
fi