#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Informationen"
_DESC="Allgemeine Informationen zum Tool"
_INFORMATION="XBian ist eine freie Open-Source Media Anwendung für den Raspberry Pi und kann über http://www.xbian.org heruntergeladen werden. Unser Slogan ist \"XBMC on Raspberry Pi, bleeding edge\" und wir möchten die schnellste und beste Mediacenter Anwendung für den Raspberry Pi bereitstellen. Jeder kann helfen XBian weiter zu verbessern! Für weitere Fragen, Meinungen, Vorschläge oder Supportanfragen gehe bitte auf unsere Homepage und nutze das Forum, das Wiki oder die FAQ-Liste. Viel Spaß!"