#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Información"
_DESC="Información sobre esta herramienta"
_INFORMATION="XBian es un software de código abierto, gratuito, que provee al Rapberry Pi de una distribución que funcione como mediacenter y puede ser descargado desde http://www.xbian.org. Nuestro eslogan es \"XBMC en Raspberry Pi, a la vanguardia\", centrándonos en desarrollar el mediacenter más rápido para Raspberry Pi. Creemos que todo el mundo puede ayudar a hacer XBian mejor. Por favor visita nuestra página web para apoyarnos y si tienes alguna sugerencia, deseo o contribución, por favor ¡compártela con nosotros!"