#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Information"
_DESC="Information à propos de cet outil"
_INFORMATION="XBian est un media center Open Source et gratuit pour le Raspberry Pi. Il peut être télécharger à l'adresse http://www.xbian.org. Notre slogan est \"XBMC on Raspberry Pi, bleeding edge\", notre objectif étant de délivrer un media center rapide et complet pour le Raspberry Pi. Nous pensons que tout le monde peut rendre XBian meilleur. Visitez Notre site web pour tout support. Si vous avez des suggestions, souhaits, ou contribution, partagez les avec nous!"