#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Informácia"
_DESC="Informácia o tejto aplikácii"
_INFORMATION="XBian je voľne šíriteľný, bezplatný \"Open Source\" média centrum softvér pre Raspberry Pi a je dostupný na prebratie z http://www.xbian.org. Náš slogan je \"XBMC na Raspberry Pi, drsne dobrý\" pretože naším cieľom je poskytnúť najrýchlejšie média centrum pre Raspberry Pi. Taktiež veríme, že každý môže pomôcť urobiť XBian ešte lepším. Prosím, navštívte našu stránku kde nájdete podporu a taktiež môžete písať návrhy, priania a prśpevky. Prosím neváhajte sa podeliť o čokoľvek!"