#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>
#

# XBMC language array
declare -A LANGARRAY
LANGARRAY[Dutch]=nl
LANGARRAY[English]=en
LANGARRAY[French]=fr
LANGARRAY[Slovak]=sk
LANGARRAY[Spanish]=es
LANGARRAY[German]=de
LANGARRAY[Danish]=dk
LANGARRAY[Russian]=ru

# Language translations
_DUTCH="Nederlands"
_ENGLISH="English"
_FRENCH="Français"
_SLOVAK="Slovenčina"
_SPANISH="Español"
_GERMAN="Deutsch"
_DANISH="Dansk"
_RUSSIAN="Русский"

function getLanguageFn() {
	# Get XBMC language setting
	if [ -f $BASEPATH"/config/xbconfig" ]; then
		USERLANG=$(cat $BASEPATH"/config/xbconfig" | grep language | cut -f2 -d":");
	else
		USERLANG="";
	fi
	XBMCLANG=$(cat /home/xbian/.xbmc/userdata/guisettings.xml | sed '/<language>/!d;s//\n/;s/[^\n]*\n//;:a;$!{/<\/language/!N;//!ba};y/\n/ /;s/<\/language>/\n/;P;D' | sed -ne 's/\([A-Za-z]\{1,\}\)\([\ ](.*\|.*\)/\1/p')

	# Prefered language of xbian-config
	if [ -z $USERLANG ]; then
		LANGUAGE=${LANGARRAY[$XBMCLANG]};
	else
		LANGUAGE=${LANGARRAY[$USERLANG]};
	fi
}