#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="VC1"
_DESC="Управление лицензией VC1"
_VC1LICENSE="Лицензия VC1"
_VC1INSERTED="Лицензия VC1 успешно добавлена";
_VC1DELETED="Лицензия VC1 успешно удалена";
_VC1UPDATED="Лицензия VC1 успешно обновлена";
_VC1LICENSEINVALID="Лицензия VC1 не распознана"