#!/bin/bash

if [ $1 == "remove" ]; then

	if [ -d /opt/linux3.2.27 ]; then
		rm -r /opt/linux3.2.27
	fi

	if [ -L /lib/modules/3.2.27/source ]; then
		rm /lib/modules/3.2.27/source
	fi
	
	if [ -L /lib/modules/3.2.27/build ]; then
		rm /lib/modules/3.2.27/build
	fi
	
	if [ -L /lib/modules/3.2.27+/source ]; then
		rm /lib/modules/3.2.27+/source
	fi
	
	if [ -L /lib/modules/3.2.27+/build ]; then
		rm /lib/modules/3.2.27+/build
	fi	
	
fi

if [ $1 == "upgrade" -o $1 == "install" ]; then

	if [ -d /opt/linux3.2.27 ]; then
		rm -r /opt/linux3.2.27
	fi

	if [ -L /lib/modules/3.2.27/source ]; then
		rm /lib/modules/3.2.27/source
	fi
	
	if [ -L /lib/modules/3.2.27/build ]; then
		rm /lib/modules/3.2.27/build
	fi

	if [ -L /lib/modules/3.2.27+/source ]; then
		rm /lib/modules/3.2.27+/source
	fi
	
	if [ -L /lib/modules/3.2.27+/build ]; then
		rm /lib/modules/3.2.27+/build
	fi
fi