#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function showXBMCSettingsDlg() {
	MENU=();
	MENU+=(1,"\Zn"$_XBMCGUIRES);
	MENU+=(2,"\Zn"$_XBMCWEBSERVER);
	createTableFn "menu"\
	"#,\Zb"$_XBMCACTIONS\
	"${MENU[@]}";

	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+11))
	showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} 10
}

function showXBMCGUIResDlg() {
	MENU=();
	I=0;
	for RES in ${GUIRES[@]}; do
		I=$(($I+1));
		MENU+=($I",\Zn"$RES);
	done
	createTableFn "menu"\
	"#,\Zb"$_XBMCGUIRES\
	"${MENU[@]}";

	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+11))
	showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} 12
}

function showXBMCWebserverDlg() {
	wrapTxtFn "$_XBMCWEBSERVERENABLEDISABLE" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showConfirmDlg "$ALIGNEDTXT" $HEIGHT 55 "$_ENABLE" "$_DISABLE"
	return $?;
}

function showXBMCWebserverSuccessEnabledDlg() {
	wrapTxtFn "$_XBMCWEBSERVERSUCCESSENABLED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}

function showXBMCWebserverSuccessDisabledDlg() {
	wrapTxtFn "$_XBMCWEBSERVERSUCCESSDISABLED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}

function showXBMCWebserverFailedEnableDlg() {
	wrapTxtFn "$_XBMCWEBSERVERFAILEDENABLED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;	
}

function showXBMCWebserverFailedDisableDlg() {
	wrapTxtFn "$_XBMCWEBSERVERFAILEDDISABLED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;	
}

function showXBMCGUIResSuccessDDlg() {
	wrapTxtFn "$_XBMCGUIRESSUCCESS" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}

function showXBMCGUIResFailedDlg() {
	wrapTxtFn "$_XBMCGUIRESFAILED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT;
}