#!/bin/bash
#
#Copyright 2012 Koenkk <development@xbian.org>
#
#This file is part of Xbian - XBMC on the Raspberry Pi.
#
#Xbian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#Xbian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with Xbian. If not, see <http://www.gnu.org/licenses/>
#
### BEGIN INIT INFO
# Provides:          createswap
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Creates a 128 MB swapfile
# Description:
#
### END INIT INFO

NAME=createswap
DESC="Creates a 128 MB swapfile"
VERBOSE=no
SCRIPTNAME=/etc/init.d/createswap
DEBUG=0;

case "$1" in
  start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" ""
echo '
 _______  ______    _______  _______  _______  ___   __    _  _______    _______  _     _  _______  _______ 
|       ||    _ |  |       ||   _   ||       ||   | |  |  | ||       |  |       || | _ | ||   _   ||       |
|       ||   | ||  |    ___||  |_|  ||_     _||   | |   |_| ||    ___|  |  _____|| || || ||  |_|  ||    _  |
|       ||   |_||_ |   |___ |       |  |   |  |   | |       ||   | __   | |_____ |       ||       ||   |_| |
|      _||    __  ||    ___||       |  |   |  |   | |  _    ||   ||  |  |_____  ||       ||       ||    ___|
|     |_ |   |  | ||   |___ |   _   |  |   |  |   | | | |   ||   |_| |   _____| ||   _   ||   _   ||   |    
|_______||___|  |_||_______||__| |__|  |___|  |___| |_|  |__||_______|  |_______||__| |__||__| |__||___|    ';
	dd if=/dev/zero of=/var/swapfile bs=1024 count=128000 &>/dev/null
	mkswap /var/swapfile &>/dev/null
	swapon /var/swapfile &>/dev/null
	echo '/var/swapfile swap swap defaults 0 0' >> /etc/fstab 
	update-rc.d createswap remove >/dev/null
	rm /etc/init.d/createswap >/dev/null

        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  stop)
	sync;
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop}" >&2
        exit 3
        ;;
esac

:
