#!/bin/bash
#
#Copyright 2012 Koenkk <development@xbian.org>
#
#This file is part of Xbian - XBMC on the Raspberry Pi.
#
#Xbian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#Xbian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with Xbian. If not, see <http://www.gnu.org/licenses/>
#
### BEGIN INIT INFO
# Provides:          createswap
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Creates a 128 MB swapfile
# Description:
#
### END INIT INFO

NAME=createswap
DESC="Creates a 128 MB swapfile"
VERBOSE=no
SCRIPTNAME=/etc/init.d/createswap
DEBUG=0;

case "$1" in
  start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" ""
echo '
       d8888 8888888b.  8888888b.     .d8888b.  888       888        d8888 8888888b.  
      d88888 888  "Y88b 888  "Y88b   d88P  Y88b 888   o   888       d88888 888   Y88b 
     d88P888 888    888 888    888   Y88b.      888  d8b  888      d88P888 888    888 
    d88P 888 888    888 888    888    "Y888b.   888 d888b 888     d88P 888 888   d88P 
   d88P  888 888    888 888    888       "Y88b. 888d88888b888    d88P  888 8888888P"  
  d88P   888 888    888 888    888         "888 88888P Y88888   d88P   888 888        
 d8888888888 888  .d88P 888  .d88P   Y88b  d88P 8888P   Y8888  d8888888888 888        
d88P     888 8888888P"  8888888P"     "Y8888P"  888P     Y888 d88P     888 888';
	dd if=/dev/zero of=/var/swapfile bs=1024 count=128000 &>/dev/null
	mkswap /var/swapfile &>/dev/null
	swapon /var/swapfile &>/dev/null
	echo -e '/var/swapfile\t\t\t\tswap\t\tswap\tdefaults\t\t\t0\t0' >> /etc/fstab 
	update-rc.d createswap remove >/dev/null
	rm /etc/init.d/createswap >/dev/null

        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  stop)
	sync;
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop}" >&2
        exit 3
        ;;
esac

:
