#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of Xbian - XBMC on the Raspberry Pi.
#
#Xbian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#Xbian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with Xbian. If not, see <http://www.gnu.org/licenses/>
#
### BEGIN INIT INFO
# Provides:          firstrun
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Resize SD card on first boot
# Description:
#
### END INIT INFO

NAME=firstrun
DESC="Execute various commands on first boot"
VERBOSE=no
SCRIPTNAME=/etc/init.d/firstrun

function showyesno() {
	return 0;
}
function showdialog() {
        echo -e "\n\n$(echo -e "$3" | sed ':a;N;$!ba;s/\n/ /g' | sed 's/ *$//g' | sed 's/^ *//g')\n\n";
}

DEBUG=0;

source /usr/local/include/xbian-config/scripts/resizesd;

case "$1" in
  start)
	/usr/bin/splash --infinitebar --msgtxt='First-time setup...'
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" ""
echo '
8888888b.  8888888888  .d8888b.  8888888 8888888888P 8888888 888b    888  .d8888b.
888   Y88b 888        d88P  Y88b   888         d88P    888   8888b   888 d88P  Y88b
888    888 888        Y88b.        888        d88P     888   88888b  888 888    888
888   d88P 8888888     "Y888b.     888       d88P      888   888Y88b 888 888
8888888P"  888            "Y88b.   888      d88P       888   888 Y88b888 888  88888
888 T88b   888              "888   888     d88P        888   888  Y88888 888    888
888  T88b  888        Y88b  d88P   888    d88P         888   888   Y8888 Y88b  d88P
888   T88b 8888888888  "Y8888P"  8888888 d8888888888 8888888 888    Y888  "Y8888P88';
	resizesd >/dev/null
	update-rc.d firstrun remove >/dev/null
	rm /etc/init.d/firstrun >/dev/null
	update-rc.d createswap defaults
echo '
8888888b.  8888888888 888888b.    .d88888b.   .d88888b.  88888888888
888   Y88b 888        888  "88b  d88P" "Y88b d88P" "Y88b     888
888    888 888        888  .88P  888     888 888     888     888
888   d88P 8888888    8888888K.  888     888 888     888     888
8888888P"  888        888  "Y88b 888     888 888     888     888
888 T88b   888        888    888 888     888 888     888     888
888  T88b  888        888   d88P Y88b. .d88P Y88b. .d88P     888
888   T88b 8888888888 8888888P"   "Y88888P"   "Y88888P"      888';
	/usr/bin/splash --msgtxt='Rebooting...'
	reboot

        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  stop)
	sync;
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop}" >&2
        exit 3
        ;;
esac

:
