#! /bin/bash
### BEGIN INIT INFO
# Provides:          resizesd
# Required-Start:
# Required-Stop:
# Default-Start:     2
# Default-Stop:
# Short-Description: Resizes SD card at boot time
# Description:
#
### END INIT INFO

# Author: CurlyMo

DESC="Resize partition to fill the SD card"
NAME=resizesd
DAEMON=/usr/sbin/$NAME
SCRIPTNAME=/etc/init.d/$NAME
VERBOSE=no

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

do_start()
{
      /usr/sbin/resizesd
}

case "$1" in
  start)
        do_start
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start}" >&2
        exit 3
        ;;
esac

:
