#! /bin/bash
### BEGIN INIT INFO
# Provides:          xbmc
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop XBMC through init
# Description:
#
### END INIT INFO

# Author: CurlyMo
DESC=XBMC
NAME=xbmc.bin
DAEMON=/usr/local/lib/xbmc/$NAME
DAEMON_ARGS="--standalone"
PIDFILE=/var/run/xbmc.pid
SCRIPTNAME=/etc/init.d/xbmc

. /lib/init/vars.sh
. /lib/lsb/init-functions

# Exit if the package is not installed
#[ -x $DAEMON ] || exit 0

do_start()
{
	if [ $(($(ps -A | grep xbmc.bin | wc -l))) -eq 0 ]; then
		start-stop-daemon -c xbian -u xbian --start --quiet --pidfile $PIDFILE --exec $DAEMON --test || return 1;
		chmod a+rw /dev/vchiq
		if [ $(who am i | grep -wo "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | wc -l) -eq 0 ]; then
			echo -e '\e[40;30m'
			dmesg -n 1
			clear
		fi
	echo $(start-stop-daemon -c xbian -u xbian -m --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS; RETURN=$?; case $RETURN in 0 ) echo do normal exit.....; ;; 64 ) echo do power off.....; sudo halt ;; 66 ) echo do reboot.....; sudo reboot; ;; esac || return 2) &exit
	fi
}

do_stop()
{
       start-stop-daemon --stop --signal 9 --retry 5 --quiet --pidfile $PIDFILE
}

case "$1" in
  start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        case 0 in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  status)
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit 0
        ;;
  *)
        #echo "Usage: $SCRIPTNAME {start|stop}" >&2
        echo "Usage: $SCRIPTNAME {start|stop}" >&2
        exit 3
        ;;
esac

:
