#! /bin/bash
### BEGIN INIT INFO
# Provides:          xbmc
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop XBMC through init
# Description:
#
### END INIT INFO

# Author: CurlyMo
DESC=XBMC
NAME=xbmc.bin
DAEMON=/usr/lib/xbmc/$NAME
DAEMON_ARGS="--standalone"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/xbmc
VERBOSE=no

# Exit if the package is not installed
[ -x $DAEMON ] || exit 0

do_start()
{
	su - root -c  "/usr/bin/startxbmc $PIDFILE $DAEMON $DAEMON_ARGS &"
}

do_stop()
{
       kill -9 $(pgrep -o xbmc)
}

case "$1" in
  start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        case 0 in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  status)
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit 0
        ;;
  *)
        #echo "Usage: $SCRIPTNAME {start|stop}" >&2
        echo "Usage: $SCRIPTNAME {start|stop}" >&2
        exit 3
        ;;
esac

:
