#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function showXBConfigSettingsDlg() {
	MENU=();
	MENU+=(1,"\Zn"$_XBLANGUAGE);
	MENU+=(2,"\Zn"$_XBAUTOSTART);
	TBLCOLUMNCENTER=0; 
	createTableFn "menu"\
	"#,\Zb"$_XBACTIONS\
	"${MENU[@]}";
	TBLCOLUMNCENTER=1; 
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+11))
	showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} 10
}

function showXBConfigLanguageDlg() {
	MENU=();
	MENU+=(1,"\Zn"$_XBAUTOMATIC);
	I=1;
	for VALUE in ${LANGUAGES[@]}; do
		I=$(($I+1));
		VALUE="_"${VALUE^^};
		MENU+=($I,"\Zn"${!VALUE});
	done
	createTableFn "menu"\
	"#,\Zb"$_XBLANGUAGE\
	"${MENU[@]}";
	
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+11))
	showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} 14
}

function showXBConfigAutoStartDlg() {
	wrapTxtFn "$_XBCONFIGAUTOSTARTENABLEDISABLE" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showConfirmDlg "$ALIGNEDTXT" $HEIGHT 55
	return $?;
}

function showXBConfigSuccessEnableAutoStartDlg() {
	wrapTxtFn "$_XBSUCCESSENABLEAUTOSTART" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT; 	
}

function showXBConfigSuccessDisableAutoStartDlg() {
	wrapTxtFn "$_XBSUCCESSDISABLEAUTOSTART" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT; 	
}