#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#|------------------------------------|
#|          Global variables          |
#|------------------------------------|

# The arguments this module accepts
ARGUMENTS=(); 
LANGUAGES=();
IFS=" ";
for KEY in ${!LANGARRAY[@]}; do
	LANGUAGES+=($KEY);
done;
IFS=$ORIGINALIFS;

#|------------------------------------|
#|          Include files             |
#|------------------------------------|

source $BASEPATH/modules/xbconfig/functions
source $BASEPATH/modules/xbconfig/dialogs

#|------------------------------------|
#|           Main program             |
#|------------------------------------|

# Executes the GUI version of this module
function showGUIFn() {
	showXBConfigSettingsDlg;
	if [ $? -eq 0 ]; then
		if [ $RETURN -eq 1 ]; then
			showXBConfigLanguageDlg;
			if [ $? -eq 0 ]; then
				if [ $RETURN -eq 1 ]; then
					SELLANG="";
				else
					SELLANG=${LANGUAGES[$(($RETURN-2))]}
				fi
				setXBConfigLanguageFn $SELLANG;
			fi
			showGUIFn;
		elif [ $RETURN -eq 2 ]; then
			showXBConfigAutoStartDlg;
			if [ $? -eq 0 ]; then
				setXBConfigAutoStartFn 1;
				if [ $? -eq 0 ]; then
					showErrorDlg;
				else
					showXBConfigSuccessEnableAutoStartDlg;
				fi
				showGUIFn;
			else
				setXBConfigAutoStartFn 0;
				if [ $? -eq 0 ]; then
					showErrorDlg;
				else
					showXBConfigSuccessDisableAutoStartDlg;
				fi
				showGUIFn;
			fi
		fi
	fi
}

# Executes the command line version of this module
function showCMDFn() {
	echo;
}