#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

	if [ ! -d "/usr/local/include/lirc" ]; then
		mkdir -p "/usr/local/include/lirc";
	fi

	if [ ! -d "/etc/lirc" ]; then
		mkdir -p "/etc/lirc";
	fi

fi 