#!/bin/bash

if [ $1 == "remove" ]; then

	if [ -f "/boot/kernel.img" ]; then
		if [[ $(ls -Al /boot/kernel.img | awk '{print $5}') -eq 5636964 ]]; then
			rm /boot/kernel.img
		fi
	fi
	
	if [ -d /lib/modules/3.6.9+ ]; then
		rm -r /lib/modules/3.6.9+
	fi

fi