#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Oplysninger"
_DESC="Oplysninger om denne distribution"
_INFORMATION="XBian er en fri, Open Source medie center distribution for Raspberry Pi, som kan hentes fra http://www.xbian.org. Vores slogan er \"XBMC on Raspberry Pi, bleeding edge\" da vores primære fokus ligger på levering af den hurtigste mediecenterløsning til Raspberry Pi. Vi er overbeviste om at alle kan bidrage til at gøre XBian bedre. Besøg venligst vores hjemmeside for få hjælp eller komme med forslag, ønsker eller bidrag, del endelig disse med os!"