#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Informatie"
_DESC="Informatie over dit besturingssysteem"
_INFORMATION="XBian is een gratis, Open Source media center besturingssysteem voor de Raspberry Pi, dat gedownload kan worden op http://www.xbian.org. Onze slogan is \"XBMC on Raspberry Pi, bleeding edge\" aangezien onze voornamelijke focus ligt in het leveren van de snelste media center voor Raspberry Pi. Wij geloven dat iedereen XBian beter kan maken. Bezoek onze website voor ondersteuning en als je vragen, suggesties of wensen hebt, deel ze met ons!"
