#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Информация"
_DESC="Информация о программе"
_INFORMATION="XBian это бесплатный, открытый (Open Source) медиа-центр для Raspberry Pi, который может быть загружен с http://www.xbian.org. Наш слоган \"XBMC on Raspberry Pi, bleeding edge\" отражает нашу главную цель -  разработку быстрейшего медиацентра для Raspberry Pi. Мы верим, что каждый может помочь сделать XBian лучше. Пожалуйста, посетите наш сайт если вам нужна помощь или если у вас есть пожелания, предложения или вы хотите присоединиться к разработчикам, свяжитесь с нами!"