#!/bin/bash
#
#Copyright 2012 Hexagon & CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# Show a menu for selecting interfaces
#  $1 List of interfaces
function showInterfacesSelectDlg() {
	MENU=()
	IFACES="$1"
	I=1
	for IFACE in ${IFACES[@]}; do
		IPADDR=$(ifconfig $IFACE | grep 'inet' | cut -d: -f2 | awk '{print $1}')
		NETMASK=$(ifconfig $IFACE | grep 'inet' | cut -d: -f4 | awk '{print $1}')
		MENU+=($I",\Zn"$IFACE",\Zn"$IPADDR",\Zn"$NETMASK)
		I=$(($I+1))
	done
	TBLCOLUMNCENTER=0;
	createTableFn "menu"\
	"#,\Zb$_NETWORKINTERFACES,\Zb$_NETWORKADDRESS,\Zb$_NETWORKMASK"\
	"${MENU[@]}";
	TBLCOLUMNCENTER=1;
	
	# Show interface selector dialog
	centerTxtFn "$_SELECTINTERFACE" $(($DEFAULTWIDTH+11));
	HEADER1=$CENTEREDTXT;
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+11));
	showMenuDlg "$HEADER1\n$CENTEREDTXT" "$ROWS" ${#MENU[@]} $((${#MENU[@]}+9))
}

# Show a radio dialog for selecting DHCP or Static configuration
# Arguments
#  $1 Current mode (DHCP|Static)
function showIPModeConfigDlg() {
	MENU=();
	# Radio states
	STATUSDHCP="off"
	STATUSSTATIC="off"
	
	# Pre-select current state
	if [ "$1" == "static" ]; then
		STATUSSTATIC="on"
	else
		STATUSDHCP="on"
	fi
	IFS=$ORIGINALIFS;
	MENU+=(1",\Zn"$_IPDHCP","$STATUSDHCP);
	MENU+=(2",\Zn"$_IPSTATIC","$STATUSSTATIC);
	
	createTableFn "radio" \
	"#,\Zb$_NETWORKTYPE"\
	"${MENU[@]}"
	
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+6));
	showRadioDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} $((${#MENU[@]}+8))
}

# Show a radio dialog for selecting WLAN Protection mode
# Arguments
#  $1 Current status (WPA|WEP|Open)
function showWlanModeConfigDlg() {

	MENU=();

	# Radio states
	STATUSWPA="off"
	STATUSWEP="off"
	STATUSOPEN="off"

	# Pre-select current state
	if [ "$1" = "WPA" ]; then
		STATUSWPA="on"
	elif [ "$1" = "WEP" ]; then
		STATUSWEP="on"
	elif [ "$1" = "Open" ]; then
		STATUSOPEN="on"
	else
		STATUSOPEN="on"
	fi
	
	IFS=$ORIGINALIFS;
	MENU+=(1",\Zn"$_WLANWPA","$STATUSWPA);
	MENU+=(2",\Zn"$_WLANWEP","$STATUSWEP);
	MENU+=(3",\Zn"$_WLANOPEN","$STATUSOPEN);
	createTableFn "radio" \
	"#,\Zb$_NETWORKPROTECTION"\
	"${MENU[@]}"
	
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+6));
	showRadioDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} $((${#MENU[@]}+9))

}

function showInterfacesLoadingDlg() {
	wrapTxtFn "$_LOADINGINTERFACES" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
}

function showNoInterfacesAvailableDlg() {
	wrapTxtFn "$_NOINTERFACES" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}

function showScanningForNetworksDlg() {
	wrapTxtFn "$_SCANNINGFORWLAN" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
}

# Ask for credentials for the selected interface
# Arguments
#  $1 Current SSID
#  $2 Current KEY
function showInterfaceCredentialsDlg() {
	wrapTxtFn "$_ENTERCREDENTIALS" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInputForm2Dlg "$ALIGNEDTXT" "$_SSID:" "$1" "$_KEY:" "$2"
}

# Ask for static IP configuration
# Arguments
#  $1 Current IP
#  $2 Current Netmask
#  $3 Current Gateway
#  $4 Current Nameserver 1
#  $5 Current Nameserver 2
function showInterfaceStaticDlg() {
	wrapTxtFn "$_ENTERSTATICCONFIG" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInputForm5Dlg "$ALIGNEDTXT" "$_NETWORKADDRESS*:" "$1" "$_NETWORKMASK*:" "$2" "$_NETWORKGATEWAY*:" "$3" "$_NAMESERVER:" "$4" "$_NAMESERVER:" "$5"
}

function showInterfaceCredentialsErrorDlg() {
	wrapTxtFn "$_INVALIDCREDENTIALS" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}

function showInterfaceCredentialsSuccessDlg() {
	wrapTxtFn "$_CREDENTIALSUPDATED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}

function showInterfaceStaticErrorDlg() {
	wrapTxtFn "$_INVALIDSTATICCONFIG" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}

function showInterfaceStaticSuccessDlg() {
	wrapTxtFn "$_STATICCONFIGUPDATED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}

function showInterfaceDhcpSuccessDlg() {
	wrapTxtFn "$_DHCPCONFIGUPDATED" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}

# Shows available wlan networks
# Arguments
#  $1 Current SSID
#  $2 Current networklist
function showAvailableWLANDlg() {
	MENU=();
	IFS=$'\n';
	SSID=$1
	shift;
	WNETWORKS=($@)
	X=1;
	SIGNAL="";
	for WNETWORK in ${WNETWORKS[@]}; do
		IFS=",";
		VALUES=($WNETWORK);

		NAME=$(echo "${VALUES[0]}" | awk '{print substr($0,2,length-2)}');
		if [ ${#NAME} -gt 13 ]; then
			NAME=${NAME:0:10}"...";
		fi
		SECURITY=${VALUES[2]};
		if [ "$SECURITY" == "on" ]; then
			SECURITY="$_YES"
		else
			SECURITY="$_NO"
		fi
		SELECTED="off";
		if [ "$NAME" == "$SSID" ]; then
			SELECTED="on";
		fi
		if [ ${VALUES[3]} -eq 100 ]; then
			SIGNAL="*****";
		elif [ ${VALUES[3]} -gt 80 ]; then
			SIGNAL="****";
		elif [ ${VALUES[3]} -gt 60 ]; then
			SIGNAL="***";
		elif [ ${VALUES[3]} -gt 40 ]; then
			SIGNAL="**";
		else
			SIGNAL="*";
		fi
		MENU+=($X",\Zn"$NAME",\Zn"$SECURITY",\Zn"${VALUES[1]}",\Zn"$SIGNAL","$SELECTED);
		X=$(($X+1));
	done
	TBLCOLUMNCENTER=0;
	createTableFn "radio" \
	"#,\Zb"$_NETWORKNAME",\Zb"$_NETWORKPROTECTION",\Zb"$_NETWORKTYPE,"\Zb"$_WLANSIGNAL"" \
	"${MENU[@]}"
	TBLCOLUMNCENTER=1;
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+7));
	showRadioDlg "$CENTEREDTXT" "$ROWS" 6 15
}

function showScanForWLANDlg() {
	MENU=()
	
	TBLCOLUMNCENTER=0;
	createTableFn "menu" \
	"#,\Zb"$_NETWORKWLAN"" \
	"1,\Zn"$_NETWORKSCANAVAILABLE"" \
	"2,\Zn"$_NETWORKCUSTOM""
	TBLCOLUMNCENTER=1;
	
	# Show interface selector dialog
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+11));
	showMenuDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} $((${#MENU[@]}+8))
}

# Ask for network SSID in case of open protection
# Arguments
#  $1 Current SSID
function showInterfaceSSIDDlg() {
	showInputDlg "$_SSID:" $1
}

function showRestartWLANDlg() {
	wrapTxtFn "$_RESTARTINGADAPTER $1" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
}

function showWLANConnectingDlg() {
	wrapTxtFn "$_TRYINGCONNECTINGTO $1" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showInfoDlg "$ALIGNEDTXT" $HEIGHT
}

function showWLANConnectionFailedDlg() {
	wrapTxtFn "$_FAILEDTOCONNECTTO $1" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}

function showWLANConnectionSuccessDlg() {
	wrapTxtFn "$_SUCCESSFULLYCONNECTEDTO $1" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT" $HEIGHT
}
