#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Dienste"
_DESC="Start/Stop sowie Verwalten der Dienste"
_LOADINGSERVICES="Status der Dienste wird geladen..."
_RESTARTINGSERVICE="Dienst wird neu gestartet..."
_FAILEDTORESTARTSERVICE="Abbruch beim Neustart des Dienstes..."
_STARTINGSERVICE="Dienst wird gestartet..."
_FAILEDTOSTARTSERVICE="Abbruch beim Start des Dienstes..."
_STOPPINGSERVICE="Dienst wird beendet..."
_FAILEDTOSTOPSERVICE="Abbruch beim Beenden des Dienstes..."
_FAILEDTOENABLEAUTOSTARTSERVICE="Abbruch beim Aktivieren des Autostarts..."
_FAILEDTODISABLEAUTOSTARTSERVICE="Abbruch beim Deaktivieren des Autostarts..."
_ENABLEAUTOSTARTSERVICE="Autostart wird aktiviert..."
_DISABLEAUTOSTARTSERVICE="Autostart wird deaktiviert..."
_UNEXISTINGSERVICE="Der gewählte Dienst existiert nicht..."
_SERVICEDELETECONFIRM="Soll der Dienst wirklich von der Liste entfernt werden?"
_SERVICEDELETED="Der Dienst wurde erfolgreich entfernt"
_SERVICEINSERTED="Der Dienst wurde erfolgreich hinzugefügt"
_SERVICEUPDATED="Der Dienst wurde erfolgreich aktualisiert"
_SERVICE="Dienst"
_SERVICEACTION="Aktion"
_SERVICEAUTOSTART="Autostart"
_SERVICERUNNING="Läuft"
_SERVICESTARTRESTART="(Neu)Start"
_SERVICESTOP="Beenden"
_SERVICEEDIT="Bearbeiten"
_SERVICEDELETE="Entfernen"
_SERVICENAME="Name"
_SERVICEDAEMONS="Daemon(s)"