#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Services"
_DESC="Start/stop and manage services"
_LOADINGSERVICES="Loading status of services..."
_RESTARTINGSERVICE="Restarting service..."
_FAILEDTORESTARTSERVICE="Failed to restart the service..."
_STARTINGSERVICE="Starting service..."
_FAILEDTOSTARTSERVICE="Failed to start the service..."
_STOPPINGSERVICE="Stopping service..."
_FAILEDTOSTOPSERVICE="Failed to stop the service..."
_FAILEDTOENABLEAUTOSTARTSERVICE="Failed to enable the autostart of the service..."
_FAILEDTODISABLEAUTOSTARTSERVICE="Failed to disable the autostart of the service..."
_ENABLEAUTOSTARTSERVICE="Enabling the autostart of the service..."
_DISABLEAUTOSTARTSERVICE="Disabling the autostart of the service..."
_UNEXISTINGSERVICE="This service does not exists..."
_SERVICEDELETECONFIRM="Are you sure you want to delete this service from the list?"
_SERVICEDELETED="The service has successfully been removed"
_SERVICEINSERTED="The service has successfully been inserted"
_SERVICEUPDATED="The service has successfully been updated"
_SERVICE="Service"
_SERVICEACTION="Action"
_SERVICEAUTOSTART="Autostart"
_SERVICERUNNING="Running"
_SERVICESTARTRESTART="(Re)Start"
_SERVICESTOP="Stop"
_SERVICEEDIT="Edit"
_SERVICEDELETE="Delete"
_SERVICENAME="Name"
_SERVICEDAEMONS="Daemon(s)"