#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Services"
_DESC="Gérer les services"
_LOADINGSERVICES="Chargement du statut des services..."
_RESTARTINGSERVICE="Redémarrage du service..."
_FAILEDTORESTARTSERVICE="Echec lors du redémarrage du service..."
_STARTINGSERVICE="Démarrage du service..."
_FAILEDTOSTARTSERVICE="Echec lors du démarrage du service..."
_STOPPINGSERVICE="Arrêt du service..."
_FAILEDTOSTOPSERVICE="Echec lors de l'arrêt du service..."
_FAILEDTOENABLEAUTOSTARTSERVICE="Echec lors de l'activation du démarrage automatique du service..."
_FAILEDTODISABLEAUTOSTARTSERVICE="Echec lors de la désactivation du démarrage automatique du service..."
_ENABLEAUTOSTARTSERVICE="Activation du démarrage automatique du service..."
_DISABLEAUTOSTARTSERVICE="Désactivation du démarrage automatique du service..."
_UNEXISTINGSERVICE="Ce service n'existe pas..."
_SERVICEDELETECONFIRM="Voulez vous supprimer ce service de la liste?"
_SERVICEDELETED="Le service a été correctement supprimé"
_SERVICEINSERTED="Le service a été correctement ajouté"
_SERVICEUPDATED="Le service a été correctement mis à jour"
_SERVICE="Service"
_SERVICEACTION="Action"
_SERVICEAUTOSTART="Démarrage automatique"
_SERVICERUNNING="Démarré"
_SERVICESTARTRESTART="(Re)Démarrer"
_SERVICESTOP="Arrêter"
_SERVICEEDIT="Modifier"
_SERVICEDELETE="Supprimer"
_SERVICENAME="Nom"
_SERVICEDAEMONS="Daemon(s)"