#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Diensten"
_DESC="Start/Stop en beheer diensten"
_LOADINGSERVICES="Status van diensten aan het laden..."
_RESTARTINGSERVICE="Service aan het herstarten..."
_FAILEDTORESTARTSERVICE="Het herstarten van de service is niet gelukt..."
_STARTINGSERVICE="Service aan het starten..."
_FAILEDTOSTARTSERVICE="Het starten van de service is niet gelukt..."
_STOPPINGSERVICE="Service aan het stoppen..."
_FAILEDTOSTOPSERVICE="Het stoppen van de service is niet gelukt..."
_FAILEDTOENABLEAUTOSTARTSERVICE="Het aanzetten van autostart voor deze service is niet geluk..."
_FAILEDTODISABLEAUTOSTARTSERVICE="Het uitzetten van autostart voor deze service is niet geluk..."
_ENABLEAUTOSTARTSERVICE="Autostart voor deze service aan het aanzetten..."
_DISABLEAUTOSTARTSERVICE="Autostart voor deze service aan het uitzetten..."
_UNEXISTINGSERVICE="Deze dienst bestaat niet..."
_SERVICEDELETECONFIRM="Weet u zeker dat u deze dienst uit de lijst wilt verwijderen?"
_SERVICEDELETED="De dienst is succesvol verwijderd"
_SERVICEUPDATED="De dienst is succesvol bijgewerkt"
_SERVICEINSERTED="De dienst is succesvol toegevoegd"
_SERVICE="Dienst"
_SERVICEACTION="Actie"
_SERVICEAUTOSTART="Autostart"
_SERVICERUNNING="Draaiend"
_SERVICESTARTRESTART="(Her)Starten"
_SERVICESTOP="Stoppen"
_SERVICEEDIT="Bewerken"
_SERVICEDELETE="Verwijderen"
_SERVICENAME="Naam"
_SERVICEDAEMONS="Daemon(s)"