#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Службы"
_DESC="Запуск, остановка и управление службами"
_LOADINGSERVICES="Загрузка служб..."
_RESTARTINGSERVICE="Перезапуск службы..."
_FAILEDTORESTARTSERVICE="Не удалось перезапустить службу..."
_STARTINGSERVICE="Запуск службы..."
_FAILEDTOSTARTSERVICE="Не удалось запустить службу..."
_STOPPINGSERVICE="Остановка службы..."
_FAILEDTOSTOPSERVICE="Не удалось остановить службу..."
_FAILEDTOENABLEAUTOSTARTSERVICE="Не удалось включить автозапуск службы..."
_FAILEDTODISABLEAUTOSTARTSERVICE="Не удалось выключить автозапуск службы..."
_ENABLEAUTOSTARTSERVICE="Включение автозапуска службы..."
_DISABLEAUTOSTARTSERVICE="Выключение автозапуска службы..."
_UNEXISTINGSERVICE="Эта служба не существует..."
_SERVICEDELETECONFIRM="Вы действительно хотите хотите удалить службу из списка?"
_SERVICEDELETED="Служба была успешно удалена"
_SERVICEINSERTED="Служба была успешно добавлена"
_SERVICEUPDATED="Служба была успешно обновлена"
_SERVICE="Службы"
_SERVICEACTION="Действия"
_SERVICEAUTOSTART="Автозапуск"
_SERVICERUNNING="Запущена"
_SERVICESTARTRESTART="(Пере)Запуск"
_SERVICESTOP="Остановить"
_SERVICEEDIT="Редактировать"
_SERVICEDELETE="Удалить"
_SERVICENAME="Имя"
_SERVICEDAEMONS="Демон(ы)"
