#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="VC1"
_DESC="Manage your VC1 license"
_VC1LICENSE="VC1 License"
_VC1INSERTED="VC1 license successfully inserted";
_VC1DELETED="VC1 license successfully removed";
_VC1UPDATED="VC1 license successfully updated";
_VC1LICENSEINVALID="The VC1 license you entered is of an incorrect format"