#!/bin/bash
#
#Copyright 2012 CurlyMo & Hexagon <development@xbian.org>
#
#Resize SD function is based on the corresponding function in raspi-config
#The overclocking function is copied from raspi-config
#raspi-config is created by Alex Bradbury <asb@asbradbury.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

#Enable CTRL-C, doesn't clear caches, doesn't install/executes anything
if [ $DEBUG -eq 0 ]; then
	trap '' 2;
fi

# Check that required packages are already installed
pkg_installed "dialog"; if [ $? -eq 0 ]; then
	echo "This program requires the dialog package: apt-get install dialog";
	exit 0;
fi

pkg_installed "screen"; if [ $? -eq 0 ]; then
	echo "This program requires the screen package: apt-get install screen";
	exit 0;
fi

pkg_installed "git"; if [ $? -eq 0 ]; then
	echo "This program requires the git package: apt-get install git";
	exit 0;
fi

pkg_installed "git"; if [ $? -eq 0 ]; then
	echo "This program requires the wget package: apt-get install wget";
	exit 0;
fi
