#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function showVideoFlagsDlg() {
	MENU=();
	
	X=0;
	for FLAG in ${VIDEOFLAGS[@]}; do
		X=$(($X+1));
		_LABEL="_"$(echo $FLAG | sed -e 's/_//g' | tr "[:lower:]" "[:upper:]");
		if [ ! -z ${!_LABEL} ]; then
			LABEL=${!_LABEL};
		else
			LABEL=$FLAG;
		fi
		
		if [ ${VIDEOSETTINGS[$FLAG]} -eq 0 ]; then
			MENU+=($X",\Zn"$LABEL",off");
		else
			MENU+=($X",\Zn"$LABEL",on");
		fi
	done;
	createTableFn "radio" \
	"#,\Zb$_VIDEOFLAGS" \
	"${MENU[@]}"
	
	centerTxtFn "$HEADER" $(($DEFAULTWIDTH+6));
	showChecklistDlg "$CENTEREDTXT" "$ROWS" ${#MENU[@]} $((${#MENU[@]}+9))
}

function showVideoFlagsSuccessDlg() {
	wrapTxtFn "$_VIDEOFLAGSSUCCESS" $(($DEFAULTWIDTH-4));
	centerTxtFn "$WRAPPEDTXT" $(($DEFAULTWIDTH-4));
	valignTxtFn "$CENTEREDTXT"
	showMsgDlg "$ALIGNEDTXT"
}