#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

function getVideoFlagsFn() {
	for FLAG in ${VIDEOFLAGS[@]}; do
		selectConfigVarFn $FLAG;
		if [ -z $RETURN ]; then
			VIDEOSETTINGS[$FLAG]=0;
		else
			VIDEOSETTINGS[$FLAG]=1;
		fi
	done;
}

function updateVideoFlagsFn() {
	for KEY in ${!VIDEOFLAGS[*]}; do
		FLAG=${VIDEOFLAGS[$KEY]};
		if [[ "$1" =~ "$(($KEY+1))" ]]; then
			updateConfigVarFn "$FLAG" 1;
			askForRebootFn;
		else
			deleteConfigVarFn "$FLAG";
			askForRebootFn;
		fi
	done;
	getVideoFlagsFn;
	ERROR=0;
	for KEY in ${!VIDEOFLAGS[*]}; do
		FLAG=${VIDEOFLAGS[$KEY]};
		if [[ "$1" =~ "$(($KEY+1))" ]]; then
			if [ ${VIDEOSETTINGS[$FLAG]} -eq 0 ]; then
				ERROR=1;
			fi
		else
			if [[ ${VIDEOSETTINGS[$FLAG]} -eq 1 ]]; then
				ERROR=1;
			fi
		fi
	done;
	return $ERROR;
}