#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Overclocking"
_DESC="Konfigurer overclocking"
_OCWARNING="Ekstrem overclocking kan reducere levetiden for din Raspberry Pi. XBian har afprøvet forskellige indstillinger for overclocking og skabt en foretrukken konfiguration af indstillinger. Turbo-overclocking kan forårsage fejl i filsystemet. Overclock på eget ansvar!"
_OCNOTCHANGED="Disse overclock-indstillinger er allerede sat"
_OCCHANGED="Overclock-indstillingerne er ændret"
_OCNAME="Navn"
_OCCUSTOM="~"
_OCEMPTYFIELDS="Udfyld alle felterne"