#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Overclocking"
_DESC="Configurar overclocking"
_OCWARNING="Overcloking extremo puede reducir la vida util de tu Raspberry Pi. XBian ha sido probado con diversas configuraciones de overclock y se han creado una configuracion recomendada de overclock. Overclock en modo turbo puede hacer que se corrompa el sistema. ¡Haz overclock bajo tu propio riesgo!"
_OCNOTCHANGED="Estos ajustes de overclock ya estan siendo usados"
_OCCHANGED="Los ajustes de overclock han sido sustituidos con exito"
_OCNAME="Nombre"
_OCCUSTOM="~"
_OCEMPTYFIELDS="No has rellenado todo los campos"