#!/bin/sh
### BEGIN INIT INFO
# Provides:          progress75
# Required-Start:    sudo
# Required-Stop:
# Should-Start:
# Default-Start:     1 2 3 4 5
# Default-Stop:
# Short-Description:
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

case "$1" in
  start|"")
        if [ $(cat /boot/cmdline.txt | grep splash | /usr/bin/wc -l) -eq 1 ]; then
#               if [ -d "/splash" ] && [ -f "/splash/splash" ]; then
                if [ -f "/usr/bin/splash" ]; then
#                       $(/splash/splash --percentage=75);
                        $(splash --percentage=75);
                fi
        fi
	;;
esac

:
