#! /bin/sh
### BEGIN INIT INFO
# Provides:          progress25
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description:
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

case "$1" in
  start|"")
	if [ $(cat /boot/cmdline.txt | grep splash | /usr/bin/wc -l) -eq 1 ]; then
#		if [ -d "/splash" ] && [ -f "/splash/splash" ]; then
		if [ -f "/usr/bin/splash" ]; then
#			$(/splash/splash --percentage=25);
			$(splash --percentage=25);
		fi
	fi
	;;
esac

:
