#! /bin/sh
### BEGIN INIT INFO
# Provides:          zram
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: zram swap
# Description:       
### END INIT INFO


#pre-start script
#    modprobe zram
#    echo 134215680 > /sys/block/zram0/disksize
#    mkswap /dev/zram0
#    swapon /dev/zram0
#end script

#post-stop script
#    swapoff /dev/zram0
#    echo 0 > /sys/block/zram0/disksize
#end script

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

SWAPFILE="/var/swapfile"
LOOP=''

start () {
	modprobe -q zram
        modprobe -q loop
	echo 134217728 > /sys/block/zram0/disksize  
	mkswap /dev/zram0 > /dev/null 2>&1
	swapon -p 20 /dev/zram0  >/dev/null 2>&1
	if [ ! -e "$SWAPFILE" ]; then
		log_action_msg "Creating $SWAPFILE"
		dd if=/dev/zero of="$SWAPFILE" bs=1M count=128 >/dev/null 2>&1
		mkswap "$SWAPFILE" >/dev/null 2>&1
	fi
	chattr -C "$SWAPFILE"
	LOOP=`losetup -f`
	echo "$LOOP" > /run/$(basename "$0").conf
	losetup "$LOOP" "$SWAPFILE"  >/dev/null 2>&1
	swapon -p 0 /dev/loop0  >/dev/null 2>&1
	log_action_msg "Starting $DESC" "$NAME"
}

stop () {
	LOOP=`cat /run/$(basename "$0").conf`
	swapoff /dev/zram0  >/dev/null 2>&1
	swapoff "$LOOP"  >/dev/null 2>&1
	echo 0 > /sys/block/zram0/disksize
	rmmod zram  >/dev/null 2>&1
	losetup -d "$LOOP"  >/dev/null 2>&1
	rm /run/$(basename "$0").conf
	log_action_msg "Stopping $DESC" "$NAME"
}

case "$1" in
  start)
	if [ -e /run/$(basename "$0").conf ]; then
		log_warning_msg "Already started."
		exit 99
	fi 
	start
	log_success_msg "Started ok"
	;;
  stop)
	if [ ! -e /run/$(basename "$0").conf ]; then
		log_warning_msg "Not started."
		exit 99
	fi
	stop
	log_success_msg "Stopped ok"
	;;
  restart)
	test -e $/run/$(basename "$0").conf && stop
	sleep 1
	start
	log_success_msg "Restarted ok"
	;;
  status)
	[ -e /dev/zram[0-99] ] && log_success_msg "zram swap running" || log_success_msg "zram swap not running" 
	;;
  *)
	log_success_msg "Usage: zram-swap {start|stop|status|restart}"
	exit 1	
	;;

esac


exit 0
