#!/bin/bash

if [ $1 == "remove" ]; then

	if [ -f /boot/kernel3_6_1.img ]; then
		rm /boot/kernel3_6_1.img
	fi
	
	if [ -d /lib/modules/3.6.1 ]; then
		rm -r /lib/modules/3.6.1
	fi
	
fi

if [ $1 == "upgrade" ]; then

	if [ -f /boot/kernel3_6_1.img ]; then
		rm /boot/kernel3_6_1.img
	fi	

fi
