#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Tjenester"
_DESC="Start/stop og håndter tjenester"
_LOADINGSERVICES="Henter status for tjenester..."
_RESTARTINGSERVICE="Genstarter tjeneste..."
_FAILEDTORESTARTSERVICE="Genstart af tjeneste mislykkedes..."
_STARTINGSERVICE="Starter tjeneste..."
_FAILEDTOSTARTSERVICE="Start af tjeneste mislykkedes..."
_STOPPINGSERVICE="Stopper tjeneste..."
_FAILEDTOSTOPSERVICE="Standsning af tjeneste mislykkedes..."
_FAILEDTOENABLEAUTOSTARTSERVICE="Aktivering af autostart for tjenesten mislykkedes"
_FAILEDTODISABLEAUTOSTARTSERVICE="Deaktivering af autostart for tjenesten mislykkedes..."
_ENABLEAUTOSTARTSERVICE="Aktiverer autostart af tjenesten..."
_DISABLEAUTOSTARTSERVICE="Deaktiverer autostart af tjenesten..."
_UNEXISTINGSERVICE="Denne tjeneste kunne ikke findes..."
_SERVICEDELETECONFIRM="Er du sikker på du vil slette denne tjeneste fra listen?"
_SERVICEDELETED="Denne service er nu fjernet"
_SERVICEINSERTED="Denne service er nu tilføjet"
_SERVICEUPDATED="Denne service er nu opdateret"
_SERVICE="Tjeneste"
_SERVICEACTION="Handling"
_SERVICEAUTOSTART="Autostart"
_SERVICERUNNING="Kører"
_SERVICESTARTRESTART="(Gen)start"
_SERVICESTOP="Stop"
_SERVICEEDIT="Rediger"
_SERVICEDELETE="Slet"
_SERVICENAME="Navn"
_SERVICEDAEMONS="Daemon(er)"