#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Servicios"
_DESC="Iniciar/parar y gestionar servicios"
_LOADINGSERVICES="Cargando estado de los servicios..."
_RESTARTINGSERVICE="Reiniciando servicio..."
_FAILEDTORESTARTSERVICE="Fallo al reiniciar servicio..."
_STARTINGSERVICE="Iniciando servicio..."
_FAILEDTOSTARTSERVICE="Fallo al iniciar el servicio..."
_STOPPINGSERVICE="Parando el servicio..."
_FAILEDTOSTOPSERVICE="Fallo al parar el servicio..."
_FAILEDTOENABLEAUTOSTARTSERVICE="Activar el inicio automático del servicio ha fallado..."
_FAILEDTODISABLEAUTOSTARTSERVICE="Desactivar el inicio automático del servicio ha fallado..."
_ENABLEAUTOSTARTSERVICE="Activando el inico automático del servicio..."
_DISABLEAUTOSTARTSERVICE="Desactivando el inicio automático del servicio..."
_UNEXISTINGSERVICE="Este servicio no exite..."
_SERVICEDELETECONFIRM="¿Estás seguro de que quieres borrar este servicio de la base de datos?"
_SERVICEDELETED="Este servicio ha sido desinstalado con éxito"
_SERVICEINSERTED="Este servicio ha sido insertado con éxito"
_SERVICEUPDATED="Este servicio ha sido actualizado con éxito"
_SERVICE="Servicio"
_SERVICEACTION="Acción"
_SERVICEAUTOSTART="Inicio automático"
_SERVICERUNNING="Ejecutándose"
_SERVICESTARTRESTART="Reiniciar"
_SERVICESTOP="Parar"
_SERVICEEDIT="Editar"
_SERVICEDELETE="Borrar"
_SERVICENAME="Nombre"
_SERVICEDAEMONS="Daemon(s)"