#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="XBMC"
_DESC="Skift XBMC-indstillinger"
_XBMCWEBSERVERSUCCESSENABLED="XBMC webserver er aktiveret"
_XBMCWEBSERVERSUCCESSDISABLED="XBMC webserver er deaktiveret"
_XBMCWEBSERVERFAILEDENABLE="Aktivering af XBMC webserver mislykkedes"
_XBMCWEBSERVERFAILEDDISABLE="Deaktivering af XBMC webserver mislykkedes"
_XBMCGUIRESSUCCESS="Ændring af opløsning for XBMC GUI lykkedes"
_XBMCGUIRESFAILED="Ændring af opløsning for XBMC GUI mislykkedes"
_XBMCGUIRES="GUI Opløsning"
_XBMCWEBSERVER="Webserver"
_XBMCACTIONS="Handlinger"
_XBMCWEBSERVERENABLEDISABLE="Vil du de-/aktivere XBMC webserver?"