#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="XBMC"
_DESC="Изменение настроек XBMC"
_XBMCWEBSERVERSUCCESSENABLED="Веб-сервер XBMC успешно включен"
_XBMCWEBSERVERSUCCESSDISABLED="Веб-сервер XBMC успешно отключен"
_XBMCWEBSERVERFAILEDENABLE="Не удалось включить веб-сервер XBMC"
_XBMCWEBSERVERFAILEDDISABLE="Не удалось отключить веб-сервер XBMC"
_XBMCGUIRESSUCCESS="Разрешение экрана успешно изменено"
_XBMCGUIRESFAILED="Не удалось изменить разрешение экрана"
_XBMCGUIRES="Разрешение экрана"
_XBMCWEBSERVER="Веб-сервер"
_XBMCACTIONS="Варианты"
_XBMCWEBSERVERENABLEDISABLE="Вы хотите включить или отключить веб-сервер XBMC?"
