#!/bin/bash
#
#Copyright 2012 CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

# Get the current license
#  $1 [Container] License
# Returns
#  $LICENSE [String]
function getCurrentLicenseMPG2Fn() {
	LICENSE=$(cat /boot/config.txt | grep 'decode_MPG2' | cut -f 2 -d=); 
}

# Insert the current license
#  $1 [String] License
# Returns
#  * [Integer]
#  - 1: Success
#  - 0: Failed
function insertLicenseMPG2Fn() {
	NEWLICENSE=$1;
	if [ "${NEWLICENSE:0:2}" == "0x" ] && [[ "${NEWLICENSE:2:8}" =~ ^[0-9a-f]{1,8}$ ]] && [ ${#NEWLICENSE} -le 10 ] && [ ${#NEWLICENSE} -ge 9 ]; then
		echo "decode_MPG2=$1" >> /boot/config.txt 
		if [ $(cat /boot/config.txt | grep $1 | wc -l) -eq 1 ]; then
			return 1;
		else
			return 0;
		fi
	else
		return 2;
	fi
}


# Update the current license
#  $1 [String] Current License
#  $2 [String] Old License
# Returns
#  * [Integer]
#  - 1: Success
#  - 0: Failed
function updateLicenseMPG2Fn() {
	NEWLICENSE=$1;
	if [ "${NEWLICENSE:0:2}" == "0x" ] && [[ "${NEWLICENSE:2:8}" =~ ^[0-9a-f]{1,8}$ ]] && [ ${#NEWLICENSE} -le 10 ] && [ ${#NEWLICENSE} -ge 9 ]; then
		sed -i "s/decode_MPG2=$2/decode_MPG2=$1/g" /boot/config.txt
		if [ $(cat /boot/config.txt | grep $1 | wc -l) -eq 1 ]; then
			return 1;
		else
			return 0;
		fi
	else
		return 2;
	fi
}

# Delete the current license
#  $1 [String] Current License
# Returns
#  * [Integer]
#  - 1: Success
#  - 0: Failed
function deleteLicenseMPG2Fn() {
	sed -i "/decode_MPG2=$1/d" /boot/config.txt;
	if [ $(cat /boot/config.txt | grep $1 | wc -l) -eq 0 ]; then
		return 1;
	else
		return 0;
	fi
}
