#!/bin/bash

if [ $1 == "remove" ]; then

	if [ -f "/boot/kernel.img" ]; then
		if [[ $(md5sum /boot/kernel.img | awk '{print $1}') == "d24fbfba51e4b5632bdb3d8ec78cf62e" ]]; then
			rm /boot/kernel.img
		fi
	fi
	
	if [ -d /lib/modules/3.6.11+ ]; then
		rm -r /lib/modules/3.6.11+
	fi

fi