#!/bin/bash

if [ $1 == "remove" ]; then

	if [ -f /boot/kernel3_6_11.img ]; then
		rm /boot/kernel3_6_11.img
	fi
	
	if [ -d /lib/modules/3.6.11+ ]; then
		rm -r /lib/modules/3.6.11+
	fi
	
fi

if [ $1 == "upgrade" ]; then

	if [ -f /boot/kernel3_6_11.img ]; then
		rm /boot/kernel3_6_11.img
	fi	

fi
