#!/bin/bash
#
#Copyright 2012 Hexagon & CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Netværk"
_DESC="Konfigurer netværksgrænseflader"
_LOADINGINTERFACES="Netværksgrænseflader indlæses..."
_NOINTERFACES="Ingen netværksgrænseflader tilgængelige eller tilsluttet"
_SELECTINTERFACE="Vælg grænseflade at konfigurere"
_IPDHCP="DHCP"
_IPSTATIC="Statisk IP"
_SELECTHOW="Vælg hvordan";
_OBTAINIP="skal få sin IP-addresse"
_SSID="SSID"
_KEY="Nøgle (Key)"
_ENTERCREDENTIALS="Angiv adgangsoplysninger for valgt grænseflade"
_INVALIDCREDENTIALS="Ugyldige adgangsoplysninger angivet, både SSID og Nøgle skal angives"
_WLANWEP="WEP"
_WLANWPA="WPA"
_WLANOPEN="Åben"
_WLANSIGNAL="Signal"
_CREDENTIALSUPDATED="WLAN adgangsoplysninger blev opdateret"
_ENTERSTATICCONFIG="Angiv detaljer om statisk IP"
_NETWORKINTERFACES="Grænseflader"
_NETWORKADDRESS="IP-Addresse"
_NETWORKMASK="Netmaske"
_NETWORKGATEWAY="Gateway"
_NAMESERVER="Navneserver"
_INVALIDSTATICCONFIG="Ugyldige oplysninger for statisk IP, forsøg igen"
_STATICCONFIGUPDATED="Statisk IP konfiguration blev opdateret"
_DHCPCONFIGUPDATED="Grænsefladen konfigureres nu med DHCP"
_NETWORKTYPE="Type"
_NETWORKPROTECTION="Beskyttelse"
_WLANSCAN="Skan"
_NETWORKNAME="Navn"
_NETWORKSCANAVAILABLE="Skan"
_NETWORKCUSTOM="Tilpasset"
_NETWORKWLAN="WLAN"
_SCANNINGFORWLAN="Søger tilgængelige netværk..."
_RESTARTINGADAPTER="Genstarter"
_TRYINGCONNECTINGTO="Vent venligst. Forsøger at forbinde til"
_FAILEDTOCONNECTTO="Kunne ikke forbinde til"
_SUCCESSFULLYCONNECTEDTO="Forbindelsen er oprettet til"