#!/bin/bash
#
#Copyright 2012 Hexagon & CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Network"
_DESC="Configure network interfaces"
_LOADINGINTERFACES="Interfaces loading, please wait ..."
_NOINTERFACES="No network interfaces available or they are not connected"
_SELECTINTERFACE="Select interface to configure"
_IPDHCP="DHCP"
_IPSTATIC="Static IP"
_SELECTHOW="Select how";
_OBTAINIP="should obtain it's IP address"
_SSID="SSID"
_KEY="KEY"
_ENTERCREDENTIALS="Enter credentials for selected interface"
_INVALIDCREDENTIALS="Invalid WLAN credentials entered, both SSID and KEY has to be entered"
_WLANWEP="WEP"
_WLANWPA="WPA"
_WLANOPEN="Open"
_WLANSIGNAL="Signal"
_CREDENTIALSUPDATED="WLAN credentials successfully updated"
_ENTERSTATICCONFIG="Enter static IP details"
_NETWORKINTERFACES="Interfaces"
_NETWORKADDRESS="IP Address"
_NETWORKMASK="Netmask"
_NETWORKGATEWAY="Gateway"
_NAMESERVER="Nameserver"
_INVALIDSTATICCONFIG="Invalid static IP details, please try again"
_STATICCONFIGUPDATED="Static IP configuration updated"
_DHCPCONFIGUPDATED="Interface is now configured using DHCP"
_NETWORKTYPE="Type"
_NETWORKPROTECTION="Protection"
_WLANSCAN="Scan"
_NETWORKNAME="Name"
_NETWORKSCANAVAILABLE="Scan"
_NETWORKCUSTOM="Custom"
_NETWORKWLAN="WLAN"
_SCANNINGFORWLAN="Scanning for available networks..."
_RESTARTINGADAPTER="Restarting"
_TRYINGCONNECTINGTO="Please wait. Trying to connect to"
_FAILEDTOCONNECTTO="Failed to connect to"
_SUCCESSFULLYCONNECTEDTO="Successfully connected to"