#!/bin/bash
#
#Copyright 2012 Hexagon & CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Red"
_DESC="Configurar una interfaz de red"
_LOADINGINTERFACES="Cargando interfaces, por favor espere ..."
_NOINTERFACES="No hay interfaces de red disponibles o no estan conectadas"
_SELECTINTERFACE="Selecciona la interfaz a configurar"
_IPDHCP="DHCP"
_IPSTATIC="IP estatica"
_SELECTHOW="Selecciona como";
_OBTAINIP="deberia obtener una direccion IP"
_SSID="SSID"
_KEY="Clave"
_ENTERCREDENTIALS="Introduce los credenciales para la interfaz seleccionada"
_INVALIDCREDENTIALS="Credenciales WLAN invalidos, tanto SSID como la clave debenser introducidas"
_WLANWEP="WEP"
_WLANWPA="WPA"
_WLANOPEN="Abierta"
_WLANSIGNAL="Señal"
_CREDENTIALSUPDATED="Credenciales WLAN actualizados con exito"
_ENTERSTATICCONFIG="Introduce la configuracion de IP estatica"
_NETWORKINTERFACES="Interfaces"
_NETWORKADDRESS="Direccion IP"
_NETWORKMASK="Mascara de red"
_NETWORKGATEWAY="Gateway"
_NAMESERVER="Nombre del servidor"
_INVALIDSTATICCONFIG="Ajuste de IP estaticos invalidos, por favor vuelva a intentarlo"
_STATICCONFIGUPDATED="Configuracion de IP estatica actualizada"
_DHCPCONFIGUPDATED="la interfaz esta ahora configurada para usar DHCP"
_NETWORKTYPE="Tipo"
_NETWORKPROTECTION="Proteccion"
_WLANSCAN="Escanear"
_NETWORKNAME="Nombre"
_NETWORKSCANAVAILABLE="Escanear"
_NETWORKCUSTOM="A medida"
_NETWORKWLAN="WLAN"
_SCANNINGFORWLAN="Escaneando redes disponibles..."
_RESTARTINGADAPTER="Reiniciando"
_TRYINGCONNECTINGTO="Por favor espere, intentando conectar con"
_FAILEDTOCONNECTTO="Fallo en la conexion con"
_SUCCESSFULLYCONNECTEDTO="Se consiguio conectar con"