#!/bin/bash
#
#Copyright 2012 Hexagon & CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Réseau"
_DESC="Configurer les interfaces réseaux"
_LOADINGINTERFACES="Chargement, veuillez patienter ..."
_NOINTERFACES="Pas d'interface réseau disponible ou elles ne sont pas connectées"
_SELECTINTERFACE="Choisissez l'inteface a configurer"
_IPDHCP="DHCP"
_IPSTATIC="IP fixe"
_SELECTHOW="Choisisser comment l'inteface";
_OBTAINIP="obtient son adress ip"
_SSID="SSID"
_KEY="Clé de sécurité"
_ENTERCREDENTIALS="Entrer la clé de securité pour l'interface sélectionnée"
_INVALIDCREDENTIALS="Données erronées, vous devez introduire le SSID et la clé de sécurité"
_WLANWEP="WEP"
_WLANWPA="WPA"
_WLANOPEN="Ouvert"
_WLANSIGNAL="Signal"
_CREDENTIALSUPDATED="Clé de sécurité du WLAN modifiée"
_ENTERSTATICCONFIG="Entrer la configuration IP"
_NETWORKINTERFACES="Interfaces"
_NETWORKADDRESS="Addresse IP"
_NETWORKMASK="Masque de sous-réseau"
_NETWORKGATEWAY="Passerelle"
_NAMESERVER="DNS"
_INVALIDSTATICCONFIG="Configuration IP invalide, veuillez réessayer"
_STATICCONFIGUPDATED="Configuration IP modifiée"
_DHCPCONFIGUPDATED="L'interface est maintenant configurée en DHCP"
_NETWORKTYPE="Type"
_NETWORKPROTECTION="Protection"
_WLANSCAN="Scan"
_NETWORKNAME="Nom"
_NETWORKSCANAVAILABLE="Scan"
_NETWORKCUSTOM="Personnel"
_NETWORKWLAN="WLAN"
_SCANNINGFORWLAN="Recherche des réseaux disponible..."
_RESTARTINGADAPTER="Dedémarrage"
_TRYINGCONNECTINGTO="Veuillez patienter, tentative de connection à"
_FAILEDTOCONNECTTO="Connection échouée à"
_SUCCESSFULLYCONNECTEDTO="Connecté à"