#!/bin/bash
#
#Copyright 2012 Hexagon & CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Netwerk"
_DESC="Configureer netwerk adapters"
_LOADINGINTERFACES="Adapter aan het laden, een ogenblik geduld aub..."
_NOINTERFACES="Geen netwerk adapters beschikbaar en ze zijn niet verbonden"
_SELECTINTERFACE="Selecteer de adapter die u wilt configureren"
_IPDHCP="DHCP"
_IPSTATIC="Statisch IP"
_SELECTHOW="Selecteer hoe";
_OBTAINIP="aan zijn IP adres moet komen"
_SSID="SSID"
_KEY="Sleutel"
_ENTERCREDENTIALS="Vul de waarden van de adapter in"
_INVALIDCREDENTIALS="Ongeldige WLAN waardes ingevuld, zowel de SSID als de sleutel moeten ingevuld worden"
_WLANWEP="WEP"
_WLANWPA="WPA"
_WLANOPEN="Open"
_WLANSIGNAL="Signaal"
_CREDENTIALSUPDATED="WLAN waardes succesvol bijgewerkt"
_ENTERSTATICCONFIG="Geef statische IP gegevens"
_NETWORKINTERFACES="Adapters"
_NETWORKADDRESS="IP adres"
_NETWORKMASK="Netmask"
_GATEWAY="Gateway"
_NAMESERVER="Nameserver"
_INVALIDSTATICCONFIG="Ongeldige IP waardes, probeer het nogmaals"
_STATICCONFIGUPDATED="Statische IP waardes bijgewerkt"
_DHCPCONFIGUPDATED="Adapter werkt nu via DHCP"
_NETWORKTYPE="Type"
_NETWORKPROTECTION="Beveiliging"
_WLANSCAN="Zoeken"
_NETWORKNAME="Naam"
_NETWORKSCANAVAILABLE="Zoeken"
_NETWORKCUSTOM="Handmatig"
_NETWORKWLAN="WLAN"
_SCANNINGFORWLAN="Aan het zoeken naar beschikbare netwerken..."
_RESTARTINGADAPTER="Bezig met herstarten van"
_TRYINGCONNECTINGTO="Een moment geduld aub. Proberen te verbinden met"
_FAILEDTOCONNECTTO="Kan niet verbinden met"
_SUCCESSFULLYCONNECTEDTO="Succesvol verbonden met"