#!/bin/bash
#
#Copyright 2012 Hexagon & CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Сети"
_DESC="Настройка сетевых интерфейсов"
_LOADINGINTERFACES="Загрузка сетевых интерфейсов..."
_NOINTERFACES="Сетевые интерфейсы не обнаружены или они не подключены"
_SELECTINTERFACE="Выберите сеть для настройки"
_IPDHCP="DHCP"
_IPSTATIC="Статич. IP"
_SELECTHOW="Select how";
_OBTAINIP="should obtain it's IP address"
_SSID="SSID"
_KEY="KEY"
_ENTERCREDENTIALS="Введите параметры для выбранного интерфейса"
_INVALIDCREDENTIALS="Указаны неправильные параметры, должны быть указаны SSID и KEY"
_WLANWEP="WEP"
_WLANWPA="WPA"
_WLANOPEN="Open"
_WLANSIGNAL="Сигнал"
_CREDENTIALSUPDATED="Параметры WLAN успешно обновлены"
_ENTERSTATICCONFIG="Введите параметры статич. IP"
_NETWORKINTERFACES="Интерфейсы"
_NETWORKADDRESS="IP адрес"
_NETWORKMASK="Маска подсети"
_NETWORKGATEWAY="Шлюз"
_NAMESERVER="DNS"
_INVALIDSTATICCONFIG="Неправильные параметры статич. IP, попробуйте еще раз"
_STATICCONFIGUPDATED="Конфигурация статич. IP обновлена"
_DHCPCONFIGUPDATED="Интерфейс настроен с использованием DHCP"
_NETWORKTYPE="Тип"
_NETWORKPROTECTION="Защита"
_WLANSCAN="Сканировать"
_NETWORKNAME="Имя"
_NETWORKSCANAVAILABLE="Scan"
_NETWORKCUSTOM="Вручную"
_NETWORKWLAN="WLAN"
_SCANNINGFORWLAN="Поиск доступных сетей..."
_RESTARTINGADAPTER="Restarting"
_TRYINGCONNECTINGTO="Пытаюсь подключиться к"
_FAILEDTOCONNECTTO="Не удалось подключиться к"
_SUCCESSFULLYCONNECTEDTO="Успешно подключились к"