#!/bin/bash
#
#Copyright 2012 Hexagon & CurlyMo <development@xbian.org>
#
#This file is part of XBian - XBMC on the Raspberry Pi.
#
#XBian is free software: you can redistribute it and/or modify it under the
#terms of the GNU General Public License as published by the Free Software
#Foundation, either version 3 of the License, or (at your option) any later
#version.
#
#XBian is distributed in the hope that it will be useful, but WITHOUT ANY
#WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#details.
#
#You should have received a copy of the GNU General Public License along
#with XBian. If not, see <http://www.gnu.org/licenses/>

_NAME="Sieť"
_DESC="Nadstavenie sieťových rozhraní"
_LOADINGINTERFACES="Nčítavajú sa rozhrania, prosím čakať ..."
_NOINTERFACES="Žiadne sieťové rozhrania niesú dostupné, alebo niesú pripojené"
_SELECTINTERFACE="Vyber rozhranie pre konfiguráciu"
_IPDHCP="DHCP"
_IPSTATIC="Statická IP"
_SELECTHOW="Vyber ako";
_OBTAINIP="by mali byť odzískané IP adresy"
_SSID="SSID"
_KEY="KEY"
_ENTERCREDENTIALS="Zadaj údaje pre vybrané rozhranie"
_INVALIDCREDENTIALS="Nesprávne WLAN údaje boli zadané, musía byť zadané oba údaje, SSID aj KEY"
_WLANWEP="WEP"
_WLANWPA="WPA"
_WLANOPEN="Open"
_WLANSIGNAL="Signál"
_CREDENTIALSUPDATED="WLAN údaje boli úspešne zmenené"
_ENTERSTATICCONFIG="Zadaj statickú IP adresu"
_NETWORKINTERFACES="Rozhrania"
_NETWORKADDRESS="IP adresa"
_NETWORKMASK="Maska siete"
_NETWORKGATEWAY="Brána"
_NAMESERVER="Nameserver"
_INVALIDSTATICCONFIG="Nesprávna statická IP adresa, skús znovu"
_STATICCONFIGUPDATED="Nadstavenie statickej IP bolo aktualizované"
_DHCPCONFIGUPDATED="Rozhranie používa DHCP nadstavenia"
_NETWORKTYPE="Typ"
_NETWORKPROTECTION="Ochrana"
_WLANSCAN="Skenovanie"
_NETWORKNAME="Meno"
_NETWORKSCANAVAILABLE="Skenovanie"
_NETWORKCUSTOM="Vlastné"
_NETWORKWLAN="WLAN"
_SCANNINGFORWLAN="Skenovanie dostupných sietí..."
_RESTARTINGADAPTER="Reštart"
_TRYINGCONNECTINGTO="Prosím čakať. Pripájanie do"
_FAILEDTOCONNECTTO="Nepodarilo sa pripojiť do"
_SUCCESSFULLYCONNECTEDTO="Úspešne pripojené do"